### ISSUE TITLE
Texture files with special names cannot be found

### ISSUE THREAD

**Issue by xlsfs** [donmccurdy/glTF-Transform#1003]
**Describe the bug**
If the texture file name used in the model contains characters such as spaces,
When exporting gltf with 'blander', the uri of the texture will be encoded,
When using 'glTF-Transform', the texture file cannot be found,
maybe need to do some 'decodeURI' processing on the uri

**To Reproduce**
1. Go to [https://drive.google.com/file/d/1nvQ5sKPgKIiLhDoUKlSKi6WqOyoPftil](url)
2. Download the 'model.zip', and unzip it.
3. Run `gltf-transform optimize model/a.gltf a_out.gltf `
4. See error "error: ENOENT: no such file or directory, open '/model/texture/Map%20823%22%E7%9A%84%E5%89%AF%E6%9C%AC.jpg'"

![image](https://github.com/donmccurdy/glTF-Transform/assets/7886342/0c30a780-7f07-41c9-a313-175159c7ff7b)

**Expected behavior**
The gltf file can be opened correctly and output correctly

**Versions:**
 - Version: [v3.4.4]
 - Environment: [Node.js]

**Comment by donmccurdy** [comment]
Thanks @xlsfs! Published a fix to v3.4.5.

**Comment by xlsfs** [comment]
In the new version, the file can be read correctly by "glTF-Transform", but there is a problem with the file name of the output texture file. For example, "Map 1.png" will be saved as "Map%201.png" on the disk. Hope it can be saved correctly with the original name
<img width="514" alt="image" src="https://github.com/donmccurdy/glTF-Transform/assets/7886342/ddbeddc4-92f2-459b-9488-10056bcf0a97">

1. Go to [model.zip](https://drive.google.com/file/d/1nvQ5sKPgKIiLhDoUKlSKi6WqOyoPftil)
2. Download the 'model.zip', and unzip it.
3. Run gltf-transform optimize ./model/a.gltf ./model_out/a.gltf

Version: [v3.7.1]
Environment: [Node.js]

**Comment by donmccurdy** [comment]
Will take a look!

**Comment by xlsfs** [comment]
Tested in v3.7.3, the name can be output correctly, thank you
