### ISSUE TITLE
Unable to load glTF file missing images tag from JSON

### ISSUE THREAD

**Issue by user-ops** [donmccurdy/glTF-Transform#101]
When loading file via readGLTF I encounter a throw.
It appears that you're trying to access the images tag, which may or may not be specified.
https://github.com/donmccurdy/glTF-Transform/blob/5719132bb3f8e73cc60719eb1fcc1487502d65d4/packages/core/src/io/web-io.ts#L69

According to spec this shouldn't be required
https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#gltf

**Comment by donmccurdy** [comment]
Thanks! You're right, this is a bug. I got it correct in NodeIO...

https://github.com/donmccurdy/glTF-Transform/blob/5719132bb3f8e73cc60719eb1fcc1487502d65d4/packages/core/src/io/node-io.ts#L94-L96

... but missed it in WebIO. Would you be able to send a PR by any chance? 🙂

**Comment by user-ops** [comment]
#103 Used the same format you've used in node-io.ts, should be functioning now.

**Comment by donmccurdy** [comment]
Looks great, thank you! The fix will be available in v0.7.
