### ISSUE TITLE
Support skipping individual textures during ktx compression

### ISSUE THREAD

**Issue by mwbeene** [donmccurdy/glTF-Transform#1017]
There have been several cases where I'd like to skip textures individually when using ktx compression. Skipping entire slots can solve the problem visually but leads to larger files than necessary since some textures of that slot type look fine compressed.

I'm imagining something like this:
--skip "{myTextureName1,myTextureName2}"

Currently, if I want to achieve this I need to export my model as a gltf, run toktx on individual textures, then re-link them into my gltf. This can be particularly painful when trying to iterate quickly, especially since my particular software has been designed to work with glb files.

**Comment by donmccurdy** [comment]
In certain other operations I've included a `pattern` option. This would be a RegExp for script authors, or a glob for CLI users. Something like:

> `--pattern <pattern>` Pattern to match textures, by name or URI.

```
gltf-transform etc1s in.glb out.glb --pattern "!{myTextureName1,myTextureName2}"
```

If that option were added to `etc1s` and `uastc` commands, would that work?

**Comment by pavel-mazhuga** [comment]
@donmccurdy is there a problem with excluding a file which name contains spaces? For example, ```--pattern="!{floor.greece_batch - test_CyclesBake_COMBINED}"``` doesn't work. What did I miss?

**Comment by donmccurdy** [comment]
@pavel-mazhuga I'm not aware of a limitation related to spaces. If it helps, the globbing library used here is micromatch: https://github.com/micromatch/micromatch. It might be easier to match just a specific substring in the texture you want to omit, if possible.

**Comment by pavel-mazhuga** [comment]
Thanks, gonna try it.
