### ISSUE TITLE
weld has huge normal tolerance

### ISSUE THREAD

**Issue by rotu** [donmccurdy/glTF-Transform#1028]
`gltf-transform weld` welds vertices with relatively large discrepancies in normal. There is not a command-line option to change this threshold.

<img width="205" alt="image" src="https://github.com/donmccurdy/glTF-Transform/assets/119948/6617ee3f-ae0d-4bd2-a9f4-331fde82f470">
<img width="205" alt="image" src="https://github.com/donmccurdy/glTF-Transform/assets/119948/0f31f111-95cb-474c-88f5-84ff489bafc8">

**Comment by donmccurdy** [comment]
Thanks @rotu! I agree 0.5 is probably a larger tolerance than appropriate for the NORMAL attribute. I'll do some tests on other possible values, but if you have ideas or sample models you'd like me to consider, please do share those. :)
