### ISSUE TITLE
Instancing lose node names

### ISSUE THREAD

**Issue by enruilo1** [donmccurdy/glTF-Transform#1034]
Hi, when i use "gltf-transform instance", node names was losed in the instancing process. I want to preserve that names because it contains guid info for each node mesh and i have so many info attached to that guid. 
Is there any way to preserve that name and when i load in threejs know what guid is for specific instance?
Adjoint a gltf with several nodes with guid names
[GpuInstancing_old.zip](https://github.com/donmccurdy/glTF-Transform/files/12112404/GpuInstancing_old.zip)

**Comment by donmccurdy** [comment]
Hi @enruilo1! Removing nodes is inherent to what the `instance` operation is doing, as explained a bit more in https://github.com/donmccurdy/glTF-Transform/discussions/1018#discussioncomment-6398390. There is no canonical way to associate a string name with each instance, at this time. There are certain ways to associate numerical IDs with instances, but I'm not sure whether that works for your goals, and you'd need to write some code in three.js to access those IDs efficiently from the `THREE.InstancedMesh` object.

More complete workarounds would depend on draft/proposed glTF extensions, such as https://github.com/KhronosGroup/glTF/pull/2082.

**Comment by javagl** [comment]
With the [`EXT_instance_features`](https://github.com/CesiumGS/glTF/tree/3d-tiles-next/extensions/2.0/Vendor/EXT_instance_features) extension, you can assign (numerical) IDs to the instances. This is done by adding an attribute to the `EXT_mesh_gpu_instancing` object that contains these IDs. These IDs could then be used in a client application, to look up the GUID based on the numeric ID. (You could also use the `EXT_structural_metadata` extension for this, but if you don't want to associate more "metadata" with the instances, only using the numeric ID may be simpler). The `EXT_instance_features` extension is not sooo widely supported by viewers, but an example glTF asset that uses it can be found in the [3D Tiles glTF extensions samples](https://github.com/CesiumGS/3d-tiles-samples/tree/main/glTF/GpuInstancesMetadata).

**Comment by enruilo1** [comment]
Cool ¡¡ EXT_instance_features and EXT_mesh_gpu_instancing could be a great solution and THREEJS is able to read EXT_instance_features and introduce that info in a "userData" property:
![Captura de pantalla 2023-07-23 130803](https://github.com/donmccurdy/glTF-Transform/assets/46839816/549de7d8-6c10-44c7-b714-3635aa86441b)

 BUT we have two problems:
1.- Gltf-Transform not support EXT_instance_features (i dont see it).
2.- When EXT_instance_features refer to EXT_structural_metadata, "propertyTable" is not read by THREEJS properly (could be an issue for that repo), but it could be insteresting to "at least" try to get work of EXT_instance_features.

@donmccurdy @javagl 

Adjoin an image when instance GLTF (by GLTF-TRANSFORM) doesnt contain any metadata:
![Captura de pantalla 2023-07-23 123137](https://github.com/donmccurdy/glTF-Transform/assets/46839816/997da165-4de2-4eee-a20b-6ffef9741c25)

**Comment by donmccurdy** [comment]
@enruilo1 there's no out of the box solution here, three.js does not understand `EXT_instance_features`, it just passes through the raw JSON from unknown extensions. It's possible to write an implementation that loads the extension and register that with THREE.GLTFLoader, but I suspect it's more work than you may want for this. Similarly, glTF Transform does not include an implementation of the extension either, although it's possible to [implement custom extensions yourself](https://gltf-transform.dev/extensions).

How many node(s) are you instancing? If the number is <100, then I suspect getting this working may be more work than it is worth to you.

***

The quickest method I can see would be for you to create a custom version of the [`instance()`](https://github.com/donmccurdy/glTF-Transform/blob/main/packages/functions/src/instance.ts) function used by glTF Transform. Where it creates each batch ...

https://github.com/donmccurdy/glTF-Transform/blob/c043cb2829da8f5d437b5a17a4925c012da71ce0/packages/functions/src/instance.ts#L165-L169

... you'd want to add some code that creates an empty `_ID` attribute. Then where it writes data for each node ...

https://github.com/donmccurdy/glTF-Transform/blob/c043cb2829da8f5d437b5a17a4925c012da71ce0/packages/functions/src/instance.ts#L82-L88

... you'd want to set the (integer) ID for each, and create an ordered array of the node names. That array can then be assigned to the instanced mesh or node, and it will be available in three.js as `.userData` ...

```js
mesh.setExtras({instanceNames: [ 'name1', 'name2', 'name3', ... ]});
```

Then you can run your custom version of the instance() function on whatever models you need:

```js
import { NodeIO } from '@gltf-transform/core';
import { ALL_EXTENSIONS } from '@gltf-transform/extensions';

const io = new NodeIO().registerExtensions(ALL_EXTENSIONS);
const document = await io.read('path/to/model.glb');

await document.transform( customInstance() );

await io.write('path/to/model_out.glb', document);
```
