### ISSUE TITLE
Merging documents loses texture transform information

### ISSUE THREAD

**Issue by Inviz** [donmccurdy/glTF-Transform#105]
Hello! I really like your library, but I've encountered some challenges in creating multiple glb -> gltf-transform -> gltfpack pipeline. 

One specific thing that i stumbled upon was the fact that after merging documents, the "KHR_texture_transform" information does not get carried over. I had to cache and it manually restore it to a new document.

**Comment by Inviz** [comment]
I think the same thing happens (or more accurately does not happen) with node extras. I worked around it by saving extras to map and restoring it after merge.

**Comment by donmccurdy** [comment]
Thanks! I was able to reproduce the issue with KHR_texture_transform, but not with node extras. Could you share example files, or a unit test, that demonstrate the issue?

**Comment by Inviz** [comment]
[Archive.zip](https://github.com/donmccurdy/glTF-Transform/files/5349428/Archive.zip)
Merging these two files under 2mb total takes 7 seconds via cli

**Comment by Inviz** [comment]
Hmm... I can't reproduce it now either with extras. I feel a little silly. I'll post back if I figure out what happened to me.

**Comment by donmccurdy** [comment]
No worries! I'll work on the texture transform issue.
