### ISSUE TITLE
Disposing of buffers after merging is slow

### ISSUE THREAD

**Issue by Inviz** [donmccurdy/glTF-Transform#107]
I followed your example to merge some glb files. Merging two 10mb files, takes 10 seconds to dispose the N+1 buffers. It's by far the slowest part of my whole pipeline. I wonder if there could be a quicker way to do that?

**Comment by donmccurdy** [comment]
I'm surprised by that, wouldn't there only be one buffer to dispose? I have a guess at what might be happening, but if you can share an example that may help, too. Thanks!

**Comment by Inviz** [comment]
[Archive.zip](https://github.com/donmccurdy/glTF-Transform/files/5349434/Archive.zip)
Merging these two files under 2mb total takes 7 seconds via cli. I think `poses.glb` is the one to blame

**Comment by donmccurdy** [comment]
Thanks! I'll look into this.

**Comment by donmccurdy** [comment]
Performance should be noticeably better in v0.7.2. 👍

**Comment by Inviz** [comment]
Wow that's a dramatic improvement. 12s -> 0.3s for my files. 

Thanks a lot for the fist turnaround! Great work!

**Comment by Inviz** [comment]
Although interestingly upstream `gltfpack` started segfaulting now on the files output with 0.72 gltf-transform. The version of `gltfpack` in npm is fine though... really weird

**Comment by Inviz** [comment]
Interesting... So I have two files generated with blender using `library override` feature. That feature allows creating a single "source" blender file, and then include it into another blender file and customize settings of meshes, apply different animations, etc. So basically it's like if meshes were the same, but their transforms and animations are different. 

If I merge those files into one in 0.72, run dedupe, and then later try to open the resulting file later in gltfpack, it segfaults.

If I either
1) Use non-upstream `gltfpack`
2) Do not run `dedupe`

there is no segfault. I'm preparing test files

**Comment by Inviz** [comment]
[Archive.zip](https://github.com/donmccurdy/glTF-Transform/files/5353147/Archive.zip)

```
gltf-transform merge office-job.glb office.glb output.glb
gltf-transform dedup output.glb output.dedupe.glb
../../../../../meshoptimizer/gltfpack -i output.dedupe.glb -o 1.glb
[1]    77530 segmentation fault  ../../../../../meshoptimizer/gltfpack -i output.dedupe.glb -o 1.glb``

gltfpack is compiled from sources.

**Comment by Inviz** [comment]
So like yeah... it could have be an issue with `gltfpack`, but it seems that it is related to 0.7.2. change. So either it 0.7.2. does some really agressive deduping which gltfpack can't make sense of, or there is a bug with deduping and it does something incorrectly

**Comment by donmccurdy** [comment]
> If I merge those files into one in 0.72, run dedupe, and then later try to open the resulting file later in gltfpack, it segfaults.

Hmm... there shouldn't be any difference in the output of v0.7.1 and v0.7.2, except for preserving KHR_texture_transform. If you have two GLBs produced by glTF-Transform before/after, where one segfaults gltfpack and the other doesn't, could you share those? Or maybe it's worth running the model through https://github.khronos.org/glTF-Validator/ to check.

**Comment by Inviz** [comment]
@donmccurdy in the archive above, there're 2 files `office.glb` and `office-job.glb` merging/deduping them in 0.7.1 and in 0.7.2. produces different result. I guess i can make final side-by-side samples for you... Give me a minute

**Comment by Inviz** [comment]
[Archive 2.zip](https://github.com/donmccurdy/glTF-Transform/files/5356427/Archive.2.zip)
See the archive with source files and output files for 0.7.1 and 0.7.2. The files have slightly different size, and 0.7.2. crashes gltfpack compiled from sources

**Comment by Inviz** [comment]
Good point on validator. The 0.7.2. file does not pass the validator.

**Comment by donmccurdy** [comment]
Ok thanks — yeah it looks like my 0.7.2 optimization broke something. Strange that the model renders correctly before and after, but the validator failing is good confirmation. I'll look into that soon.

**Comment by Inviz** [comment]
Yeah, might be just some empty objects/meshes or something, according to validator. So it makes sense that it renders correctly, and also makes sense that it could crash gltfpack,

Thanks! Happy weekend. 

I've been googling a lot of stuff about gltf, three.js, materials, colors, etc recently. You're everywhere in those results! Thanks a lot for your hard work and help for the community.

**Comment by Inviz** [comment]
Splendid work! It fixed the issue, and works really fast. About 50 times faster than before :')
