### ISSUE TITLE
draco: using draco compression results in wonky mesh 

### ISSUE THREAD

**Issue by eLenoAr** [donmccurdy/glTF-Transform#1074]
When using the `gltf-transform draco` command (cli and npm) with version 3.4.0 and prior, the resulting mesh is like the expected original mesh. But using v3.4.1 and later breaks the mesh. it is always kind of wonky.

The only relevant line I can see is this -> changing the `encoder` to `expertEncoder`.

https://github.com/donmccurdy/glTF-Transform/compare/v3.4.0...v3.4.1#diff-670d375d9bfe763258b16352fb3c3a69b5daf53015c8ab54e3ed93ba5acd95b2R68

<img height="300" alt="original" src="https://github.com/donmccurdy/glTF-Transform/assets/1316732/0348eef9-a463-4fd2-be15-02ed526420a3">

<img height="300" alt="v3.5.1" src="https://github.com/donmccurdy/glTF-Transform/assets/1316732/fe5f5f93-c18f-4b80-b75c-498c41affd81">

**To Reproduce**
1. go to https://gltf.report
2. load demo-model.glb from zip
3. export with draco compression (edgebreaker & mesh)
4. load the draco compressed model

**Expected behavior**
Original mesh with Draco compression like in version 3.4.0 and prior.

**Versions:**
 - Version: since v3.4.1
 - Environment: Browser, Node.js, CLI

**Sample model**
[demo-model.zip](https://github.com/donmccurdy/glTF-Transform/files/12474750/demo-model.zip)

**Comment by donmccurdy** [comment]
Thank you @eLenoAr – this should be fixed soon, by https://github.com/donmccurdy/glTF-Transform/pull/1077.
