### ISSUE TITLE
Deduping textures resolution callback 

### ISSUE THREAD

**Issue by Inviz** [donmccurdy/glTF-Transform#108]
I like the deduping feature! Really useful. However one thing i've had is that i use multiple glb files with resources packed in, and merge them together. Sometimes some of them have slightly outdated versions of shared textures baked in. I wonder if there could be some sort of a callback to tell that texture is the same (e.g. by filename), instead of contents.

**Comment by donmccurdy** [comment]
Are you using the dedup function through the CLI, or in a script? If the filenames really are 100% the same then they presumably refer to the same file on disk. This might be an unusual enough situation that I'd recommend scripting with the glTF-Transform API instead of using 'dedup' function correctly, but if it turns out that it's not easy to do that, I am glad to help figure out how to make it easy. :)

**Comment by Inviz** [comment]
I'm using it in a script, but the textures are already baked in to the files (which i guess is something i shouldn't do so i can avoid this issue altogether).

Okay, let me try to switch my workflow to avoid baking in textures into glb files, i think that's reasonable approach. Thanks for consideration and suggestions.

**Comment by Inviz** [comment]
So it looks like Blender does not allow me to save glb/gltf files without packing/exporting unique images. So if I've got two files using same texture, the image will be packed into each of files bundles. And if I update one of the files, with new version of image, now i have undedupable images. So the only solution is to each time texture is update, is to re-export all files that use that image and run dedupe script. Which isn't nice. I wish i could dedupe textures by texture/material name or something... but that might be too specific of a task for your lib.

**Comment by donmccurdy** [comment]
> So it looks like Blender does not allow me to save glb/gltf files without packing/exporting unique images.

It should be possible to avoid this, if you pre-pack the images in the way that Blender needs before exporting. For example, the roughness/metalness and baseColor/alpha maps will have to be combined. There may be other things involved, or that Blender could improve, see https://github.com/KhronosGroup/glTF-Blender-IO/pull/1099 for some discussion.
