### ISSUE TITLE
Get Accessor's `stride`

### ISSUE THREAD

**Issue by CITIZENDOT** [donmccurdy/glTF-Transform#1088]
**Is your feature request related to a problem? Please describe.**
`InterleavedBuffer` can have stride that's different from `itemSize` (or in this case: [`getElementSize`](https://gltf-transform.dev/modules/core/classes/Accessor)). Currently, I couldn't find any way to access the stride of the accessor.

**Comment by donmccurdy** [comment]
The in-memory vertex layout of a glTF Transform [Document](https://gltf-transform.dev/modules/core/classes/Document) is never interleaved. When serializing the file to disk, I/O utilities may interleave the data (see [`.setVertexLayout`](https://gltf-transform.dev/modules/core/classes/PlatformIO#setVertexLayout)), and it's at that point that stride comes into the picture. So I don't think that an `accessor.getStride()` method would make sense for the current API.

**Comment by donmccurdy** [comment]
Is there a reason you need or expect to find this information in glTF Transform, as opposed to in an engine like three.js?

**Comment by CITIZENDOT** [comment]
I'm extracting morphAttributes on the server (deno) side and sending them to the client (streaming targets as needed). I'm sending only the `array` (typed array) to the client.

To recreate the morphAttribute, I want other values like `offset`, `normalized`, `stride`. I'm extracting morphAttributes using **gltf-Transform** because it's the only tool which supports the deno runtime 🥹.

**Comment by donmccurdy** [comment]
Hm, in that case the data from `accessor.getArray()` is not interleaved, and you shouldn't need to worry about the stride... are you adding the morph targets to a base mesh that is already interleaved here? It might be best to de-interleave the base mesh I think, simplifying this a bit.

**Comment by CITIZENDOT** [comment]
When loading the GLB on threejs, I see it's interleaved. So yea. Can I just use the buffers from gltf-transform and construct BufferAttribute (instead of Interleaved)?

**Comment by donmccurdy** [comment]
If the original GLB is created by glTF Transform, you could de-interleave it with the `--vertex-layout separate` flag on the CLI, or using the scripting API. For example:

```bash
gltf-transform cp in.glb out.glb --vertex-layout separate
```

**Comment by CITIZENDOT** [comment]
Okay, will do this. Thanks!

**Comment by CITIZENDOT** [comment]
There is a massive size change after de-interleaving vertices:
```
❯ gltf-transform cp in.glb out.glb --vertex-layout separate
warn: Decoded EXT_meshopt_compression. Further compression will be lossy.
info: in.glb (81.38 MB) → out.glb (245.77 MB)
```
Is this expected?

**Comment by donmccurdy** [comment]
We'll have to decompress to deinterleave, but you can recompress in the same step with:

```bash
gltf-transform meshopt in.glb out.glb --vertex-layout separate
```

_Ideally_ we'd start from the uncompressed source copy, and get de-interleaved output from whatever tool created that. Compressing, decompressing, and recompressing can add some data precision loss. If the model was originally compressed with `gltf-transform` you can just add `--vertex-layout separate` to whatever command you were using.

**Comment by CITIZENDOT** [comment]
That did the trick. Although the size is little-bit larger than the gltfpack, it's fine. Shall we close this?

**Comment by donmccurdy** [comment]
Sounds good - feel free to comment or reopen if you have other issues though!
