### ISSUE TITLE
Unable to install `@gltf-transform/functions` in deno

### ISSUE THREAD

**Issue by CITIZENDOT** [donmccurdy/glTF-Transform#1092]
**Describe the bug**
Cannot import/install `@gltf-transform/functions`

**To Reproduce**
Open deno REPL and import something from `@gltf-transform/functions`.
```
> import { quantize } from 'https://esm.sh/@gltf-transform/functions';
Uncaught TypeError: Import 'https://esm.sh/v132/sharp@0.32.5/denonext/sharp.mjs' failed: 500 Internal Server Error
    at https://esm.sh/v132/ndarray-pixels@3.0.4/denonext/ndarray-pixels.mjs:2:71
    at async <anonymous>:2:23
```

**Versions:**
 - Version: 3.5.1
 - Environment: Deno

**Additional context**
It appears to be sharp isn't built correctly: https://esm.sh/v132/sharp@0.32.5/denonext/sharp.mjs

**Comment by donmccurdy** [comment]
Related:

- https://github.com/lovell/sharp/issues/2583
- https://github.com/donmccurdy/ndarray-pixels/pull/137
- https://github.com/donmccurdy/ndarray-pixels/issues/87
- https://github.com/donmccurdy/glTF-Transform/pull/1075

It seems like this "should" work, but the error is two levels down in the dependencies. Do you know if Deno supports tree-shaking? Or what version of Deno you're using? I'm not sure I understand why it would be importing `sharp` when only the `quantize` function is loaded.

The only solutions I see at the moment would be:

1. Add another image processing implementation to `ndarray-pixels` specifically for Deno. Not appealing if `sharp` _should_ work in Deno...
2. Try to ensure `sharp` is always lazily imported in `ndarray-pixels`. Not sure whether I can do that in a sanity-preserving way without switching to ESM-only builds. I'd like to go ESM-only eventually, but the whole CJS/ESM situation is a headache.
3. ???

As a workaround you could also copy/paste the bits of `quantize.js` that you need, though I understand that's probably not appealing. :) 

https://github.com/donmccurdy/glTF-Transform/blob/main/packages/functions/src/quantize.ts

**Comment by CITIZENDOT** [comment]
```
❯ deno --version
deno 1.36.0 (release, x86_64-unknown-linux-gnu)
v8 11.6.189.12
typescript 5.1.6
```
[Tree shaking is added to deno in v1.5](https://deno.com/blog/v1.5#new-and-improved-bundling). I'll copy/paste the `quantize.js` for now. I think lazy import is a good approach though.

**Comment by birkskyum** [comment]
- https://github.com/denoland/deno/issues/20071

**Comment by donmccurdy** [comment]
Related:

- https://github.com/lovell/sharp/issues/3750

**Comment by donmccurdy** [comment]
I think upcoming Sharp versions will fix this, but in any case let's track general support for the Deno runtime in https://github.com/donmccurdy/glTF-Transform/issues/457.
