### ISSUE TITLE
Function to flatten node hierarchy, merge meshes

### ISSUE THREAD

**Issue by donmccurdy** [donmccurdy/glTF-Transform#11]
Plan —

- [x] (1) Add `transformPrimitive(prim, matrix)`, `transformMesh(mesh, matrix)`
    - #700
    - #657
- [x] (2) Add `clearNodeParent(node)`, `clearNodeTransform(node)`. Requires (1).
    - Detaches node from its parent, applies world transform to `node.mesh`
    - #784
- [x] (3) Add `document.transform(flatten())`. Requires (1) and (2).
    - https://github.com/donmccurdy/glTF-Transform/pull/790 
    - Deletes unneeded empties (with options to keep them)
    - Keeps armatures
    - ~~Clears parents and transforms of nodes where possible~~
- [ ] (4) Add `joinPrimitives(prim: Primitive[])`.
    - #707 
- [ ] (5) Add `document.transform(join())`. Requires (1), (2), (3), (4).
    - Assumes node hierarchy has already been flattened as desired, using (3).
    - Joins all compatible meshes that are siblings in the scene hierarchy.
    - `TODO`: Maximum vertex counts per draw? Spatial locality?
    - #658

***

Other considerations —

Considerations:

- Update IBMs if node is a joint?
- ~~`clearNodeTransform` must warn on attached camera or light~~
- Apply world transforms to TRS animations?
- Apply world transforms to volumetric properties?
- Detach shared vertex streams? Deal with detached accessors?

**Comment by donmccurdy** [comment]
Part of prune package?

**Comment by dbuck** [comment]
I potentially could use this functionality also, though not fully flatten, I just want to merge a few of the meshes together, and am wondering whether I should do it in the obj before we get to gltf, or just tack it on to the pipeline scripts here ;)

In terms of how to psuedocode approach it, am I on track here?

Create new node/mesh/accessors to receive the merged details
targetPositionArray = accessor.getArray .. etc for each type

list nodes, filter to the ones I want to merge
from those nodes, get the meshes
from those meshes, get the accessors  for position/normal/uv
from the accessors get the arrays
concat them with the targetArray
dispose :all-the-things:

How should it handle textured meshes? Attach newly merged node to a scene, profit?

**Comment by dbuck** [comment]
For the generalized transform, an input filter to select which items to merge would be helpful, ex: `(mesh: Mesh) => boolean` if Mesh is the correct level to select from? That would allow a user to: merge only meshes where mesh.name contains 'boots'

**Comment by donmccurdy** [comment]
That's the right process, with a couple other things you'd need to check for:

- Do the nodes all have the same world transform? If not, you'll want to apply the inverse world matrix to the vertex positions before merging.
- Do the nodes all have the same attributes (TEXCOORD_0, COLOR_0, ...), and do the attributes all have the same component types? If not, you'll either need to choose which to merge accordingly, or add/remove attributes from some.
- Do the nodes all have the same material properties? Probably not, but material colors can be written into vertex colors to handle simple cases. The harder case is merging textures, which would require efficiently packing textures together and then shifting UVs to the new texture positions. See https://github.com/donmccurdy/glTF-Transform/issues/230.

**Comment by donmccurdy** [comment]
Very much (a) untested and (b) not exhaustive (e.g. this needs to handle all vertex attribute types, and apply node transforms), but this would be a starting point for writing a simple flatten function. Posting for future reference:

```ts
import { Accessor, BufferUtils, Primitive } from '@gltf-transform/core';
import { dedup, prune, unweld, weld } from '@gltf-transform/functions';

const p = [], n = [], t = [];

await document.transform(unweld()); // Unweld now, re-weld later.

for (const mesh of document.getRoot().listMeshes()) {
  for (const prim of mesh.listPrimitives()) {
    p.push(prim.getAttribute('POSITION').getArray());
    n.push(prim.getAttribute('NORMAL').getArray());
    t.push(prim.getAttribute('TEXCOORD_0').getArray());
    prim.dispose();
  }
  mesh.dispose();
}

const material = document.getRoot().listMaterials().pop();
const mergedPrim = document.createPrimitive()
  .setMode(Primitive.Mode.TRIANGLES)
  .setMaterial(material)
  .setAttribute('POSITION', flattenArray('VEC3', p))
  .setAttribute('NORMAL', flattenArray('VEC3', n))
  .setAttribute('TEXCOORD_0', flattenArray('VEC2', t));

const mergedMesh = document.createMesh('MatildaMesh').addPrimitive(mergedPrim);
const mergedNode = document.createNode('MatildaNode').setMesh(mergedMesh);
document.getRoot().getDefaultScene().addChild(mergedNode);

await document.transform(weld(), dedup(), prune()); // Clean up.

function flattenArray(type, arrays: Float32Array[]): Accessor {
  const array = new Float32Array(BufferUtils.concat(arrays.map(BufferUtils.trim)));
  return document.createAccessor().setType(type).setArray(array);
}

```

**Comment by dbuck** [comment]
Slight tangent, but likely to be found here by anyone searching for it, I was using this to merge a few separate gltfs together prior to using a variation of the ^ script to merge the nodes together (though my meshes are pretty basic/simple, so ymmv).

```
import { NodeIO, Document } from '@gltf-transform/core';

const io = new NodeIO();
const document = new Document();

// Add all files to 1 document
gltfFilepaths.forEach((p) => document.merge(io.read(p)));

// Use a single buffer in the merged document
const buffer = document.getRoot().listBuffers().pop();
document.getRoot().listAccessors().forEach((a) => a.setBuffer(buffer));
document.getRoot().listBuffers().forEach((b, index) => index > 0 ? b.dispose() : null);

// Combine children into a single scene
let mergedScene;
document.getRoot().listScenes().forEach((scene, index) => {
  if (index > 0) {
    scene.listChildren().forEach((node) => mergedScene.addChild(node) );
    scene.dispose();
  } else {
    mergedScene = scene;
  }
});

// Merge :all-the-things:
```

**Comment by donmccurdy** [comment]
Related, a very simple version of `flatten()` that unnests the node hierarchy (but does not merge meshes) is described in https://github.com/donmccurdy/glTF-Transform/issues/463. That part works, but `prune()` does not yet remove the empty leaf nodes left behind.

**Comment by donmccurdy** [comment]
great test case for a merge+weld+simplify pipeline:

<img width="666" alt="Screen Shot 2022-08-13 at 12 35 27 AM" src="https://user-images.githubusercontent.com/1848368/184468916-c0012c9d-8dfe-4cde-bc3b-50e0941e671c.png">

https://sketchfab.com/3d-models/sculpt-january-day-19-lovecraftian-34ad2501108e4fceb9394f5b816b9f42

its vertices are divided arbitrarily among primitives, so the topology isn't smooth until those primitives are merged.

**Comment by donmccurdy** [comment]
Added draft/proposed plan above.

**Comment by donmccurdy** [comment]
Another test case, this model begins with 70 meshes but can be reduced as far as 1 mesh with 14 mesh primitives.

https://sketchfab.com/3d-models/free-1972-datsun-240k-gt-b2303a552b444e5b8637fdf5169b41cb

**Comment by donmccurdy** [comment]
Work in progress toward (2) —

- https://github.com/donmccurdy/glTF-Transform/pull/784

**Comment by yunusbayraktaroglu** [comment]
Functionality to apply world matrix to attributes would be great.

**Comment by donmccurdy** [comment]
Hi @yunusbayraktaroglu – that part of the functionality is done, if you'd like to use these methods from `@gltf-transform/functions`:

- `transformMesh( mesh, matrix )`
- `transformPrimitive( mesh, matrix )`

https://gltf-transform.donmccurdy.com/functions.html#transformmesh

The other features above are still in progress, though.

**Comment by yunusbayraktaroglu** [comment]
Thank you Don, I couldn't get your example working. I think **BufferUtils.trim** is deprecated.

```
function trim(srcBuffer){
  const { byteOffset, byteLength } = srcBuffer;
  const array = srcBuffer.buffer.slice(byteOffset, byteOffset + byteLength);
  return array;
}
function flattenArray(arrayType, arrays) {
  const array = new Float32Array(BufferUtils.concat(arrays.map(trim)));
  return document.createAccessor().setType(arrayType).setArray(array);
}
```

Still no luck.

**Comment by donmccurdy** [comment]
Sorry, no I would not rely on the examples above as a working solution. The features needed to flatten a node hierarchy are still in progress above. I meant to say the functions that apply a matrix transform to vertex attributes are complete, the rest is ongoing.
