### ISSUE TITLE
Missing elements imported into Blender before and after optimization

### ISSUE THREAD

**Issue by xlsfs** [donmccurdy/glTF-Transform#1100]
**Describe the bug**
When importing the optimized gltf file into Blender, some elements are lost. 
However, these elements remain intact when the file is imported into gltf.report. 
I am uncertain as to why this problem arises.

**To Reproduce**
1. Go to [model.glb](https://drive.google.com/file/d/1oU5_TvQvfmxOHc3m0S4er3PvciMAj9fQ/view?usp=drive_link)
2. Download the 'model.glb'
3. Run gltf-transform optimize --flatten false --join false --simplify false model.glb model_out.glb 
4. import model.glb to Blender.
5. import model_out.glb to Blender.
6. Compare the two

![image](https://github.com/donmccurdy/glTF-Transform/assets/7886342/1cb15432-6421-43aa-9e0e-8c728aaf6749)

**Expected behavior**
The structure imported into Blender is the same before and after optimization

**Versions:**
 - Version: [v3.7.0]
 - Environment: [Node.js]

**Comment by donmccurdy** [comment]
Hi @xlsfs — this tool applies GPU instancing using the `EXT_mesh_gpu_instancing` glTF extension. Blender currently does not support that extension, so any meshes that are instanced will disappear from Blender. If you'd like to skip that optimization you may do so:

```
gltf-transform optimize model.glb model_out.glb --no-flatten --no-join --no-instance
```

You may also find the `--verbose` flag helpful, as it shows in a bit more detail what's happening during the optimization.

**Comment by xlsfs** [comment]
thank you for your reply
