### ISSUE TITLE
"Inspect format md" is adding non-basic ASCII? 

### ISSUE THREAD

**Issue by echadwick-artist** [donmccurdy/glTF-Transform#1103]
`gltf-transform inspect file.glb --format md >file.md
`
This command seems to be adding non-basic ASCII characters to the output file. 

![2023-09-24 18_20_59-StainedGlassLamp-KTX-BasisU-Volume-ETC1S-370 md - Visual Studio Code](https://github.com/donmccurdy/glTF-Transform/assets/40177036/0f1c14a3-806c-4faa-87ee-c5ff0b8e4097)

**To Reproduce**
1. Install gltf-transform with npm
2. Launch windows cmd
3. cd to folder with the glb
4. `gltf-transform inspect file.glb --format md >file.md`
5. Open the resulting md file in Visual Studio Code v1.81.1

**Expected behavior**
I think the MD file should only contain basic ASCII characters?

**Versions:**
 - Version: 3.7.0
 - Environment: npm v10.1.0 in Windows 11 cmd

**Additional context**
glTF file I ran into this problem with: https://github.com/KhronosGroup/3D-Formats-Guidelines/blob/main/samples/StainedGlassLamp/StainedGlassLamp-KTX-BasisU-Volume-ETC1S.glb

**Comment by donmccurdy** [comment]
Thanks @echadwick-artist! This should be fixed by https://github.com/donmccurdy/glTF-Transform/pull/1107 soon.
