### ISSUE TITLE
Resample Error : Missing Float32Array input

### ISSUE THREAD

**Issue by Makio64** [donmccurdy/glTF-Transform#1113]
**Describe the bug**
I tried resample on different glb with animations but i keep getting an error when using resample()
`Failed to get file info: Error: Missing Float32Array input.`

For example on this animated glb : https://www.dropbox.com/scl/fi/ldkc3ea7s9bsslnmomy8x/rhino.glb?rlkey=dbfvg8e2zy1uak5qo28s5vu23&dl=0

**To Reproduce**
```
import { ready, resample } from 'keyframe-resample'
//...
		let document = await io.read(filepath)
		await document.transform(resample()) // Error
		await io.write(output, document)
```

Got the same error with the wasm version : 
`await document.transform(resample({ ready, resample }));`

**Expected behavior**
No error and resample done.

**Versions:**
 - Version: 
 - "keyframe-resample": "^0.0.15",
 - "@gltf-transform": "^3.7.1",
 - Node.js 20.+
 
**Additional context**

**Comment by donmccurdy** [comment]
The [example in the docs](https://gltf-transform.dev/modules/functions/functions/resample) might be misleading here, since it's unclear which "resample" is which. Either of these works for me locally ...

```js
import { NodeIO } from '@gltf-transform/core';
import { resample } from '@gltf-transform/functions';
import { ready, resample as resampleWASM } from 'keyframe-resample'

const io = new NodeIO();
const document = await io.read('./rhino.glb');

await document.transform(resample({ready, resample: resampleWASM}));
```

```js
import { NodeIO } from '@gltf-transform/core';
import { resample } from '@gltf-transform/functions';

const io = new NodeIO();
const document = await io.read('./rhino.glb');

await document.transform(resample());
```

... do you get errors with this?

**Comment by Makio64** [comment]
Worked perfectly, thanks !

As you guessed I got confused by the doc and didnt import resample from the '@gltf-transform/functions'

**Comment by donmccurdy** [comment]
Glad to hear! I'll improve the docs soon with https://github.com/donmccurdy/glTF-Transform/commit/9907494179cea6e527d7961dfb0fcb8bacc2e1af.
