### ISSUE TITLE
'partition' command should allow partitions for animation data

### ISSUE THREAD

**Issue by donmccurdy** [donmccurdy/glTF-Transform#112]
Currently the command only partitions binary data for meshes; it should allow an animations option as well.

**Comment by VrTech** [comment]
Sorry to bring this up but, is there a partition method for one big mesh into multiple meshes (for loading purposes)?

**Comment by donmccurdy** [comment]
I'd think of that as two things: (1) a feature to subdivide a larger mesh, and (2) something like the existing `partition` method to put each mesh in a separate `.glb` or `.bin` file. This library doesn't currently implement (1), although it could be written on top of gltf-transform. An existing implementation more suitable for really large use cases would be [Cesium Ion](https://cesium.com/platform/cesium-ion/), which can subdivide a glTF model into any number of 3D tiles.
