### ISSUE TITLE
Impossible to select texture using slot in textureCompress

### ISSUE THREAD

**Issue by Makio64** [donmccurdy/glTF-Transform#1128]
**Describe the bug**
Impossible to select texture using slot in textureCompress

**To Reproduce**
here an example of the code i'm using : 
```
	// rename all the texture 
	let textures = document.getRoot().listTextures()
	let texturesInfos = []
	for (let texture of textures) {
		texture.setName('texture_' + k++)
	}
	
	await document.transform(textureCompress({ encoder: sharp, targetFormat: 'webp', resize: [64,64], nearLossless: true, slots: slot })) // change nothing
```

**Expected behavior**
The transform textureCompress is apply to all texture matching texture_

**Versions:**
 - Version: ^3.7.3
 - Environment: Nodejs

**Comment by Makio64** [comment]
it does work using compressTexture : 
```
let texture = textures.find((t) => t.getName() == p.name)
await compressTexture(texture, { encoder: sharp, targetFormat: params.format, resize: [params.width, params.height], nearLossless: true })
```

**Comment by donmccurdy** [comment]
@Makio64 what is the "slot" argument in this example?

**Comment by Makio64** [comment]
@donmccurdy oh sorry i wanted to simplify the example and removed the slot by mistake, it was : 

```
let slot = new RegExp(`^(texture_0).*$`)
```
 for example, i also tried variations but none worked

**Comment by donmccurdy** [comment]
Oh, I see the issue. The "slot" here refers to texture slots on the material, and would need to match the name from the glTF Specification, like...

- baseColorTexture
- emissiveTexture
- occlusionTexture
- ...

To match the user-provided name or URL of the texture, you'll want to use the `pattern` option instead. Docs for the options are below, though I guess more detail could be added on these:

https://gltf-transform.dev/modules/functions/interfaces/TextureCompressOptions#pattern

**Comment by Makio64** [comment]
thanks, didnt saw the pattern earlier, sorry for this issue !
