### ISSUE TITLE
Error message formating

### ISSUE THREAD

**Issue by Makio64** [donmccurdy/glTF-Transform#1146]
**Describe the bug**
The formating of the message error seems broken `weld: Requires 0 Γëñ tolerance Γëñ 0.1`

**To Reproduce**
give a wrong "weld"

**Expected behavior**
correct formating for `Γëñ` 

**Versions:**
 - Version: 3.7.5
 - Environment: Windows / Nodejs / visual studio code latest version terminal

**Comment by donmccurdy** [comment]
I guess this may depend on your terminal and/or font – the characters are ≤ symbols. 

If you'd like to make a PR it would be welcome!

https://github.com/donmccurdy/glTF-Transform/blob/fad253d2925056f62b828137d5148d6a11c72e39/packages/functions/src/weld.ts#L418-L424

**Comment by Makio64** [comment]
@donmccurdy Sure, replacing by `<=` instead of the special character would be ok for you ?

**Comment by donmccurdy** [comment]
That works for me, yes!

**Comment by donmccurdy** [comment]
Fixed by https://github.com/donmccurdy/glTF-Transform/pull/1155.
