### ISSUE TITLE
Dependency crashing Cli build: warp-ansi

### ISSUE THREAD

**Issue by josepduarte** [donmccurdy/glTF-Transform#1152]
**Describe the bug**

I have `@gltf-transform/cli` as a dependency on my project. Today, I started having this an error when building the app.

```
error TS2688: Cannot find type definition file for 'wrap-ansi'.
  The file is in the program because:
    Entry point for implicit type library 'wrap-ansi'
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Process completed with exit code 2.
```

Had to override the version of `wrap-ansi` to be `9.0.0` on the `package.json`.
```
    "resolutions": {
        "wrap-ansi": "9.0.0"
    },
```

**To Reproduce**
1. Add `@gltf-transform/cli` as a dependency and try to build your app.
2. The build crashes with the error shown above.

**Expected behavior**
- The build shouldn't fail.

**Versions:**
 - Version: 3.8.0
 - Environment: Node.js

**Comment by donmccurdy** [comment]
Mainly `@gltf-transform/cli` is a CLI tool, so I may need more context to know what using it "as a dependency" means. Are you importing something from it, and if so what? What is the build that is failing?

**Comment by donmccurdy** [comment]
Sorry, I'll need more information to investigate the issue further.
