### ISSUE TITLE
Draco compression issue

### ISSUE THREAD

**Issue by marwie** [donmccurdy/glTF-Transform#1215]
**Describe the bug**
Hello, it seems like with draco compression the UV coordinates (?) get lost for one particular model

**To Reproduce**
1. Open zip
2. See LiamA without compression
3. Inspect LiamA-draco - see that the texture is not correctly displayed on the character
4. run `gltf-transform draco LiamA.glb LiamA-draco.glb` to repro

**Expected behavior**
Character looks the same with draco compression aplied

**Versions:**
 - Version: 3.10.0
 - Environment: CLI

**Additional context**

[draco-issue.zip](https://github.com/donmccurdy/glTF-Transform/files/13744722/draco-issue.zip)

original and expected:
![image](https://github.com/donmccurdy/glTF-Transform/assets/5083203/eb3fb584-f0a5-4bf2-820d-9a8352144a9f)

after draco:
![image](https://github.com/donmccurdy/glTF-Transform/assets/5083203/54069749-5aac-43c3-9b67-98a146f53742)

![image](https://github.com/donmccurdy/glTF-Transform/assets/5083203/7841a5c5-8b74-4191-8820-5f27e0ab4058)

after meshopt:
![image](https://github.com/donmccurdy/glTF-Transform/assets/5083203/fa0836d8-7df6-457d-9dca-5ba5c3cbf03a)

**Comment by donmccurdy** [comment]
Pulling the UV islands up in Blender, note the long tail off to the right:

![UV islands in Blender extending far outside 0-1 range](https://github.com/donmccurdy/glTF-Transform/assets/1848368/a17b5e87-5ad0-43b9-b022-3ba4f3807962)

In short, some UVs are wild outliers, and any quantization implementation (in this case it's Draco's quantization, but my own cannot do better) will end up sacrificing quality with a larger quantization grid on the assumption that they're important.

Same cause:

- https://github.com/donmccurdy/glTF-Transform/issues/936
- https://github.com/donmccurdy/glTF-Transform/issues/976

***

I'm curious why this happens... is it one particular DCC tool? Perhaps it's common enough that it's worth scanning for, though. The process could be something like:

1. iterate over all UVs, record counts in three buckets:
    - number of UVs inside [0,1]
    - number of UVs inside [-2<sup>4</sup>,+2<sup>4</sup>]
    - number of UVs outside [-2<sup>4</sup>,+2<sup>4</sup>]
2. if the last bucket contains a trivial number of vertices compared to the first two, bring these UVs back inside a smaller range; this would require checking samplers, and finding an 'equivalent' 
3. log a warning so users know their input data is a bit troubled

Does this sound reasonable to you?

**Comment by marwie** [comment]
Thank you very much for looking into this - I've forwarded the question about the tool to our user and also how to fix the issue. I'll let you know when I get more information.
