### ISSUE TITLE
Resized textures may be below maximum dimension

### ISSUE THREAD

**Issue by donmccurdy** [donmccurdy/glTF-Transform#1225]
As reported in https://github.com/donmccurdy/glTF-Transform/issues/1213#issuecomment-1872522276, for certain input textures with large non-square dimensions, resizing down to fit a 512x512 box should (I believe) leave the largest dimension at exactly 512px. Instead, in some cases, I see the largest dimension at 511px.

I tried creating a simple snippet to reproduce the issue while filing a bug on Sharp, but the result worked as expected in the snippet, so I need to investigate further what might be going wrong.

[baseColor_3.png.zip](https://github.com/donmccurdy/glTF-Transform/files/13799123/baseColor_3.png.zip)

```typescript
import sharp from 'sharp';
import fs from 'node:fs';

const srcBuffer = fs.readFileSync('./baseColor_3.png');
const dstBuffer = await sharp(srcBuffer)
	.toFormat('png')
	.resize(512, 512, {
		withoutEnlargement: true,
		fit: 'inside',
		kernel: 'lanczos3',
	})
	.toBuffer();

fs.writeFileSync('./baseColor_3.out.png', dstBuffer);

```

***

Copied draft bug report to Sharp repo — 

***

### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

### Are you using the latest version of sharp?

- [ ] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

I'm not able to upgrade to sharp v0.33 quite yet due to some compatibility issues.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 283.25 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v20.10.0/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
```

### What are the steps to reproduce?

[baseColor_3.png.zip](https://github.com/lovell/sharp/files/13799052/baseColor_3.png.zip)

The image attached has dimensions 1900x1030. I'm attempting to resize it to 512x512 —

```js
instance.resize(512, 512, { fit: 'inside' });
```

### What is the expected behaviour?

I expected the resulting image to have a size of 512px on the larger dimension, with the smaller dimension somewhere around 277px. Instead the larger dimension in 511px.

**Comment by donmccurdy** [comment]
Model:

[input.zip](https://github.com/donmccurdy/glTF-Transform/files/13799138/input.zip)

**Comment by javagl** [comment]
Just a heads-up that this might either be resolved, or does not happen on all platforms. 

A quick local test with this (using the `input.zip` given above)
```
import fs from "fs";
import sharp from "sharp";

import { textureCompress } from "@gltf-transform/functions";
import { NodeIO } from "@gltf-transform/core";

async function run() {
  const inputFileName = "./input-glTF-Transform-issue-1225/input.glb";
  const outputFileName = "./input-glTF-Transform-issue-1225/output.glb";
  const io = new NodeIO();
  const inputGlb = fs.readFileSync(inputFileName);
  const document = await io.readBinary(inputGlb);
  const root = document.getRoot();

  const inputTextures = root.listTextures();
  console.log("inputTextures")
  for (const texture of inputTextures) {
    console.log(texture.getSize());
  }

  await document.transform(
    textureCompress({
      encoder: sharp,
      targetFormat: "png",
      resize: [512, 512],
    })
  );
  const outputTextures = root.listTextures();
  console.log("outputTextures")
  for (const texture of outputTextures) {
    console.log(texture.getSize());
  }

  const outputGlb = await io.writeBinary(document);
  fs.writeFileSync(outputFileName, outputGlb);
}

run();
```

prints
```
inputTextures
[ 980, 980 ]
[ 259, 259 ]
[ 1900, 1030 ]
[ 1500, 1500 ]
[ 4096, 4096 ]
outputTextures
[ 512, 512 ]
[ 259, 259 ]
[ 512, 278 ]
[ 512, 512 ]
[ 512, 512 ]
```
which seems to be correct. 

Some version info:
gltf-transform 3.10.1
sharp 0.32.6
Node (various, including) 18.19.0
OS Win 10

**Comment by donmccurdy** [comment]
Thanks @javagl! I'm no longer able to reproduce this either. Possibly fixed in other v4 changes, upgrades to Sharp, etc. Happy to reopen if this is still a problem on v4.
