### ISSUE TITLE
Add Merge Materials

### ISSUE THREAD

**Issue by zhaoyuanmeng** [donmccurdy/glTF-Transform#1244]
Optimize materials by finding and removing identical duplicates. If multiple materials have the same properties, only one will be kept.

**Comment by zhaoyuanmeng** [comment]
I have a very large bim5 data imported into glb data, because bim5 builds too many objects, causing the browser to load too slowly, want to achieve the same material batch operation to reduce draw call, thank you

**Comment by donmccurdy** [comment]
Hi! I think that the [dedup()](https://gltf-transform.dev/modules/functions/functions/dedup) and [join()](https://gltf-transform.dev/modules/functions/functions/join) functions will together do what you're after. 

Examples:

```
import { dedup, flatten, join } from '@gltf-transform/functions';

await document.transform(
  dedup(),
  flatten(),
  join()
);
```

```bash
gltf-transform optimize input.glb output.glb --no-compress
```

**Comment by zhaoyuanmeng** [comment]
Thank you. I'll have a try!
