### ISSUE TITLE
Broken model after using instance transform

### ISSUE THREAD

**Issue by harrycollin** [donmccurdy/glTF-Transform#1261]
Using the instance transform on the linked model results in misplaced objects. First discovered in Node and reproduced on https://gltf.report.

**To Reproduce**
1. Go to [Sketchfab Model](https://sketchfab.com/3d-models/santa-cruz-v10-downhill-mountain-bicycle-65e16e9785de4a019e35f599e47c9ee6)
2. Download the model as gLTF (glb)
3. Go to https://gltf.report
4. Open the downloaded model
5. Use the following code and apply to the model
```
import { prune, dedup, resample, instance } from '@gltf-transform/functions';

await document.transform(
	// Remove duplicate vertex or texture data, if any.
	dedup(),

	instance(),

	// Losslessly resample animation frames.
	resample(),

	// Remove unused nodes, textures, or other data.
	prune(),
);
```

6: The resulting model looks like this:
![image](https://github.com/donmccurdy/glTF-Transform/assets/10602138/b7bbdcba-20b7-4d7b-97a6-e99df77063de)

**Versions:**
 - Version: 3.5.1
 - Environment: Browser, Nodejs

**Additional context**
This doesn't seem to happen via the CLI for me.

**Comment by donmccurdy** [comment]
Confirmed, thanks @harrycollin! I'm seeing the same issue in the latest stable version v3.10. I was able to reproduce it on the CLI as well, though perhaps it depend on the order of commands and the optional flags there.

**Comment by donmccurdy** [comment]
I've been able to reproduce this error in https://gltf.report, but I can't reproduce it in a Node.js script or in the CLI, and it's fairly difficult to debug in the web app. if you're able to observe the error in Node, do you mind sharing how you went about that? Things that might be important:

- Node.js version
- ES Modules or CommonJS
- TypeScript or JavaScript
- any build tools

Thanks!

**Comment by donmccurdy** [comment]
Note to self — broken version of the file contains no accessors in the instance TRS transforms.

Correct:

```json
    {
      "mesh": 30,
      "extensions": {
        "EXT_mesh_gpu_instancing": {
          "attributes": {
            "TRANSLATION": 0,
            "ROTATION": 1,
            "SCALE": 2
          }
        }
      }
    },
```

Broken:

```json
        {
            "mesh": 30,
            "extensions": {
                "EXT_mesh_gpu_instancing": {
                    "attributes": {}
                }
            }
        },
```

**Comment by harrycollin** [comment]
Thanks for looking at this! I first noticed this in my Node environment. My bundled version of gLTF-Transform is higher than that used on https://gltf.report.

Info:
- gLTF-Transform 3.10.0
- Node 18.x
- ES Modules
- Typescript
- Bundled with esbuild
- Banner config for esbuild: 
```
  import { fileURLToPath } from 'url';
  import * as path from 'path';
  import { createRequire as topLevelCreateRequire } from 'module';
  const require = topLevelCreateRequire(import.meta.url);
  const __filename = fileURLToPath(import.meta.url);
  const __dirname = path.dirname(__filename);

```

**Comment by harrycollin** [comment]
> if you're able to observe the error in Node

I created a very simple node script but couldn't reproduce the problem. However in deployed bundled version (referenced above) it still occurs. I can't think of anything else right now that would cause this to happen. I'll keep digging in the meantime.

**Comment by donmccurdy** [comment]
I have a hunch this might be a case of [dual package hazard](https://nodejs.org/api/packages.html#dual-package-hazard). Certain build configurations compiling ESM to CJS (for example) can cause two copies of a dependency to be loaded. If the `@gltf-transform/functions` package imports code from one copy of `@gltf-transform/core` but is given an input document from another copy, lots of unpredictable bugs can happen, like `material instanceof Material` returning false.

If that's the case, setting output to ESM in either your ESBuild or TypeScript configuration would likely fix it ... see https://github.com/donmccurdy/glTF-Transform/discussions/857#discussioncomment-5343345 for a similar bug and resolution.

**Comment by Samsy** [comment]
Actually reporting the same issue 

On this model in particular :
https://github.com/Samsy/glbs/blob/main/sample.glb

Using the command line CLI to instance it results good : 
https://github.com/Samsy/glbs/blob/main/sample-instanced-good.glb


<img width="1950" alt="Screenshot 2024-02-08 at 15 30 28" src="https://github.com/donmccurdy/glTF-Transform/assets/3786958/2020ac72-4c9a-4a90-a0d7-f64cc706a8f4">

But using GLTF report script to instance dont show anything : 

https://github.com/Samsy/glbs/blob/main/sample-instanced-broken.glb

<img width="1965" alt="Screenshot 2024-02-08 at 15 30 50" src="https://github.com/donmccurdy/glTF-Transform/assets/3786958/0c63f3fa-a6d1-4e22-86cf-d4396ad9363d">


I also noticed, flatten does not seem to work on GLTF-report scripts !

**Comment by donmccurdy** [comment]
Would someone be able to share a Node.js script that reproduces this error, along with the specific bundlers and typescript configurations (if any) used to build and run that script?

I'm fairly confident this has to do with dual package hazard. Presumably I can fix the issue in glTF Report, but if you're running into the same issues in your own code, your build process may also need a configuration change. Targeting ESM (whatever that means in your build system) tends to resolve this problem.

**Comment by donmccurdy** [comment]
I've found the cause — partial fix in https://github.com/donmccurdy/glTF-Transform/pull/1269, but there are a few pieces of the solution I still need to figure out before merging.

**Comment by donmccurdy** [comment]
Fixed and published to 4.0.0-alpha.6. If you'd like to test that fix, you can use the `@next` tag, like `npm install @gltf-transform/cli@next`. glTF Report will be updated after the v4 stable release, which I'm hoping will happen by the end of March.

**Comment by Samsy** [comment]
Thank you very much, I'm going to check this !

**Comment by harrycollin** [comment]
Thank you @donmccurdy. Sorry I missed your request above for more info. I'm not sure I can avoid using clone(), so I'll test in v4 :D

**Comment by donmccurdy** [comment]
@Samsy yes – if you're using the scripting API in a node.js environment you'd probably want:

```
npm install --save @gltf-transform/core@next @gltf-transform/extensions@next @gltf-transform/functions@next
```
