### ISSUE TITLE
Dedup / instance / prune is breaking the model

### ISSUE THREAD

**Issue by Samsy** [donmccurdy/glTF-Transform#1283]
Hello hello ! 

Did discover an issue with prune.

Using this model :  https://github.com/Samsy/glbs/blob/main/testitest.glb

Original : 

<img width="930" alt="Screenshot 2024-02-22 at 11 14 55" src="https://github.com/donmccurdy/glTF-Transform/assets/3786958/44231e8a-4e42-4a6e-9c4a-728df595d510">

This transformation using 4.0.0-alpha.7 tested on both Nodejs package + CLI  / same version :  

    `import { Document, NodeIO, VertexLayout } from "@gltf-transform/core";

    import { KHRONOS_EXTENSIONS, EXTTextureWebP, EXTMeshGPUInstancing } from "@gltf-transform/extensions";

    import draco3d from "draco3dgltf";

    import {
        prune,
        dedup,
        resample,
        simplify,
        metalRough,
        draco,
        weld,
        // textureCompress,
        instance,
        dequantize,
        join,
        palette,
        clearNodeTransform,
        transformMesh,
    } from "@gltf-transform/functions";
    

    import fs from 'fs'

    async function process(url ){

       const io = new NodeIO()
        .registerExtensions(KHRONOS_EXTENSIONS)
        .registerExtensions([EXTMeshGPUInstancing])

        io.registerDependencies({
            "draco3d.decoder": await draco3d.createDecoderModule(), // Optional.
            "draco3d.encoder": await draco3d.createEncoderModule(), // Optional.
        });
    
        const originalDocument = await io.read(url);
    
        await originalDocument.transform(
         dedup(),

        instance(),

        // Losslessly resample animation frames.
        resample(),

        // Remove unused nodes, textures, or other data.
        prune(),
     
        );
    
        // const clone = originalDocument.clone()
    
        const glb = await io.writeBinary(originalDocument)
    
        fs.writeFileSync('yolo.glb', glb)

    }

    process('testitest.glb')
`

Result :  https://github.com/Samsy/glbs/blob/main/testitest-broken.glb

<img width="924" alt="Screenshot 2024-02-22 at 11 19 13" src="https://github.com/donmccurdy/glTF-Transform/assets/3786958/c01db935-09f6-417e-bfc3-b14f6a25453f">

I realised that removing the last prune transform does not break the model !

EDIT : 

I just tested the options of prunes : 

Seems like this option is not breaking the model : 

  prune({
            keepIndices: true
        })

**Comment by donmccurdy** [comment]
Thanks @Samsy! Will be fixed in https://github.com/donmccurdy/glTF-Transform/pull/1284.
