### ISSUE TITLE
Weld getting stuck on large OBJ files

### ISSUE THREAD

**Issue by dennis-modelsend** [donmccurdy/glTF-Transform#1292]
**Describe the bug**
Using weld on large OBJ files but getting stuck without any error or running out of memory.

**To Reproduce**
Preform weld on this file: https://we.tl/t-hkROOkQy3T

**Expected behavior**
Produces smaller OBJ file

**Versions:**
 - Version: 3.6.0
 - Environment: Browser

**Comment by donmccurdy** [comment]
I'd recommend trying the v4 alpha release. Example:

```js
npm install --save @gltf-transform/core@next @gltf-transform/extensions@next @gltf-transform/functions@next
```

That should perform better on large files, using default tolerance. It may or may not produce a smaller file, as that would depend on the input weld tolerance and the geometry. 

If that's still not working as expected, it may be best to share the GLB involved - my conversion from OBJ to GLB may be different than yours, as glTF Transform doesn't handle reading/writing OBJ files.

**Comment by dennis-modelsend** [comment]
Upgrading to v4 alpha release fixed the weld issue!
