### ISSUE TITLE
weld breaks loose edges

### ISSUE THREAD

**Issue by RenaudRohlinger** [donmccurdy/glTF-Transform#1331]
Hello! Is there a way to keep the original geometry when applying `optimize` to a glb object that has a Mesh with the Loose Edges options opted in?

Here my glb file for reference:
[cube_edges.glb.zip](https://github.com/donmccurdy/glTF-Transform/files/14730507/cube_edges.glb.zip)

Without using `optimize`:
<img width="1727" alt="image" src="https://github.com/donmccurdy/glTF-Transform/assets/15867665/2ead9a80-55a8-4ba4-9f6c-a7182fd49f97">

With `optimize`:
<img width="1727" alt="Screenshot 2024-03-23 at 15 36 56" src="https://github.com/donmccurdy/glTF-Transform/assets/15867665/8cb65a78-79ee-429f-af9b-a0f67c89f622">

**Comment by donmccurdy** [comment]
@RenaudRohlinger it looks like this has already been fixed on the v4 alpha release. If you'd like to give that a try:

```
npm i -g @gltf-transform/cli@next
```

**Comment by RenaudRohlinger** [comment]
Awesome, indeed v4 fixed my issue!
