### ISSUE TITLE
Cache cleanup

### ISSUE THREAD

**Issue by marwie** [donmccurdy/glTF-Transform#1368]
Hey,

I just noticed that the gltf-transform temp directory has grown to 1.2 GB by now and I wonder if files could automatically be removed or cleaned up after a run since - if I remember correctly - they're not used anymore later (e.g. as a cache)

![image](https://github.com/donmccurdy/glTF-Transform/assets/5083203/73132b2f-3f96-4185-8c4f-052763c4024c)

**Comment by donmccurdy** [comment]
Yikes. That was intended to happen...

https://github.com/donmccurdy/glTF-Transform/blob/46a74055d829c8e15b001c3ff55952e0dd1966d0/packages/cli/src/transforms/toktx.ts#L30

... but it looks like I may not be using that feature of `tmp` correctly — will take a look. I'll retag this as a bug.

**Comment by donmccurdy** [comment]
I also really want to avoid using CLI-in-CLI like this, per #675, but no progress there.
