### ISSUE TITLE
Draco compression may produce an UNSIGNED_SHORT index buffer with vertex count > 65535

### ISSUE THREAD

**Issue by allcreater** [donmccurdy/glTF-Transform#1370]
Hello, thank you so much for this library!

**Describe the bug**
Transforming some models with Draco compression may produce glTF with invalid accessors declaration

**To Reproduce**
1. Download an [attached test model](https://github.com/donmccurdy/glTF-Transform/files/15112589/dangerous_model.glb.zip)

2. Run `gltf-transform draco ../dangerous_model.glb optimize_test/dangerous_model.gltf`
3. Open the result glTF file in text mode and take a look on the index accessor with `"componentType": 5123` (should be 5125)
4. Despite some of the web-based renderers, like [Three.js](https://threejs.org/), [Babylon.js](https://www.babylonjs.com/) can load out model without any problems, some renderers like [Google Filament](https://google.github.io/filament/) yield an artifacts

**Expected behavior**
Index accessor pointed on vertex array with size more than 65535 should have a `componentType === 5125`

**Versions:**
 - Version: 3.10.1
 - Environment: both CLI and library

**Additional context**
It looks like the user will encounter the bug on a model that meets two requirements:
* one of its meshes must have a "borderline" number of vertices, near, but not exceeding, the 65535, so that it may be indexed with uint16 values.
* Draco compression algorithm must produce additional vertices so that the result number will exceed the border value.

**Comment by donmccurdy** [comment]
Yikes, thanks for reporting this! Likely related to:

- https://github.com/donmccurdy/glTF-Transform/issues/1343
- https://github.com/google/draco/issues/326

A design goal of glTF Transform is that the document being exported shouldn't change during export, but Draco compression seems to throw a few wrinkles into that plan. Will need to investigate this more.

**Comment by allcreater** [comment]
@donmccurdy thanks for your attention!

If I understand correctly, Draco may increase the number of vertices, it's pretty expected behavior, but the model just saves with incorrect componentType. As a workaround I just change the `componentType` from `5123` to `5125` and the patched model are correctly loaded by all renderers.

Of course, this trick is possible just with such "lazy" accessors whose data is populated after decompression.

**Comment by donmccurdy** [comment]
Thanks @allcreater! This should be fixed shortly with:

- https://github.com/donmccurdy/glTF-Transform/pull/1388
