### ISSUE TITLE
Quantization creates invalid skinning weights for CesiumMan.glb

### ISSUE THREAD

**Issue by donmccurdy** [donmccurdy/glTF-Transform#1404]
Quantizing CesiumMan with `gltf-transform quantize CesiumMan.glb CesiumMan+quant.glb` we see validation errors and visible 'spikes' in the geometry. Problem appears related to sorting and normalizing the skinning weights. Tested in v4-alpha.

[CesiumMan.glb.zip](https://github.com/donmccurdy/glTF-Transform/files/15214845/CesiumMan.glb.zip)

https://github.com/donmccurdy/glTF-Transform/blob/13fbccffa50f9d0ab0f9b68413817a9cd6f37191/packages/functions/src/sort-primitive-weights.ts#L74-L75

Related:

- https://discourse.threejs.org/t/gltf-meshopt-compression/66244/2

**Comment by marwie** [comment]
Just saw this issue appear in one of our meshes here as well - draco doesn't have this issue but in this case meshopt is much preferred due to blendshape compression 😊

**Comment by donmccurdy** [comment]
In progress:

- https://github.com/donmccurdy/glTF-Transform/pull/1439

**Comment by marwie** [comment]
Thanks a lot for the superfast fix!
