### ISSUE TITLE
implements meshoptimizer -sv

### ISSUE THREAD

**Issue by Makio64** [donmccurdy/glTF-Transform#1414]
The support of -sv will improve a lot the model simplification especially for model without textures.

Commit : 
https://github.com/zeux/meshoptimizer/pull/688

Issue: 
https://github.com/zeux/meshoptimizer/issues/652

**Comment by donmccurdy** [comment]
Agreed that this will be helpful! Merging the issue into:

- https://github.com/donmccurdy/glTF-Transform/issues/1153
- https://github.com/donmccurdy/glTF-Transform/issues/1335
