### ISSUE TITLE
Feature Request: Progress report for long-running CLI operations

### ISSUE THREAD

**Issue by hybridherbst** [donmccurdy/glTF-Transform#142]
Some CLI ops are pretty slow (e.g. ect1s conversion). They take "some seconds" for tiny files and "minutes" for larger ones.
It seems that the underlying slow operation is the actual texture conversion (toktx.exe) which in fact is able to report progress; would it be possible to mash those together to some kind of progress feedback for running CLI ops?

**Comment by donmccurdy** [comment]
The `--verbose` flag will print more detailed output — for ETC1S that includes texture-by-texture compression status. But a nicer progress bar, visible by default, would be a good improvement. 👍

**Comment by donmccurdy** [comment]
Tested https://www.npmjs.com/package/progress and https://www.npmjs.com/package/cli-progress, unfortunately neither seem to be a good fit here. They break if the program has any sort of "normal" log output, like warnings, and might require CLI code becoming more invasive in the rest of the project (it's currently a pretty thin wrapper on top). 

I'll keep this open as a nice-to-have but it may just need to be standard line-by-line log updates for now.

**Comment by hybridherbst** [comment]
Thank you, understood! In the meantime I'm parsing the existing `--verbose` output and turn that into a progress bar (I'm calling the CLI command from another software and wanted to show progress there).

**Comment by donmccurdy** [comment]
I think this could be done with [inquirer](https://www.npmjs.com/package/inquirer), as the CLI framework (Caporal.js) used here has an integration for it... haven't been able to get that working just yet, but I'm asking for help with it in https://github.com/mattallty/Caporal.js/issues/216.

**Comment by donmccurdy** [comment]
Unfortunately, I haven't been able to find a way to support this.
