### ISSUE TITLE
platform-io: glb with unknown chunk not supported

### ISSUE THREAD

**Issue by kzhsw** [donmccurdy/glTF-Transform#1454]
**Describe the bug**
Loading a glb with unknown chunk and without BIN chunk result in "Expected GLB BIN in second chunk." error. A quick search over code for this error leads me [here](https://github.com/donmccurdy/glTF-Transform/blob/v4.0.4/packages/core/src/io/platform-io.ts#L283).
From the [`4.4. Binary glTF Layout`](https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#binary-gltf-layout) section of gltf spec, it says in [`4.4.3.1. Overview`:](https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#chunks-overview)
> Client implementations **MUST** ignore chunks with unknown types to enable glTF extensions to reference additional chunks with new types following the first two chunks.

In `Table 1. Chunk types ` of spec, the `Occurrences` of BIN chunk is `0 or 1`, marking BIN chunk optional, so a model without a BIN chunk but with unknown chunk is valid from the spec.

**To Reproduce**
[test.zip](https://github.com/user-attachments/files/16154148/test.zip)
1. Go to <https://gltf.report/>
2. Load the glb in test.zip above
3. It says "Expected GLB BIN in second chunk."

**Expected behavior**
The glb should be successfully loaded and parsed.

**Versions:**
 - Version: since https://github.com/donmccurdy/glTF-Transform/commit/9d381f3794d668b6990196546788c3eec64e1f3b
 - Environment: All

**Additional context**
The Khronos [glTF 2.0 Sample Viewer](https://github.khronos.org/glTF-Sample-Viewer-Release/) can load the model without issue:
![screenshot of glTF-Sample-Viewer](https://github.com/donmccurdy/glTF-Transform/assets/120431159/cc291c32-f209-466f-8050-66672f28d372)
The [glTF-Validator](https://github.khronos.org/glTF-Validator/) result:
![glTF-Validator: The asset is valid.](https://github.com/donmccurdy/glTF-Transform/assets/120431159/d6279da7-866e-42cd-8ae9-ba6596fc3320)
Three.js [editor](https://threejs.org/editor/) can load without issue:
![screenshot of Three.js editor](https://github.com/donmccurdy/glTF-Transform/assets/120431159/98894157-326c-492c-b9bc-110de7af157f)
Babylon.js [sandbox](https://sandbox.babylonjs.com/) can load the model without issue:
![screenshot of babylon.js sandbox](https://github.com/donmccurdy/glTF-Transform/assets/120431159/aae2d09f-8e71-473f-a4b7-6ac75143764b)

**Comment by donmccurdy** [comment]
Hm, I see. I haven't seen GLBs using custom chunks without a GLB chunk before, but I agree this seems like a bug. Probably what's needed is just to replace the line that throws with:

```javascript
return { json, resources: {} };
```

A PR would be welcome, otherwise I'll pick this up as soon as I can, thanks!

**Comment by kzhsw** [comment]
> Probably what's needed is just to replace the line that throws with:
> 
> ```js
> return { json, resources: {} };
> ```

In this case, would the parser throw error for a truncated glb?

**Comment by donmccurdy** [comment]
This particular method won't need to know whether anything references the (missing) BIN chunk, so it should just return early if it sees a valid non-BIN chunk after the JSON chunk, I think. I'm not sure it needs to validate the unknown chunks it won't use, if that's what you mean?
