### ISSUE TITLE
Support Full Collection Hierarchy option (Blender >= 4.2.x)

### ISSUE THREAD

**Issue by RenaudRohlinger** [donmccurdy/glTF-Transform#1472]
**Describe the bug**
When using the CLI, for example  `gltf-trasform optimize cube.gltf cube.gltf`, the nodes collection generated by the option `Full Collection Hierarchy feature` gets deleted.

For example:

```json
// before optimize
{
	"asset":{
		"generator":"Khronos glTF Blender I/O v4.2.53",
		"version":"2.0"
	},
	"scene":0,
	"scenes":[
		{
			"name":"Scene",
			"nodes":[
				2
			]
		}
	],
	"nodes":[
		{
			"mesh":0,
			"name":"Cube"
		},
		{
			"children":[
				0
			],
			"name":"Collection"
		},
		{
			"children":[
				1
			],
			"name":"Scene Collection"
		}
	],
	...
}
```
![image](https://github.com/user-attachments/assets/3367c8b4-a576-43f4-b169-e5a1333bfedf)

After:
```json
{
  "asset": {
    "generator": "glTF-Transform v4.0.8",
    "version": "2.0"
  },
  "nodes": [
    {
      "name": "Cube",
      "mesh": 0
    }
  ],
  "scenes": [
    {
      "name": "Scene",
      "nodes": [
        0
      ]
    }
  ],
  "scene": 0,
  ...
}
```
![image](https://github.com/user-attachments/assets/909be36b-1d05-4eaa-8aa3-00dae2516036)

**To Reproduce**
1. Data > Scene Graph > Full Collection Hierarchy

**Expected behavior**
Keep the Collection Nodes in the Graph.

**Comment by donmccurdy** [comment]
The optimize command is the “everything but the kitchen sink” option on the CLI, using many different optimizations to try to bring file size down aggressively. If it's important to preserve more than just visual appearance (unused node hierarchy, unused UVs, etc.) then you'll want to customize its options, or apply more specific optimizations individually with other commands.

In this case, the [`flatten()`](https://gltf-transform.dev/modules/functions/functions/flatten) operation is the cause. That step can be disabled on the optimize command with the `--no-flatten` flag.
