### ISSUE TITLE
Add ability to remove EXT_GPU_INSTANCING usage

### ISSUE THREAD

**Issue by gkjohnson** [donmccurdy/glTF-Transform#1493]
**Is your feature request related to a problem? Please describe.**

Right now you can convert a model to use EXT_GPU_INSTANCING instances using the `instance` command but this is not supported by a lot of engines (Unreal, other tools). It would be nice if it were possible to _remove_ the extension usage in cases where you don't want it / can't use it.

**Describe the solution you'd like**

- Add a "--remove-instances" option to the "gltf-transform instance" command
- Or unpack instances and recompute them based on the settings of the `instance` command. Ie running a model that already has instances with the following command would remove all instances:

```
gltf-transform input.glb output.glb --min 10000000
```

**Describe alternatives you've considered**

Reading into the three.js editor and unpacking all instances manually.

**Additional context**

None

**Comment by donmccurdy** [comment]
I like the idea! This would involve:

- add an uninstance() (deinstance?) transform to the /functions package
- add a new command or flag to the CLI

I'm not immediately able to work on this, but PRs would be welcome.

**Comment by donmccurdy** [comment]
In progress:

- https://github.com/donmccurdy/glTF-Transform/pull/1525

**Comment by gkjohnson** [comment]
Awesome! Thanks Don
