### ISSUE TITLE
Refine GPU memory size computation

### ISSUE THREAD

**Issue by lexaknyazev** [donmccurdy/glTF-Transform#151]
Although image files could have 3 color channels, GPU formats like RGB8 are often emulated (by ANGLE or OpenGL driver) and expanded to RGBA8 on upload.

**Comment by donmccurdy** [comment]
/cc just @bghgary FYI, this tool reports GPU memory size with the `gltf-transform inspect input.glb` command.  Source code:

https://github.com/donmccurdy/glTF-Transform/blob/c0f5e0e9983dfa3bda71dd3687d762422b71ac17/packages/core/src/utils/image-utils.ts#L43-L63

I'm not sure this tool can report precise memory size for all hardware, does it seem reasonable to report a "best guess" assuming the texture data remains as provided to the API? Or if there are specific cases where a warning should be shown to the user I can include them. Note that this tool also doesn't attempt to handle KTX2 files that wouldn't be allowed by KHR_texture_basisu.

**Comment by lexaknyazev** [comment]
> does it seem reasonable to report a "best guess" assuming the texture data remains as provided to the API?

It's safe to say that the RGB8->RGBA8 expansion happens on almost all desktop GPUs and on a fair amount of mobile GPUs.

**Comment by donmccurdy** [comment]
I see, thanks! Yes that seems like a strong enough case for adjusting the estimate.
