### ISSUE TITLE
Normal ranges are modified after processing

### ISSUE THREAD

**Issue by gkjohnson** [donmccurdy/glTF-Transform#1510]
**Describe the bug**
Transforming (eg "gltf-transform flatten") a glb with [ - 1, 1 ] range float32 normals results in out-of-range values.

I'm seeing _massively_ out of range values on my internal test models - going from [ - 1, 1 ] to [ - 440, 4505] or larger - but I can't share those here. However using a simpler model exported from the three.js editor you can see that the normal data seems to be mangled in some way.

Here's a sample model which are these three objects inside a large sphere. I'm not exactly sure what's causing the issues so it's hard to repro:

[repro.glb.zip](https://github.com/user-attachments/files/17126997/repro.glb.zip)

<img width="381" alt="image" src="https://github.com/user-attachments/assets/685a9c51-7768-4b97-be0e-782a971667f5">

**To Reproduce**
1. Drag the "repro.glb" into the glb viewer and log the "normal" attribute ranges. See they are in the range [ - 1, 1 ] and [ 0, 1 ]
2. Run "gltf-transform flatten" on the repro.glb file
4. Log the normal ranges again
5. See the ranges are [ - 1, 1.015625 ], [ - 1, 1 ]

**Expected behavior**
The range of normals is not changed.

**Versions:**
 - Version: v4.0.8
 - Environment: node js (cli)

**Additional context**

**Comment by donmccurdy** [comment]
Hi @gkjohnson! The [flatten implementation](https://github.com/donmccurdy/glTF-Transform/blob/f3ed6a073eeaf5c2d8274ff9de9321900ea0235c/packages/functions/src/flatten.ts#L9) does not modify vertex data, so I think there must be something else going on here. Could you share the processed GLB, and how you're obtaining the normal ranges?

Note that the CLI will interleave vertex data by default – is it possible this is related?

To check the normals, I'm opening the model in https://gltf.report/ and running...

```javascript
import {flatten} from '@gltf-transform/functions';
await document.transform(flatten());

for (const mesh of document.getRoot().listMeshes()) {
	for (const prim of mesh.listPrimitives()) {
		const normal = prim.getAttribute('NORMAL');
		if (normal) {
			console.log({
				min: normal.getMin([]).join(', '),
				max: normal.getMax([]).join(', '),
			})
		}
	}
}
```

... though I did check processing through the CLI as well.

**Comment by gkjohnson** [comment]
> Note that the CLI will interleave vertex data by default 

_OH._ I didn't realize this - I figured the layout of the buffer attributes would remain untouched. Especially since something like "flatten" is such a simple operation. This explains the difference in values (I was accessing the arrays directly) and probably explains some of the other issues I was having, as well.

I see that there's a `--vertex-layout` flag to set this but I don't see a "don't change anything" option. That's what I'd expect to be the default, though I understand that's not necessarily possible in every operation.

**Comment by donmccurdy** [comment]
Unfortunately there's no "don't change anything" option for vertex layout – too complex to support all possible layouts for the in-memory representation of the model. `io.read()` loads each vertex attribute into a typed array, `io.write()` puts the attributes in one of the two available layouts.

**Comment by gkjohnson** [comment]
Sounds good - I'll just include the vertex-layout argument for now - thanks!
