### ISSUE TITLE
GLB with a material that has a texture name in capitals comes back as not having a texture.

### ISSUE THREAD

**Issue by woondossier** [donmccurdy/glTF-Transform#1515]
**Describe the bug**
Material with a name in capitals won't appear on the material it's assigned to.

**To Reproduce**
1. load a glb with a material that has a texture with the file name in all capitals except for the extension ("GRID.png")
2. get a list of all the materials in the root scene
3. list will list the material with texture as  not having a texture (null)

**Expected behavior**
Actually having the texture listed on the material that has it.

**Versions:**
 - Version: 4.0.10
 - Environment: nodejs

**Additional context**
We were testing our obj -> glb model processing pipeline for our BIM platform and I ran into this issue wondering why my texture wasn't showing up. I then changed both the name in the .mtl and file name to "grid.png"  and it worked.

GLB works in pretty much everything else that is threejs related, gltf.report, three editor, our own platform etc.
It also works fine in blender where it goes in as an obj -> and some extra post processing -> glb -> optimizing it with gltf-transform.  And in the last step the texture is suddenly "gone" when it's named "GRID" and referenced as GRID.png in the mtl.

Added the GLB in question if needed for testing.
[Orientation_Cube.zip](https://github.com/user-attachments/files/17217509/Orientation_Cube.zip)

**Comment by donmccurdy** [comment]
Hi @woondossier! I don't think I'm seeing the same result as you, here's a script:

```javascript
import { NodeIO } from '@gltf-transform/core';
const io = new NodeIO();
const document = await io.read('/Users/donmccurdy/Downloads/Orientation_Cube.glb');

const textures = document
	.getRoot()
	.listMaterials()
	.map((material) => [material.getName(), material.getBaseColorTexture()?.getName()]);

console.log(textures);
```

Output:

```jsonc
[
  [ 'BACK-F7-PURPLE', undefined ],
  [ 'CUBE', 'GRID' ],
  [ 'TOP-F6-BLUE', undefined ],
  [ 'BOTTOM_H8_PINK', undefined ],
  [ 'RIGHT-D3-GREEN', undefined ],
  [ 'LEFT-C5-TURQOISE', undefined ],
  [ 'FRONT-H1-RED', undefined ]
]
```

Anything I might be missing to reproduce this?

**Comment by woondossier** [comment]
Not really, that's exactly what I was doing, besides other things, but that's after this point so I'm not sure why it's not giving the same results.

I've actually changed it a few times to make sure that was the issue, and every time I changed it from lowercase to uppercase it would break.

I've just reconfirmed it using the same code snippet as you're using, I'll try it later today on another machine maybe it's OS/TS/Node related.

Lowercase:
[
  [    "BACK-F7-PURPLE",    null  ],
  [    "CUBE",    "grid"  ],
  [    "TOP-F6-BLUE",    null  ],
  [    "BOTTOM_H8_PINK",    null  ],
  [    "RIGHT-D3-GREEN",    null  ],
  [    "LEFT-C5-TURQOISE",    null  ],
  [    "FRONT-H1-RED",    null  ]
]

Uppercase:
[
  [    "BACK-F7-PURPLE",    null  ],
  [    "CUBE",    null  ],
  [    "TOP-F6-BLUE",    null  ],
  [    "BOTTOM_H8_PINK",    null  ],
  [    "RIGHT-D3-GREEN",    null  ],
  [    "LEFT-C5-TURQOISE",    null  ],
  [    "FRONT-H1-RED",    null  ]
]

**Comment by donmccurdy** [comment]
Just to confirm, you're loading this same .glb into gltf-transform right, and not a .gltf with external images? I could maybe imagine some issues on a case-sensitive operating system if the filepath didn't match the file on disk, but even then it ought to show an error instead of silently setting the texture to null. 

And moreover, there isn't any filepath/URL in the source .glb, just an image named "GRID" referring to an embedded binary texture:

![grid_image_2](https://github.com/user-attachments/assets/57f68998-adbe-4c85-833b-356b60d9c947)

Without that, just not sure how to reproduce this sorry!

**Comment by woondossier** [comment]
It's an automated pipeline so everything is 100% the same, it's the 'same' glb from blender the only difference is me renaming the file in the source .mtl and on disk from GRID.png to grid.png. 

Also this was on Linux, but the server that runs this pipeline is also running Linux and it's working fine so that's also not the issue, like I said it feels like an edge case and only my linux dev environment has experienced it so far and only with this model.

Thank you for looking into it though, for me it's acceptable as it doesn't break any critical parts of our system but only my pc so maybe when I have some downtime I'll try and see if I can figure out more myself.

**Comment by donmccurdy** [comment]
My best guess is that it's something to do with filesystem case sensitivity — but starting from the GLB as-is I can't find a way to reproduce this, as there are no external files there to load.

Going to close the issue for now, but would be happy to reopen if we can find a way to reproduce this.
