### ISSUE TITLE
gltf-transform optimize *glb

### ISSUE THREAD

**Issue by f1-outsourcing** [donmccurdy/glTF-Transform#1519]
Maybe command like this?

```
gltf-transform optimize *glb
```

Or is that risky? ;)

**Comment by donmccurdy** [comment]
Hi @f1-outsourcing! At this point, glob expansion and/or wildcard matching is not something I'm planning to add to the CLI. For that sort of use case I personally prefer the JavaScript API, it gives much more control over the optimization steps and input/output.

But if you don't want to install and run the JavaScript builds, you could also run something like this in a bash shell:

```bash
#!/bin/bash
FILES="path/to/*.glb"
for file in $FILES; do 
    echo "Optimizing $file..."
    gltf-transform optimize "${file%.glb}.glb" "${file%.glb}+opt.glb" 
done
```
