### ISSUE TITLE
Feature request: add explicit null annotations for return values

### ISSUE THREAD

**Issue by jeffomatic** [donmccurdy/glTF-Transform#152]
Thanks for the fantastic library!

I wanted to see how folks would feel about adding explicit `null` return value annotations to various methods across the library. For example, `Node#getMesh()` is annotated to return `Mesh`, but [the implementation](https://github.com/donmccurdy/glTF-Transform/blob/c0f5e0e9983dfa3bda71dd3687d762422b71ac17/packages/core/src/properties/node.ts#L190) has explicit cases where the function returns `null`. A safer type annotation would be `Mesh | null`. There are various getter methods across the library (in particular, those documented as "returns object x, if any") that would also benefit from this type of annotation.

Admittedly, this would be a breaking change, but it would be great for safety in the long-run, especially for projects with strict null checking enabled.

If there's interest, I might have some headroom to work on a PR.

**Comment by donmccurdy** [comment]
This would be required for #120 anyway, correct? I do want to work toward enabling strict null checks in this library eventually, so if you'd be able to work on a PR for this change, that would be wonderful. Maybe just changing 1-2 files initially to get a sense for how the usage (in unit tests, etc.) will change. I'm OK with optional chaining in unit tests, but would rather avoid it in the source code.

**Comment by donmccurdy** [comment]
Some progress in https://github.com/donmccurdy/glTF-Transform/commit/211c3aee5a46091e6562eabe1b0c2b8f31b269d6.

**Comment by donmccurdy** [comment]
With the next release (v0.9) the public API should provide correct null annotations.

Converting everything internally to have strict type checking was taking too long for this release, so that remains to be tracked in https://github.com/donmccurdy/glTF-Transform/issues/120.
