### ISSUE TITLE
KTX2 transformations should require basisu

### ISSUE THREAD

**Issue by emackey** [donmccurdy/glTF-Transform#153]
When converting textures to KTX2, no fallback PNG/JPG textures are included.  So, `KHR_texture_basisu` must be listed under `extensionsRequired` as well as `extensionsUsed`.

via https://github.com/KhronosGroup/glTF-Sample-Models/pull/285

**Comment by donmccurdy** [comment]
Fixed in https://github.com/donmccurdy/glTF-Transform/commit/b2455c31113eff4f473644e7fbef129b21987a66, thanks!
