### ISSUE TITLE
Non-unit quaternion yields strange results

### ISSUE THREAD

**Issue by rotu** [donmccurdy/glTF-Transform#1533]
**Describe the bug**
Calling `setRotation` with an incorrectly normalized quaternion results in some strange scaling and no warning.

**To Reproduce**
1. Go to gltf.report and load a model
2. Enter this script in the box:
```ts
document.getRoot().listScenes().forEach(
  s=>{
    s.listChildren().forEach(c=>{
    const newRoot = document.createNode();
    // note this has norm Math.hypot(0.5, 0, 0, 0.5) < 1
    newRoot.setRotation([0.5, 0, 0, 0.5]);
    newRoot.addChild(c);
    s.addChild(newRoot)
  })}
)
```
3. Click run a few times
4. Observe that the model is not only rotated but squished toward the axis of rotation. (screenshots below)

**Expected behavior**
One of the following should happen. I'm not sure which.
1. An error is reported and the `setRotation` call fails.
2. The `setRotation` call succeeds and scales the rotation to a unit quaternion before applying it. Optionally, a warning is reported.
3. The `setRotation` call succeeds and treats the rotation as currently does. A warning is reported.

**Additional context**
![image](https://github.com/user-attachments/assets/d65de576-6088-4464-bb01-e963e75ece52)
![image](https://github.com/user-attachments/assets/c16b47b9-5fc4-4609-8c85-38550d7ff4ff)

**Comment by donmccurdy** [comment]
@rotu The library does not validate inputs to getters/setters. I think that would be too much, both from a maintenance and performance perspective. In many cases this means the [glTF specification](https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html) is necessary as an additional reference; I'd also welcome PRs expanding on the current documentation with mathematical and/or spec requirements:

https://gltf-transform.dev/modules/core/classes/Node#setRotation

**Comment by rotu** [comment]
The gltf spec doesn't really say what to do here except that exporters should avoid emitting animations with degenerate quaternions. The `setMatrix` setter *does* coerce its input to TRS, which is much more expensive than renormalization.

Incidentally, `getMatrix/setMatrix` can be used to convert a non-unit quaternion into a unit quaternion and a scale:

```ts
let n = document.createNode();
n.setRotation([0.5,0,0,0.5])
n.setMatrix(n.getMatrix())
console.log(n.getTranslation()) // [0, 0, 0]
console.log(n.getRotation()) // [0.3826834323650897, 0, 0, 0.9238795325112867] 
console.log(n.getScale()) // [1, 0.7071067811865476, 0.7071067811865476] 
```

[gltf-viewer](https://gltf-viewer.donmccurdy.com/) reports validation errors (`ROTATION_NON_UNIT`) and maybe that's the better intervention.

![image](https://github.com/user-attachments/assets/75dd3366-8227-4981-82d5-19c759c4e13f)

**Comment by zeux** [comment]
FWIW glTF spec does say:

> rotation is a unit quaternion value, XYZW, in the local coordinate system, where W is the scalar

It is not using the normative language (e.g. `MUST`), but there are a lot of cases in the spec where it states the restriction but happens to omit the normative language (with occasional spec updates to make it more explicit).

**Comment by donmccurdy** [comment]
One other consideration is that occasionally, an extension may loosen a requirement of the core specification. KHR_mesh_quantization would be one example, allowing vertex attribute component types that would otherwise invalid. In this library I maintain a separation between the /core and /extensions modules, which would make validation in core class setters difficult in general.

One other method that should flag invalid quaternions would be...

```
gltf-transform validate scene.glb
```

... which uses https://github.com/KhronosGroup/glTF-Validator as in the viewer.

For now I think there's no action required here, but happy to reopen as needed.
