### ISSUE TITLE
WebIO support for AVIF

### ISSUE THREAD

**Issue by GitHubDragonFly** [donmccurdy/glTF-Transform#1565]
Not really sure of how the compression should be properly done and whether WebIO fully supports AVIF so this might not be a bug at all.

With my code I can see that JPEG and WEBP get compressed, PNG doesn't probably due to the `Sharp` requirement and AVIF is just an enigma to me.

This is pretty much what I am trying to do and AVIF size is rather large, equivalent of PNG file size and its header also shows `PNG` at the beginning even though the extension is changed:

```js
            const { compressTexture } = await import( "@gltf-transform/functions" );

            for (const texture of textures) {
              await compressTexture( texture, { targetFormat: tex_fmt } );

              if (tex_fmt === 'webp') {
                const { EXTTextureWebP } = await import( "@gltf-transform/extensions" );
                io.registerExtensions( [ EXTTextureWebP ] );
                doc.createExtension( EXTTextureWebP ).setRequired( true );
              } else if (tex_fmt === 'avif') {
                const { EXTTextureAVIF } = await import( "@gltf-transform/extensions" );
                io.registerExtensions( [ EXTTextureAVIF ] );
                doc.createExtension( EXTTextureAVIF ).setRequired( true );
              }
            }
```

This can be tested in my [GM Viewer](https://githubdragonfly.github.io/viewers/templates/GM%20Viewer.html) and its full code can be seen in my [repository](https://github.com/GitHubDragonFly/GitHubDragonFly.github.io/blob/main/viewers/templates/GM%20Viewer.html).

This viewer does allow exporting model MAPS only under whatever format is selected in the viewer.

**Comment by donmccurdy** [comment]
WebIO is only responsible for encoding and decoding glTF files to/from [Document](https://gltf-transform.dev/modules/core/classes/Document) instances, as long as `EXTTextureAVIF` is registered there's no limitation there, it doesn't need to decode the images.

[`compressTexture()`](https://gltf-transform.dev/modules/functions/functions/compressTexture), which needs to actually convert from the source format to AVIF, does have environment-specific limitations. When Sharp is available (in Node.js, and maybe Deno) it can apply AVIF compression. Without Sharp it falls back on [`HTMLCanvasElement#toBlob()`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob), and no browser supports AVIF compression in that API, to my knowledge.

If you want to do AVIF compression on the web, I think you'd need to first find a library that can do AVIF compression on individual images, and then write a custom function similar to `compressTexture()` ...

https://github.com/donmccurdy/glTF-Transform/blob/84f1629e08750b61ce6ab344168dd6033d4656ee/packages/functions/src/texture-compress.ts#L259

... using that library. Something like [`@jsquash/avif`](https://www.npmjs.com/package/@jsquash/avif) might be a good choice.

**Comment by GitHubDragonFly** [comment]
This is just an FYI but in case if you would find any mistake in my code then do reply so I could correct it.

I have included `@jsquash/avi` in my GM Viewer and the outputs of the Damaged Helmet example with AVIF are attached in case if you would like to test them.

Even though gltf.report can show the model it is having a hard time showing any info - not sure if this is related to its code or `@jsquash/avi` or the browser support or my code.

[Damaged Helmet avif.zip](https://github.com/user-attachments/files/17839159/Damaged.Helmet.avif.zip)

**Comment by GitHubDragonFly** [comment]
It looks like my mistake, missed to add `texture.setMimeType( 'image/avif' );` line of code.

**Comment by GitHubDragonFly** [comment]
I do have another question: under what circumstances would a texture return a size as null?

If I load a model with AVIF textures and then try to export it to KTX2 format that's when this error pops up since in my code I do check the texture size to see if it is a multiple of 4.

Would I need to add some extra code when creating a model with AVIF textures, maybe to register this format as it shows for ImageUtils.registerFormat function?

Here is a picture of what the texture looks like when logged, after the error is thrown, with some initial image array entries.

![Size Error](https://github.com/user-attachments/assets/835b96d5-9604-4ffe-9f72-139d79bde88b)

**Comment by GitHubDragonFly** [comment]
This worked for me but am not sure if it is correct way. It is kind of a hack since it is using PNG logic to read sizes from correct array locations (16 and 20):

```js
              if (texture.getMimeType() === 'image/avif') {
                const { ImageUtils } = await import( "@gltf-transform/core" );
                ImageUtils.registerFormat( 'image/avif', ImageUtils.impls[ 'image/png' ] );
              }
```

**Comment by donmccurdy** [comment]
For the purposes of an optimizing tool, I think you may want to register all available extensions with the I/O class...

```javascript
import { ALL_EXTENSIONS } from '@gltf-transform/extensions';

io.registerExtensions(ALL_EXTENSIONS);
```


That should guarantee that AVIF textures are legible to APIs like getSize(). Then on the Document, only the extensions that specific model will need.

**Comment by GitHubDragonFly** [comment]
Thank you, that will make things a bit simpler and shrink my code.

**Comment by GitHubDragonFly** [comment]
A quick question, what would be the simplest way of getting a correct extension from ALL_EXTENSIONS?

For example, if I would code it like this `doc.createExtension( ALL_EXTENSIONS[ 2 ] ).setRequired( true );` that would apply EXTTextureAVIF but this approach requires knowing the extensions list which should never change and always be registered in orderly manner by the browsers.

**Comment by donmccurdy** [comment]
Typically I'd use an additional import...

```javascript
import { ALL_EXTENSIONS, EXTTextureAVIF } from '@gltf-transform/extensions';

io.registerExtensions(ALL_EXTENSIONS);

...

const ext = document.createExtension(EXTTextureAVIF);
```

... but if you want to find it in the array that's fine too, no difference:

```javascript
const EXTTextureAVIF = ALL_EXTENSIONS.find((Extension) => Extension.EXTENSION_NAME === 'EXT_texture_avif');
```

**Comment by GitHubDragonFly** [comment]
It is not really too much code to add and users can see now what they can do. They should also bear in mind that names are not equivalent to extension itself.

If you would ever consider a switch to use a dictionary instead of an array then these could be called as simple as `ALL_EXTENSIONS.EXTTextureAVIF` or `ALL_EXTENSIONS.KHRTextureBasisu` or `KHRONOS_EXTENSIONS.KHRTextureBasisu`. This would only apply to `ALL_EXTENSIONS` and `KHRONOS_EXTENSIONS` while individual imports would still remain the same.

It's your library and your call but I am happy with things as they are.

**Comment by donmccurdy** [comment]
Mainly `ALL_EXTENSIONS` is meant as a shortcut for all built-in extensions, if you don't know which you need to support — Otherwise it'd be better to import each extension explicitly, and let the rest be tree-shaken out of the bundle. Or you might have other custom extensions not provided by `@gltf-transform/extensions`, that's not so uncommon either. 

So, I wouldn't get _too_ invested in the importance of that `ALL_EXTENSIONS` object, it's a somewhat arbitrary collection. 🙂
