### ISSUE TITLE
Resampling fails with `Maximum call stack size exceeded` 

### ISSUE THREAD

**Issue by 4nte** [donmccurdy/glTF-Transform#1572]
**Describe the bug**

I've tried to resample a glb file with `gltf-transform resample`, the file contains hundreds of animations (file size ~490mb)
Github doesn't allow uploading files larger than 25MB so I uploaded it here: [ct_anim.glb.zip](https://pub-cd6dca8fdfb444d8a969654cccc3ca48.r2.dev/animset_ct.zip)

I also tried to increasing node's maximum stack size incrementally up until I reached a hard limit where it would segmentation fault. This makes me suspicious of an infinite loop in the implementation

**To Reproduce**
1. run `gltf-transform resample animset_ct.glb animset_ct_optimized.glb --verbose`
2. see error: `error: Maximum call stack size exceeded`

**Expected behavior**
I expect the program to succeed 

**Versions:**
 - Version: `gltf-transform v4.1.0`
 - Environment: `node v22.11.0` on `ubuntu 22`

**Additional context**
I have a fairly decent machine (AMD® Ryzen 7 7700x 8-core processor × 16, 64gb ram) so I assume my computer is not the bottleneck.

**Comment by 4nte** [comment]
This is interesting: When I run sparse before resample, the error doesn't occur.

1. `gltf-transform sparse animset_ct.glb animset_ct_sparse.glb` 
2. `gltf-transform sparse animset_ct_sparse.glb animset_ct_sparse_resample.glb`

**Comment by donmccurdy** [comment]
Hm, that error shouldn't happen! Thanks for letting me know – let's keep this open and I'll take a look.

**Comment by donmccurdy** [comment]
Fix in progress: 

- https://github.com/donmccurdy/glTF-Transform/pull/1573
