### ISSUE TITLE
Is it possible to use glTF Transform to compress PLY point clouds?

### ISSUE THREAD

**Issue by kitaedesigns** [donmccurdy/glTF-Transform#1574]
I've tried using the CLI version of gltf-transform to try compressing and optimizing point clouds but can't seem to get a .ply file to be read correctly. 

"gltf-transform meshopt 6ivy.ply 6ivy-sm.ply
error: Unexpected token 'p', "ply
format"... is not valid JSON"

**Comment by donmccurdy** [comment]
Hi @kitaedesigns! glTF Transform can only read/write .gltf and .glb files, so the PLY point clouds would need to be converted to one of these formats first. Perhaps more importantly, the PLY format doesn't support Meshopt compression, so your output here will need to be .gltf or .glb in any case.

**Comment by kitaedesigns** [comment]
Ah I thought Meshopt did from this section on the Meshopt repo https://github.com/zeux/meshoptimizer?tab=readme-ov-file#point-cloud-compression but perhaps that's referring to gltf using vertices as points.

Or with Draco it seems that PLY files are supported. https://github.com/google/draco?tab=readme-ov-file#encoding-point-clouds

**Comment by donmccurdy** [comment]
Yes, other libraries that implement Meshopt or Draco compression might certainly also be able to parse PLY files as input, create an uncompressed binary stream of vertex data, and then run compression on that. But the compressed binary output would certainly not be valid PLY data, and it would need to be put into a container format that explicitly supports that type of compression. USD and glTF are the only two formats I know of supporting Draco, and I'm not aware of formats other than glTF supporting Meshopt at this time.

**Comment by kitaedesigns** [comment]
I see, I guess the main format for encoding point clouds with draco seems to be .ply to .drc, or use 3D tiles and Cesium's tools.

**Comment by donmccurdy** [comment]
Right, yes.

I think you're already aware but (for future readers) one thing I forgot to say earlier in the thread is that the glTF extension for Draco compression only supports triangle meshes, not point clouds. So for glTF, only meshopt compression (optionally with lossless supercompression like zstd on top of that) would be allowed. I'm not sure whether the USD/Draco integration supports point clouds or not.

So for point clouds with Draco, it's mainly just .drc, not the standard file formats like PLY, glTF, or USD. Or more specialized formats like OGC 3D Tiles.
