### ISSUE TITLE
Add 'material' command to CLI to add/modify textures and properties

### ISSUE THREAD

**Issue by donmccurdy** [donmccurdy/glTF-Transform#160]
Proposed usage:

```shell
gltf-transform material input.glb output.glb \
  --baseColorTexture base-color.png \
  --transmissionTexture transmission.png \
  --ior 1.5
```

This should automatically add the appropriate extensions.

**Comment by arpu** [comment]
would be nice to have a way to remove all textures from the glb

use case is to generate  a physic trimesh from  a users glb model

**Comment by donmccurdy** [comment]
This feature would probably allow you to do that if you specify `''` for each possible texture, but that's a lot of flag to include. An option you could script now would be:

```js
import { NodeIO } from '@gltf-transform/core';
import { ALL_EXTENSIONS } from '@gltf-transform/extensions';

const io = new NodeIO().registerExtensions(ALL_EXTENSIONS);

const doc = io.read('input.glb');

for (const texture of doc.getRoot().listTextures()) {
  texture.dispose();
}

io.write('output.glb', doc);
```

**Comment by arpu** [comment]
wau thx!

**Comment by dbuck** [comment]
Just wanted to tag on here that I also found that hint helpful, I was looking to use the package to work with some gltf files, but needed to have external textures at the final step, this worked to export out the embedded textures, but wasn't clear from the docs.

```
for (const tex of gltfDocument.getRoot().listTextures()) {
   tex.setURI(tex.getName() + '.jpg');
};
```

**Comment by donmccurdy** [comment]
@dbuck this tool always embeds textures in `.glb`, and never embeds textures in `.gltf`, so it is intentionally missing the "glTF Embedded" packing option that e.g. Blender provides. Does that answer the unclear issue you'd mentioned above, or did I misunderstand?

**Comment by dbuck** [comment]
No, I misread my results, realized right after that that it won't allow external references in the written glb

**Comment by donmccurdy** [comment]
Discontinuing #173 for now.

**Comment by GhostDog98** [comment]
Apologies if this is a bit of a necro, but is there any reason that this feature is not going to be implemented? I've got a use case where I need to modify ~12,000 glb files textures and I'd obviously prefer to not have to use a custom (somewhat untested) script...
