### ISSUE TITLE
error: [KHR_draco_mesh_compression] Draco primitives must share all, or no, accessors.

### ISSUE THREAD

**Issue by mattrossman** [donmccurdy/glTF-Transform#167]
Re: [twitter thread](https://twitter.com/donrmccurdy/status/1351411934189375488)

While `gtlf-pipeline` and `gltfpack` can compress my mesh without an issue, `gltf-transform` throws an error.

File: [avatar-raw.zip](https://github.com/donmccurdy/glTF-Transform/files/5839173/avatar-raw.zip)
Command: `gltf-transform draco avatar-raw.glb test-draco.glb`
Error: `error: [KHR_draco_mesh_compression] Draco primitives must share all, or no, accessors.`

**Comment by donmccurdy** [comment]
Thanks! I'll look into how to handle that case. If I remove the restriction check it seems to be working, but I think there was some other reason the check was necessary.

**Comment by donmccurdy** [comment]
Will be fixed when v0.9 is released, thanks for letting me know! 👍

**Comment by Usnul** [comment]
Ran into the same issue.

**Comment by donmccurdy** [comment]
v0.9 is now published.
