### ISSUE TITLE
Support the conversion of gltf png/jpg textures to webp texture

### ISSUE THREAD

**Issue by yoyomule** [donmccurdy/glTF-Transform#176]
Hope to be able to support the conversion of gltf png/jpg textures to webp texture format, and the ability to segment textures. Hope to have such a functional plan.

**Comment by donmccurdy** [comment]
Hi! I have been working on support for WebP. It isn't working yet, but you can track the progress in https://github.com/donmccurdy/glTF-Transform/pull/148.

I'm not sure what segmenting textures means — could you say more about this?

**Comment by yoyomule** [comment]
Thank you for your work.
It is possible that a certain texture map is very large, it may not be loaded normally when put into threejs, or the performance is not good. I wonder if there is any plan to divide a large texture map into several small texture maps.



> Hi! I have been working on support for WebP. It isn't working yet, but you can track the progress in #148.
> 
> I'm not sure what segmenting textures means — could you say more about this?

**Comment by donmccurdy** [comment]
I see, thanks! That sounds difficult to me, and requires splitting a mesh into multiple parts according to their UV layouts. It would be possible to implement something like that on top of the scripting API (see [primitive documentation](https://gltf-transform.donmccurdy.com/classes/primitive.html)) but it would be a fair bit of work to make it robust for all input meshes... I think that is more than I am able to work on myself, but would be interested to hear if others are doing so.

Generally I would advise reducing texture sizes — mobile devices have less GPU memory than you might think — or used compressed textures like KTX / Basis Universal. This project does support compressing textures now, and resizing textures is also in progress.
