### ISSUE TITLE
First argument to DataView constructor must be an ArrayBuffer when using inspect()

### ISSUE THREAD

**Issue by duncan-vrify** [donmccurdy/glTF-Transform#178]
I'm trying to implement `gltf-transform` into my Vue project in order to make use of the `inspect()` method for my gltf/glb files. 

This is what I'm trying to do 
```
import { WebIO } from '@gltf-transform/core'
import { inspect } from '@gltf-transform/lib'

// data.gltf === a URL at which the resource can be achieved (I can link it if necessary)
const gltfFile = data.gltf
const io = new WebIO()
const doc = await io.read(gltfFile)
inspect(doc)
```

But I seem to be getting this error

```
caught TypeError: First argument to DataView constructor must be an ArrayBuffer
    at new DataView (<anonymous>)
    at Function.m (core.modern.js:1)
    at Function.getSize (core.modern.js:1)
    at lib.modern.js:1
    at Array.map (<anonymous>)
    at q (lib.modern.js:1)
    at k (lib.modern.js:1)
    at _callee$ (_modelId.vue:180)
    at tryCatch (runtime.js:63)
    at Generator.invoke [as _invoke] (runtime.js:293)
    at Generator.next (runtime.js:118)
    at asyncGeneratorStep (asyncToGenerator.js:3)
    at _next (asyncToGenerator.js:25)
```

Any ideas as to what I'm doing wrong?

(Apologies if this isn't the right place to post this, let me know if it would be better suited for somewhere else)

**Comment by donmccurdy** [comment]
> `const gltfFile = data.gltf`

So `gltfFile` is a string, correct? Does it have a `.gltf` or `.glb` extension? I don't think I will need access to the actual file here. 

It might be worth looking at your browser's network tab in the developer tools, to see what URL is being requested and whether it's finding a file (HTTP 200) or not (HTTP 404). Some web frameworks have development servers that handle static files differently.

**Comment by duncan-vrify** [comment]
> 
> 
> > `const gltfFile = data.gltf`
> 
> So `gltfFile` is a string, correct? Does it have a `.gltf` or `.glb` extension? I don't think I will need access to the actual file here.
> 
> It might be worth looking at your browser's network tab in the developer tools, to see what URL is being requested and whether it's finding a file (HTTP 200) or not (HTTP 404). Some web frameworks have development servers that handle static files differently, e.g. Parcel usually needs the `parcel-plugin-static-files-copy` plugin to host any sort of binary file.

Yes, it's a string with a `.glb` extension

And I checked the response and it was returning a 200. I'll have a chat with our backend developers tomorrow to see if they have any insight towards that. Thank you.

**Comment by donmccurdy** [comment]
Oops, I think I'd missed that the error was being thrown from the `inspect(doc)` call and not while loading the file. Or at least I think so, with `lib.modern.js` in the stack trace.  If you can share the file somewhere, that may help after all.

**Comment by duncan-vrify** [comment]
> 
> 
> Oops, I think I'd missed that the error was being thrown from the `inspect(doc)` call and not while loading the file. Or at least I think so, with `lib.modern.js` in the stack trace. If you can share the file somewhere, that may help after all.

https://dev-cdn.vrify.com/3d-assets/aff0aa09-9fad-45cc-b620-b8800d8e3ffb.glb is the file url

**Comment by donmccurdy** [comment]
Ok, thanks — I can reproduce the issue here too, and will investigate. 👍

**Comment by donmccurdy** [comment]
I'm not sure why the tool is reading this file without clearer warnings, but it seems to have two entries for images that are not valid:

```
"images": [
  {
    "mimeType": "image/png"
  },
  {
    "mimeType": "image/png"
  }
],
```

^Those should have either a `bufferView` or a `uri` property to be valid, without them there is no image data. It may be a bug in COLLADA2GLTF, which seems to be the converter that produced this model.

I'll make some adjustments to ensure that glTF-Transform provides a more useful warning about this issue. In the meantime https://github.khronos.org/glTF-Validator/ may be helpful for double-checking your model's validity.

**Comment by duncan-vrify** [comment]
Ahhh, that's helpful. I will investigate that further, thank you!
