### ISSUE TITLE
INSPECT formatting

### ISSUE THREAD

**Issue by echadwick-wayfair** [donmccurdy/glTF-Transform#186]
The "info" section seems to be malformed for both MD and CSV?

gltf-transform/cli@0.9.2

gltf-transform inspect mixer.glb --format md >mixer_inspect.txt

```
 INFO
 ────────────────────────────────────────────
[90m┌────────────────────[39m[90m┬─────────────────────────────────┐[39m
[90m│[39m generator          [90m│[39m Khronos glTF Blender I/O v1.0.5 [90m│[39m
[90m├────────────────────[39m[90m┼─────────────────────────────────┤[39m
[90m│[39m version            [90m│[39m 2.0                             [90m│[39m
[90m├────────────────────[39m[90m┼─────────────────────────────────┤[39m
[90m│[39m extensionsUsed     [90m│[39m none                            [90m│[39m
[90m├────────────────────[39m[90m┼─────────────────────────────────┤[39m
[90m│[39m extensionsRequired [90m│[39m none                            [90m│[39m
[90m└────────────────────[39m[90m┴─────────────────────────────────┘[39m


 SCENES
 ────────────────────────────────────────────
| # | name  | rootName | bboxMin                     | bboxMax                  |
| - | ----- | -------- | --------------------------- | ------------------------ |
| 0 | Scene | Mixer02  | -0.10581, 0.00003, -0.16576 | 0.10581, 0.29952, 0.1537 |

...
```

gltf-transform inspect mixer.glb --format csv >mixer_inspect.csv

```
INFO
 ────────────────────────────────────────────
[90m┌────────────────────[39m[90m┬─────────────────────────────────┐[39m
[90m│[39m generator          [90m│[39m Khronos glTF Blender I/O v1.0.5 [90m│[39m
[90m├────────────────────[39m[90m┼─────────────────────────────────┤[39m
[90m│[39m version            [90m│[39m 2.0                             [90m│[39m
[90m├────────────────────[39m[90m┼─────────────────────────────────┤[39m
[90m│[39m extensionsUsed     [90m│[39m none                            [90m│[39m
[90m├────────────────────[39m[90m┼─────────────────────────────────┤[39m
[90m│[39m extensionsRequired [90m│[39m none                            [90m│[39m
[90m└────────────────────[39m[90m┴─────────────────────────────────┘[39m


 SCENES
 ────────────────────────────────────────────
#,name,rootName,bboxMin,bboxMax
0,Scene,Mixer02,"-0.10581, 0.00003, -0.16576","0.10581, 0.29952, 0.1537"

...
```

**Comment by donmccurdy** [comment]
Should be fixed on next release, thanks!

When using the default format (`--format pretty`) are the table layouts broken like that in your terminal, with `�[90m┌` characters`, or is that just when outputting to a file and viewing it here? In iTerm on macOS it would look like this:

![Screen Shot 2021-02-15 at 2 35 23 PM](https://user-images.githubusercontent.com/1848368/107998942-0b972180-6f9b-11eb-90ff-c01ddf353212.png)

Also note that putting the entire `--format csv` output into one CSV will not give a valid CSV, since CSV can only define a single "table" with one set of headers. Since the output needs a table for each resource type, each section is _individually_ a valid CSV, but would need to be copy/pasted by itself.

**Comment by echadwick-wayfair** [comment]
Thanks. Not broken in the terminal here, only in the output CSV or TXT(MD).
![image](https://user-images.githubusercontent.com/40177036/108080863-51f18c80-703e-11eb-8ec5-ff976c483cfc.png)

**Comment by echadwick-wayfair** [comment]
MD format, posted to the terminal:
![image](https://user-images.githubusercontent.com/40177036/108081037-82392b00-703e-11eb-84f6-d5bb1b8af4ee.png)

CSV format posted to the terminal:
![image](https://user-images.githubusercontent.com/40177036/108081087-91b87400-703e-11eb-87f8-ee3d09551789.png)

**Comment by echadwick-wayfair** [comment]
As far as CSV format goes, it would be helpful to have the CSV setup for ready ingestion via Sheets/Excel. If possible.

**Comment by donmccurdy** [comment]
The updated CSV and MD output on the next release will be:

**CSV**

![Screen Shot 2021-02-16 at 9 33 22 AM](https://user-images.githubusercontent.com/1848368/108099996-2d93b100-703a-11eb-9117-4916c516182e.png)

**MD** 

![Screen Shot 2021-02-16 at 9 33 54 AM](https://user-images.githubusercontent.com/1848368/108100005-2ff60b00-703a-11eb-9c60-ce7c57696602.png)

It's not possible to output all of this as a single valid CSV file — CSVs do not have separate worksheets like Excel files would. The output can be copy/pasted easily into Sheets/Excel easily but I don't think I can do better than that.
