### ISSUE TITLE
Estimated GPU size of ETC1S textures is too low

### ISSUE THREAD

**Issue by donmccurdy** [donmccurdy/glTF-Transform#187]
From Mark:

> The GPU size for ETC1S can be easily calculated from the pixel size and the knowledge that the block dimension are 4x4 and the blocksize is 8 bytes (64 bits). You will need to check if there are alpha slices. If so, the blocksize is 8+8 bytes.

Current incorrect code is here:

https://github.com/donmccurdy/glTF-Transform/blob/14140ed/packages/core/src/utils/image-utils.ts#L47

**Comment by MarkCallow** [comment]
It's waaaay too low. It is attempting to calculate the ETC1S/BasisLZ size not the ETC1S size and omits the global codebooks in supercompressionGlobalData which is the bulk of the ETC1S/BasisLZ data.
