### ISSUE TITLE
Question: How to split meshes to separate gltf?

### ISSUE THREAD

**Issue by dbuck** [donmccurdy/glTF-Transform#188]
For example, what is the best route to take to extract a single mesh from `sourceDoc: Document` to `targetDoc: Document` with any referenced materials/textures/buffers?

On glance, it looks like there are a couple routes available to take given the current api:

Brute force route: sourceDoc.clone(), listMeshes/nodes, dispose items we don't want to keep in the new doc, prune the new file?

Create a new document, walk the attributes, targets, and indices for the target mesh, creating new resources in the target document, use a custom resolve for property.copy(from, resolve), which points to the new graph?

**Comment by donmccurdy** [comment]
I think the steps should be something like:

1. `doc.clone()`
2. Create a new scene, add a node, and attach the mesh you want to that node.
3. Remove the older scene with `scene.dispose()`
4. Clean up everything else with the [prune function](https://github.com/donmccurdy/glTF-Transform/blob/main/packages/lib/src/prune.ts), e.g. `await doc.transform(prune());`

This might require more steps if you need to preserve an animation on that mesh.

**Comment by dbuck** [comment]
That's working pretty well, if a bit slow, I'll probably try and dispose newly separated meshes from the source doc at some point, so that the prune has less items to work through as the process goes on.

One small trap: I did at first try and use `scene.createNode(mesh.getName()).addChild(mesh)`, which resulted in a children:[null] in the end output, rather than the node.setMesh(mesh) which was the correct route.
