### ISSUE TITLE
Unexpected token g in JSON at position 0 when passing in URI with query parameter

### ISSUE THREAD

**Issue by duncan-vrify** [donmccurdy/glTF-Transform#193]
Hi,

I'm trying to use the `WebIO().read(()` method in order to load my URI but my URI has a query parameter attached to it in the form of `https://example-url.com/test/123?expiry=123` and when passed into the `.read()` method, it, it gives me this error

```
SyntaxError: Unexpected token g in JSON at position 0
```

The `.read()` works completely fine and as expected without the query parameter.

Let me know if I need to provide any additional info!

Thanks!

**Comment by donmccurdy** [comment]
Thanks for letting me know! It looks like there's a bug in the code in `WebIO.ts` that detects whether it's reading a `.glb` or `.gltf` file. A quick workaround in the meantime would be:

```js
const glb = fetch('https://example-url.com/test/123?expiry=123').then((response) => response.arrayBuffer());
const document = new WebIO().readBinary(glb);
```

I will try to fix WebIO so that a query parameter doesn't interfere with format detection. But if the URL really doesn't have an extension anywhere (like `test/123?expiry=123`) you may need to download it first and then parse it like the example above.

**Comment by duncan-vrify** [comment]
Ah great I'll give that a shot at implementing. And yeah it does have a `.glb` extension so that should work great. Thank you!

**Comment by duncan-vrify** [comment]
I tried this

```
        const io = new WebIO()
        fileUrl = modelData.value.gltf
        const glb = await fetch(fileUrl).then(async response => await response.arrayBuffer())
        const doc = await io.readBinary(glb)
```

which gives me this error 

```
Error: GLB images must be stored in a buffer view.
    at ft.binaryToJSON (core.modern.js:1)
    at ft.readBinary (core.modern.js:1)
    at _callee4$ (_modelId.vue:84)
    at tryCatch (runtime.js:63)
    at Generator.invoke [as _invoke] (runtime.js:293)
    at Generator.next (runtime.js:118)
    at asyncGeneratorStep (asyncToGenerator.js:3)
    at _next (asyncToGenerator.js:25)
    ```
But it seems as though it converted to the ArrayBuffer fine. I logged the array buffer between the `fetch` and `readBinary` and it came out as

```
ArrayBuffer(80625588) {}
[[Int8Array]]: Int8Array(80625588) [103, 108, 84, 70, 2, 0, 0, 0, -76, 63, -50, 4, 80, 127, 0, 0, 74, 83, 79, 78, 123, 34, 97, 115, 115, 101, 116, 34, 58, 123, 34, 103, 101, 110, 101, 114, 97, 116, 111, 114, 34, 58, 34, 67, 79, 76, 76, 65, 68, 65, 50, 71, 76, 84, 70, 34, 44, 34, 118, 101, 114, 115, 105, 111, 110, 34, 58, 34, 50, 46, 48, 34, 125, 44, 34, 115, 99, 101, 110, 101, 115, 34, 58, 91, 123, 34, 110, 111, 100, 101, 115, 34, 58, 91, 48, 93, 125, 93, 44, 34, …]
[[Int16Array]]: Int16Array(40312794) [27751, 18004, 2, 0, 16308, 1230, 32592, 0, 21322, 20047, 8827, 29537, 25971, 8820, 31546, 26402, 28261, 29285, 29793, 29295, 14882, 17186, 19535, 16716, 16708, 18226, 21580, 8774, 8748, 25974, 29554, 28521, 8814, 8762, 11826, 8752, 11389, 29474, 25955, 25966, 8819, 23354, 8827, 28526, 25956, 8819, 23354, 23856, 23933, 8748, 25459, 28261, 8805, 12346, 8748, 28526, 25956, 8819, 23354, 8827, 26723, 27753, 29284, 28261, 14882, 12635, 11357, 28194, 28001, 8805, 8762, 24409, 20565, 32034, 31532, 25378, 26984, 25708, 25970, 8814, 23354, 13363, 12588, 11318, 13617, 12588, 11316, 13105, 12588, 11314, 12593, 12588, 11312, 11321, 11320, 11318, 23858, 8748, 24942, 25965, …]
[[Int32Array]]: Int32Array(20156397) [1179937895, 2, 80625588, 32592, 1313821514, 1935745659, 578053491, 1730313018, 1919250021, 1919906913, 1126316578, 1095519311, 1194475844, 575034444, 1702240812, 1869181810, 574235246, 573582898, 1931619453, 1701733731, 1530536563, 1869488763, 577987940, 1563450170, 573332861, 1852138355, 809116261, 1869488684, 577987940, 578509626, 1818847331, 1852142180, 828062242, 1847733341, 577072481, 1599676986, 2099400789, 1663204140, 1684826472, 577660274, 875780922, 741749036, 824980785, 858860596, 741486892, 824979761, 741944368, 741747768, 573332786, 1701667182, 1596078626, 1718186614, 1869766521, 1869509743, 2099406180, 1663204140, 1684826472, 577660274, 741694266, 1563634740, 1634542124, 2020176500, 828062242, 808202286, 808202286, 808202286, 808202286, 824979502, 808202286, 808202286, 808202286, 808202286, 824979502, 808202286, 757870638, 858667315, 959722805, 926298681, 825767733, 757872690, 841888308, 959655985, 926037561, 892680246, 825044021, 842477110, 808466480, 926497075, 926036024, 774974517, 573332784, 1701667182, 941767202, 1127823174, 759513648, 809780020, 1110651949, 1178676534, 1143816514, 1127691058, …]
[[Uint8Array]]: Uint8Array(80625588) [103, 108, 84, 70, 2, 0, 0, 0, 180, 63, 206, 4, 80, 127, 0, 0, 74, 83, 79, 78, 123, 34, 97, 115, 115, 101, 116, 34, 58, 123, 34, 103, 101, 110, 101, 114, 97, 116, 111, 114, 34, 58, 34, 67, 79, 76, 76, 65, 68, 65, 50, 71, 76, 84, 70, 34, 44, 34, 118, 101, 114, 115, 105, 111, 110, 34, 58, 34, 50, 46, 48, 34, 125, 44, 34, 115, 99, 101, 110, 101, 115, 34, 58, 91, 123, 34, 110, 111, 100, 101, 115, 34, 58, 91, 48, 93, 125, 93, 44, 34, …]
byteLength: 80625588
__proto__: ArrayBuffer
[[IsDetached]]: false
```

**Comment by donmccurdy** [comment]
Does the GLB have external textures? / would you be able to share the GLB?

**Comment by duncan-vrify** [comment]
Ahhh, yeah the GLB does have external textures. 

I remember you helped me through a similar issue last time when I was trying to utilize inspect. I had to manually fetch the image from my CDN and convert that to an arrayBuffer and call `setImage` for the glb's with external textures

This is the glb

https://cdn.vrify.com/3d-assets/aff0aa09-9fad-45cc-b620-b8800d8e3ffb.glb

**Comment by duncan-vrify** [comment]
I think it might be breaking using version `0.9.2` of each of the gltf-transform packages. I tried reverting to `0.9.1` and the files seem to be loaded fine

**Comment by donmccurdy** [comment]
Probably https://github.com/donmccurdy/glTF-Transform/commit/b167623ecb62425073171bc71f87af4a15bb9abb ... it didn't support external image URLs in GLBs in v0.9.1, it just ignored them silently, and v0.9.2 began considering that an error. The glTF spec does allow external URLs in GLBs, but it's unusual, and glTF-Transform doesn't currently offer a way to read or write files that way.

Could I ask how you want to use glTF-Transform with these files? Support for reading them makes enough sense to me, but writing them would be a less ergonomic breaking change — `io.writeBinary(doc)` could not return an `ArrayBuffer` anymore.

**Comment by duncan-vrify** [comment]
Sorry yeah I deleted my comment cause I thought I was wrong but I think it is the case with the versions.

Let me give you an example snippet of what I was doing

```
        fileUrl = modelData.value.gltf
        const doc = await io.read(fileUrl)
        const textures = doc.getRoot().listTextures()
        console.log('File loaded')

        const imageBlobs = {}

        let requests = textures.map((texture, index) => {
          return new Promise(async resolve => {
            console.log(texture.getURI()) // 55ff10ee-0c46-4369-934f-1ad82444c017.png and 97fb61ca-a5b3-4d09-9ec7-4dfec931c3a9.png
            imageBlobs[index] = await fetch(CDN_URL_PATH + texture.getURI()).then(response => response.arrayBuffer())
            textures[index].setImage(imageBlobs[index])
            resolve()
          })
        })
```

So I noticed that the `texture.getURI()` had the file url and type attached to it but the image data was missing so I combined that along with my CDN url to create a proper URI which I could then fetch and convert to an array buffer and use that to setImage which allowed `inspect` to successfully run

**Comment by donmccurdy** [comment]
Hopefully have a fix in #194. Could you check whether `npm install @gltf-transform/core@alpha` works for you?

**Comment by duncan-vrify** [comment]
(I tried `v0.9.1` and `v0.9.2` of `@gltf-transform/extensions` or @gltf-transform/lib` as well, wasn't sure which versions I was supposed to leave those at)

However, with the `@gltf-transform/core@alpha`, the model listed above (non-draco compressed) gave me this error

```
instrument.js:109 Error: Cannot resolve external images with binaryToJSON().
    at lt.binaryToJSON (core.modern.js:1)
    at lt.readBinary (core.modern.js:1)
    at _callee4$ (_modelId.vue:93)
    at tryCatch (runtime.js:63)
    at Generator.invoke [as _invoke] (runtime.js:293)
    at Generator.next (runtime.js:118)
    at asyncGeneratorStep (asyncToGenerator.js:3)
    at _next (asyncToGenerator.js:25)
```

I tested with a draco-compressed model as well and it returned this error

```
TypeError: s.register is not a function
    at lt.registerExtensions (core.modern.js:1)
    at _callee4$ (_modelId.vue:72)
    at tryCatch (runtime.js:63)
    at Generator.invoke [as _invoke] (runtime.js:293)
    at Generator.next (runtime.js:118)
    at asyncGeneratorStep (asyncToGenerator.js:3)
    at _next (asyncToGenerator.js:25)
    at asyncToGenerator.js:32
    at new Promise (<anonymous>)
    at VueComponent.<anonymous> (asyncToGenerator.js:21)
    at VueComponent.inspectGltf (_modelId.vue:61)
    at invokeWithErrorHandling (vue.runtime.esm.js:1854)
    at HTMLDivElement.invoker (vue.runtime.esm.js:2179)
    at HTMLDivElement.original._wrapper (vue.runtime.esm.js:6917)
    at HTMLDivElement.sentryWrapped (helpers.js:72)
```

Let me know if I need to add any additional information!

**Comment by donmccurdy** [comment]
Everything will need to be updated in sync, so if you're using extensions try:

```
npm install @gltf-transform/core@alpha @gltf-transform/extensions@alpha @gltf-transform/lib@alpha
```

> instrument.js:109 Error: Cannot resolve external images with binaryToJSON().

`binaryToJSON(buffer)` really won't be able to resolve external images, because it doesn't know the original base path of the file, and that determines where the images are found. But going back to this sample, I think it should work now:

```js
const doc = await io.read('https://dev-cdn.vrify.com/3d-assets/e49fb37e-ab48-480c-bbad-7eef3cb21e29.glb?foo');
```

**Comment by duncan-vrify** [comment]
Ah, yeah that makes sense.

Just updated them to be all the `@alpha` and it worked great for both the draco and non-compressed draco. I was still trying the `fetch` and `readBinary` method so that might have been why it wasn't working.

Once again, I really appreciate everything. Thanks again for helping me through all this!

**Comment by donmccurdy** [comment]
Awesome, glad to hear! I'll get this published to the stable release soon then.
