### ISSUE TITLE
Rename "GPU memory size" to "Min GPU memory size"

### ISSUE THREAD

**Issue by lexaknyazev** [donmccurdy/glTF-Transform#197]
Rationale:
1. When compressed transcode targets are not available, KTX textures will be decoded to RGBA8 thus matching the uncompressed size (the same as PNG / JPEG).
2. On desktop platforms, opaque ETC1S may be transcoded to BC7 that uses 16 bytes per block.

**Comment by donmccurdy** [comment]
Since this column name also applies to PNG/JPG textures, and the GPU memory size estimates there are assuming expansion to RGBA8, wouldn't a "minimum" size need to be lowered for PNG/JPG? I guess the alternative would be something like "estimated GPU memory size"?

**Comment by lexaknyazev** [comment]
"Estimated" is too vague, but I don't have any better proposals.
- PNG / JPG are _always_ expanded to RGBA8 on platforms that use D3D or Metal.
- On OpenGL or Vulkan desktops, only Intel hardware may directly support 24-bit pixels, other vendors expand them in-driver, IIRC. Some mobile GPUs do support RGB8 natively, though.
- Transcoded size of single-slice opaque ETC1S on desktops is a matter of choice. We recommend BC7 (16 bytes per block) as it's gives less transcoding loss than BC1 (8 bytes per block) although the latter is a still a valid option.

**Comment by donmccurdy** [comment]
Updated output, example below:

***

TEXTURES
 ────────────────────────────────────────────
| # | name | uri | slots            | instances | mimeType  | resolution | size      | gpuSize¹ |
| - | ---- | --- | ---------------- | --------- | --------- | ---------- | --------- | -------- |
| 0 | | baseColor.ktx2 | baseColorTexture | 1         | image/ktx2 | 512x512  | 123 KB | 456 KB  |

¹ gpuSize estimates minimum GPU memory allocation. Older devices may require
  additional memory for GPU compression formats.
