### ISSUE TITLE
Choosing buffer data layout

### ISSUE THREAD

**Issue by ukito-pl** [donmccurdy/glTF-Transform#200]
Hi, 
I recently bump into an issue with viewing skinned models generated from gltf-transform in SceneViewer Preview (https://arvr.google.com/scene-viewer-preview).
For example:
1. Download this sample model https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/RiggedFigure
2. Copy it with gltf-transform cli 
`gltf-transform copy RiggedFigure.glb RiggedFigure2.glb`
3. View copied model on https://arvr.google.com/scene-viewer-preview Model will not be shown. Logs show error: 
`Error: Loader.tryLoad: Weight stride 48 must match sizeof(float4)`

From this log I deduce that there is a problem with `WEIGHT_0` attribute being interleaved with other vertices attributes. This is obviously viewer bug that should be resolved (or maybe there is some good reason behind this behaviour?), but in a meantime I am wondering if it is possible to choose layout of the buffer data in which gltf-transform will save the model? Is it possible in gltf-transform to save vertices data in standard _struct of arrays_ layout instead of _interleaved_ layout?

**Comment by donmccurdy** [comment]
It would be good to check the rewritten model against https://github.khronos.org/glTF-Validator/. If the model is valid there, it's certainly a bug/limitation in Scene Viewer if it can't open it. If it's not valid, that's something that glTF-Transform should certainly fix.

That said, I'm not opposed to providing an option for the buffer layout. I'm not exactly sure how the option would be passed, since I'd like to avoid adding a new flag to _every_ command in the CLI, but we can figure that out.

**Comment by ukito-pl** [comment]
Yes, the model is perfectly valid, it is clearly Scene Viewer limitation (one of many) so I'm forced to sometimes use some workarounds :( 

I don't necessarily mean to add this option to the CLI (but it can be added as global option, not bound to any specific command). Just adding an optional property 'bufferLayout' to [WriterOptions](https://github.com/donmccurdy/glTF-Transform/blob/32726bfb73c2b84dd55fdc5422bd19a7f87bfd00/packages/core/src/io/writer.ts#L22) would be sufficent and clean solution I think.

**Comment by donmccurdy** [comment]
I've published a new version as an alpha, could you try...

```
npm install --global @gltf-transform/cli@alpha
```

... and let me know if this works as expected? See https://github.com/donmccurdy/glTF-Transform/pull/204 for details.

**Comment by ukito-pl** [comment]
Thank you very much! I have tested it and it works like a charm :)
