### ISSUE TITLE
how to use gltf transform in vs C# windows form app

### ISSUE THREAD

**Issue by maakkoush** [donmccurdy/glTF-Transform#201]
Hi,
I am trying to create a test project to generate a simple gltf file using gltftransform core package. Please how to use it to implement such sample? I tried to install the package using npm but it is not working.

thanks

**Comment by donmccurdy** [comment]
Hi, this project is written in TypeScript, and compiled to JavaScript. I don't know C#, but I'm pretty sure you won't be able to use code in these languages directly in a C# project. If your C# code is running in an environment where you can access commandline utilities, you could install the CLI package and make calls to it instead. See:

- https://stackoverflow.com/questions/1469764/run-command-prompt-commands
- https://gltf-transform.donmccurdy.com/cli.html

**Comment by donmccurdy** [comment]
Also worth considering:

- https://github.com/vpenades/SharpGLTF
- https://github.com/jkuhlmann/cgltf
