### ISSUE TITLE
More control over GLB output / external content uri

### ISSUE THREAD

**Issue by dbuck** [donmccurdy/glTF-Transform#207]
I'd like the ability to be more explicit about what is bundled together when saving a document. I'm using the library to add material variants with multiple sized textures for use in a texture LOD system. 

Ex: when saving to GLB, I would like to continue to embed the initial texture, but I'd like to reference the alternate higher res textures by external uri.

**Comment by donmccurdy** [comment]
I made two design decisions related to external resources in this library that are a bit opinionated, but which I think have some value:

1. When writing `.gltf` files, never use embedded Data URIs.
  - Avoids significant performance loss in viewers.
2. When writing `.glb` files, all resources are embedded in buffers.
  - Not required by glTF specification, but a clear convention.

Between those, I think that does not allow me to implement this suggestion... (2) is the weaker argument of the two, for sure. But given that the use case here is to implement custom LODs on top of the `KHR_materials_variants` extension, it feels like a bit of an unusual workflow. I'd be curious if something like this would work just as well?

```
const uri = texture.getURI();
const texture.setExtras({
  lod0: FileUtils.basename(uri) + '@0' + FileUtils.extension(uri),
  lod0: FileUtils.basename(uri) + '@0' + FileUtils.extension(uri),
});
```

**Comment by dbuck** [comment]
(I fully get that my use cases may not fit the standard workflows, but maybe the examples can help?!)

That's fair for texture lod use case, my premise behind trying to use variants over extras was that it might allow downstream model consumers to use established/built-in extensions rather than adding a vendor specific extension, while also allowing us to do more nuanced loading in our own viewer.

A second case that I'd run into recently was the desire to split up a large (10m face) mesh into multiple tiles to amortize the costs of loading over time. It was helpful to allow the separate glb files to target toward a single set of externally referenced textures, so that I could leverage the browser cache (with the default three loaders) or an in memory cache with some light custom extension work on the loaders.

**Comment by dbuck** [comment]
> 2. When writing .glb files, all resources are embedded in buffers.
>      * Not required by glTF specification, but a clear convention.

I've got another case where I'm desiring external referenced texture content in .glb. I know this wasn't supported months back, but is it feasible to output .glb + .ktx2 now? if not yet, do you have any problem with accepting a change which supports that?

(Context: 3d-tiles) - I have multiple mesh tiles which reference the same texture atlas. I'd like to continue to use .glb, but reference an external .ktx2 file for the texture atlas, and let the loader handle the caching side of things.

**Comment by dbuck** [comment]
I'm not sure whether you'd want to enable this level of hackery in the actual package, seems like a recipe for questions. BUT it is possible to allow just by exposing an alternate set of arguments for io.writeBinary? 

Example snippet of more explicit control of the final output, while keeping the internal safety checks during normal editing?

```
import { BufferUtils, Document, NodeIO } from '@gltf-transform/core';
import fs from 'fs';

// customized writer, purely to allow .glb with an external image uri
export function writeGlbWithoutImage(nodeIo: NodeIO, doc: Document, outputUri: string, imageUri?: string): void {
  const {json, resources} = nodeIo.writeJSON(doc);
  // place which allows me the option to footgun myself by mutating the json
  // remove reference to .bin uri
  delete json.buffers[0].uri
  // and dropping the texture we don't want to embed
  if (imageUri && imageUri in resources) {
    delete resources[imageUri];
  }
  const buffer = Buffer.from(writeBinary(json, resources));
  fs.writeFileSync(outputUri, buffer);
}

/**
 * duplicate of platform-io writeBinary function from `packages/core/src/io/platform-io.ts#L198`
 * except allowing custom json/resources as input
*/
function writeBinary(json: Record<string, any>, resources: {[s: string]: ArrayBuffer}): ArrayBuffer {
  const header = new Uint32Array([0x46546C67, 2, 12]);

  const jsonText = JSON.stringify(json);
  const jsonChunkData = BufferUtils.pad( BufferUtils.encodeText(jsonText), 0x20 );
  const jsonChunkHeader = new Uint32Array([jsonChunkData.byteLength, 0x4E4F534A]).buffer;
  const jsonChunk = BufferUtils.concat([jsonChunkHeader, jsonChunkData]);
  header[header.length - 1] += jsonChunk.byteLength;

  const binBuffer = Object.values(resources)[0];
  if (!binBuffer || !binBuffer.byteLength) {
    return BufferUtils.concat([header.buffer, jsonChunk]);
  }

  const binChunkData = BufferUtils.pad(binBuffer, 0x00);
  const binChunkHeader = new Uint32Array([binChunkData.byteLength, 0x004E4942]).buffer;
  const binChunk = BufferUtils.concat([binChunkHeader, binChunkData]);
  header[header.length - 1] += binChunk.byteLength;

  return BufferUtils.concat([header.buffer, jsonChunk, binChunk]);
}

```

**Comment by donmccurdy** [comment]
This is handled to an extent by https://github.com/donmccurdy/glTF-Transform/pull/477 – absolute URLs are ignored during the writing process, and not copied to disk.

**Comment by 06wj** [comment]
> This is handled to an extent by #477 – absolute URLs are ignored during the writing process, and not copied to disk.

In v3.4.0, when converting to glb, the image will still be converted to embed image, and it is good when converting to gltf.

**Comment by donmccurdy** [comment]
@06wj #477 applied only to writing `.gltf`. When writing a `.glb`, glTF Transform will always embed the binary resources to create a self-contained file.

**Comment by 06wj** [comment]
> @06wj #477 applied only to writing `.gltf`. When writing a `.glb`, glTF Transform will always embed the binary resources to create a self-contained file.

I hope there is a parameter when exporting glb without embed images

**Comment by donmccurdy** [comment]
@06wj sorry, this is something I've decided against for this project. Exports to '.glb' will always embed resources for consistency with glTF ecosystem conventions — '.gltf' should be used for external resources instead.

**Comment by jo-chemla** [comment]
Hi @donmccurdy, sorry for commenting on a closed discussion. Is the above discussion still relevant? Choice has been made that 
 - `glb` produced by gltf-transform will always embed textures,
 - and the only way to reference external textures would be to output to `gltf`? 
 
Thanks!

**Comment by donmccurdy** [comment]
Within glTF Transform, yes. An alternative would be to use ...


```javascript
const { json, resources } = await io.writeJSON(document);
```

... and then you have more flexibility with how and where to write the resources.

**Comment by jo-chemla** [comment]
Perfect, thanks for that confirmation!
