### ISSUE TITLE
Improve quantization

### ISSUE THREAD

**Issue by donmccurdy** [donmccurdy/glTF-Transform#208]
Current implementation discontinuous at 0, for bits >8 and <16. The most obvious 
way of fixing that would be...

Math.round(el[j] * (quantScale - 1)) * storeScale;

...but then we don't maintain 1 -> (2^storeScale - 1) at the extremes. Could
also consider doing a bit more rounding...

Math.round(el[j] * (quantScale - 1)) * (storeScale + K)

...but I'm not at all sure that's right, and if our goal was to have some bit-
level consistency in the result we've surely erased it. Moreover, whatever we
implement needs to "just work" for bits=8 or bits=16.

**Comment by lexaknyazev** [comment]
Could you please provide a specific troublesome example of bit width and float value range? I'm not sure I understand the core issue here.

**Comment by donmccurdy** [comment]
@lexaknyazev Thanks for asking! Mostly I think the code I've written in #59 is simply incorrect:

https://github.com/donmccurdy/glTF-Transform/blob/1ec0890d95042e8a97f10b31b7a44a9a0d62601b/packages/lib/src/quantize.ts#L204-L228

The `KHR_mesh_quantization` specification explains clearly how to quantize data to 8 or 16 bits. I'm trying to support quantizing to 9-15 bits as well, because (1) Draco and MeshOpt provide the option, and (2) even though the storage is still 16-bit, it compresses better under gzip or zstandard. For example, quantizing positions to 14 bits before storing in a 16-bit accessor.

My current implementation subtracts 1 from positive values and adds 1 to negative values, rather than simply multiplying by a factor of appropriate scale. I would expect that to cause values near zero to be quantized discontinuously, but haven't created a test case for the bug yet.

**Comment by lexaknyazev** [comment]
> For example, quantizing positions to 14 bits before storing in a 16-bit accessor.

What exactly does this mean?
- Keeping two most significant bits as zeros effectively reducing the unquantized range?
- Keeping two least significant bits as zeros, i.e. truncating the precision?
- Uniformly remapping full-precision 16-bit values to reduced-precision 16-bit values so that there are only 2<sup>14</sup> unique values?

Note that, the exact steps would be different for `[0.0 ... 1.0]` and `[-1.0 ... 1.0]` inputs.

**Comment by lexaknyazev** [comment]
Assuming that the third option is intended here, the correct steps for `[0.0 ... 1.0]` inputs are:
```js
const storageBits = 16;
const quantBits = 14;
const scale = (1 << quantBits) - 1;

// map to [0.0 ... 1.0] to [0 ... 16383]
let quantValue = Math.round(floatValue * scale);

// replicate msb to missing lsb
quantValue = (quantValue << (storageBits - quantBits)) | (quantValue >> (2 * quantBits - storageBits));
```

The last step could be explained with a shorter example: a 4-bit value `abcd` is scaled to 6-bit storage as `abcdab`.

**Comment by donmccurdy** [comment]
> What exactly does this mean?
> 
> -    Keeping two most significant bits as zeros effectively reducing the unquantized range?
> -    Keeping two least significant bits as zeros, i.e. truncating the precision?
> -    Uniformly remapping full-precision 16-bit values to reduced-precision 16-bit values so that there are only 214 unique values?

This framing of the question is helpful. Probably not (1), because it requires additional dequantization factors I can't provide for all attribute types. Between (2) or (3), I'm not sure. Here's a test case I'm using to evaluate options.

<details>

<summary>**Test case:**</summary>

```js
test.only('@gltf-transform/lib::quantize | position continuity', async t => {
	const doc = new Document();
	const position = createFloatAttribute(doc, 'POSITION', VEC3, new Float32Array([
		-1, -1, -1,
		-.005, -.005, -.005,
		-.004, -.004, -.004,
		-.003, -.003, -.003,
		-.002, -.002, -.002,
		-.001, -.001, -.001,
		0, 0, 0,
		.001, .001, .001,
		.002, .002, .002,
		.003, .003, .003,
		.004, .004, .004,
		.005, .005, .005,
		1, 1, 1,
	]));
	const positionCopy = position.clone();

	await doc.transform(quantize({quantizePosition: 14}));

	if (positionCopy.getNormalized() || !(positionCopy.getArray() instanceof Float32Array)) {
		t.fail('Backup copy of positions was modified');
	}

	t.ok(position.getNormalized(), 'position → normalized');
	t.ok(position.getArray() instanceof Int16Array, 'position → Int16Array');

	console.log('BEFORE', util.inspect(positionCopy.getArray(), {breakLength: 200}));
	console.log('AFTER', util.inspect(position.getArray(), {breakLength: 30}));

	elementPairs(position, positionCopy, round(4))
		.forEach(([a, b], i) => t.deepEquals(a, b, `position value #${i + 1}`));
	t.end();
});
```
</details>

<details>

<summary>**Output:**</summary>

Before:

```
-1, -1, -1,
-.005, -.005, -.005,
-.004, -.004, -.004,
-.003, -.003, -.003,
-.002, -.002, -.002,
-.001, -.001, -.001,
0, 0, 0,
.001, .001, .001,
.002, .002, .002,
.003, .003, .003,
.004, .004, .004,
.005, .005, .005,
1, 1, 1,
```

After:

```
      -32767, -32767, -32767,
        -163,   -163,   -163,
        -131,   -131,   -131,
         -99,    -99,    -99,
         -63,    -63,    -63,
         -31,    -31,    -31,
           0,      0,      0,
          31,     31,     31,
          63,     63,     63,
          99,     99,     99,
         131,    131,    131,
         163,    163,    163,
       32767,  32767,  32767
```

</details>

Nothing unusual in continuity around zero, so that might have been a red herring.

**Comment by lexaknyazev** [comment]
The expectations clearly point to the third case because otherwise `1.0` is unachievable.

**Comment by donmccurdy** [comment]
That's the goal then, thanks again. Filed https://github.com/donmccurdy/glTF-Transform/pull/209.

Simple test ([source](https://sketchfab.com/3d-models/matilda-7ddedfb652bd4ea091bc3de27f98fc02)) w/ no visible issues, 6.5 MB → 4 MB:

![Screen Shot 2021-04-01 at 6 39 47 PM](https://user-images.githubusercontent.com/1848368/113371117-605be500-931a-11eb-9a4b-397bdcf17867.png)
