### ISSUE TITLE
Align toktx usage with the latest release

### ISSUE THREAD

**Issue by lexaknyazev** [donmccurdy/glTF-Transform#215]
The latest KTX-Software release has full support for Red and Red-Green texture types as well as better control over color management metadata.

- [ ] Use `--assign_oetf linear --assign_primaries none` instead of `--linear` for non-color textures.
- [ ] Use `--target_type R` for standalone occlusion maps.

**Comment by zeux** [comment]
Is there any information wrt *why* the command line attributes mentioned in this issue are recommended for use? (e.g. why is `--assign_*` better than `--linear` or why is it important to specify R/RG for textures that don't use other channels)

**Comment by lexaknyazev** [comment]
@zeux 
- `--assign_oetf linear` does the same as the old `--linear`. The latter is deprecated.
- `--assign_primaries none` ensures that textures that contain non-color data (e.g. normals) are not marked as using any specific color primaries.
- Setting R/RG texture type leads to KTX files having proper DFD configurations that enable more efficient transcode format selection. For example, a single-channel texture encoded to ETC1S with `--target_type R` would use `ETC1S_RRR` slice type. At runtime, an engine may rely on that information to knowingly select BC4 as the transcode target.

**Comment by zeux** [comment]
Ok - thanks. Does `assign_oetf` still communicate the color space information to the compressor to make sure the non-perceptual color metric is used? The name suggests this just controls the output DFD but hopefully that's not the case.

**Comment by lexaknyazev** [comment]
`--assign_oetf` overrides the transfer function of the input image just like the old `--linear`. It still does communicate the perceptual flag, although tying the latter to `--assign_primaries` would be a more correct approach because that perceptual flag applies per-component weights that originated from the specific primaries.
