### ISSUE TITLE
Unable to write GLB with 0 buffers

### ISSUE THREAD

**Issue by VelocityRa** [donmccurdy/glTF-Transform#228]
My use case is web and I want to export to .gltf/.glb files.

I'll do that via simply downloading through the browser. I can handle that part, but it'd be helpful of the library to handle the rest (converting the `Document` to `ArrayBuffer` for glb, and a JSON string for the gltf).
Not sure how to do that with the current state of the library.

**Comment by donmccurdy** [comment]
I think writeBinary and writeJSON are what you're looking for: https://gltf-transform.donmccurdy.com/classes/webio.html

**Comment by donmccurdy** [comment]
May need to enable the "Inherited" checkbox in the docs if it isn't already!

**Comment by VelocityRa** [comment]
Hey, thanks for the reply.

I saw these, but `writeJSON` returns a `JSONDocument` which I'm not sure how to convert to a JSON string.
And `writeBinary` which I initially tried errors out with `Error: GLB must have exactly 1 buffer.`.

My test code for the latter was:
```ts
            const io = new WebIO({ credentials: 'include' });

            let doc = new Document();

            doc.createCamera('p')
                .setType('perspective')
                .setZNear(0.1)
                .setZFar(10)
                .setYFov(Math.PI / 5)
                .setAspectRatio(.5);

            let glbBuf = io.writeBinary(doc);
            downloadBuffer(`${this.id}.glb`, glbBuf);
```
Shouldn't this work?

**Comment by VelocityRa** [comment]
More about my use case: I've written a file format parser for a video game's mesh + texture assets in Typescript and I want to export these to glTF for offline viewing/debugging/research. I have an obj/mtl/png exporter currently but it's very limited & slow as you can imagine (lots & large assets). Importing to Blender takes ~45 minutes for a single level.

**Comment by donmccurdy** [comment]
Your code looks right, does including `document.createBuffer()` fix that error? I believe the GLB export does require a buffer, which might be a bug in the library, it's just unusual in this case because normally there would be vertex data or textures with binary data, and the camera doesn't require any. 

I'll look into this more in a bit!

**Comment by VelocityRa** [comment]
> Your code looks right, does including document.createBuffer() fix that error?

Huh yeah it does.

**Comment by donmccurdy** [comment]
I'll mark this as a bug – the [GLB spec does not require a binary buffer](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#chunks), it's just unusual to not need one — i.e. to not have any mesh data — so I hadn't implemented that yet.

**Comment by VelocityRa** [comment]
Fair enough! Thanks for looking into it.

**Comment by donmccurdy** [comment]
I'm not quite sure how best to export a file like this; asking for clarification in https://github.com/KhronosGroup/glTF/issues/1975.
