### ISSUE TITLE
gltf-transform inspect FILE --format csv has INFO header without CSV format

### ISSUE THREAD

**Issue by hybridherbst** [donmccurdy/glTF-Transform#229]
Judging from the screenshots in #186 this is currently "by design", but I'm wondering why the "INFO" section isn't formatted the same as the others for each respective format - 
this makes parsing the result programmatically difficult (e.g. to get the list of extensions used/required).

(it's made harder by the fact that some of the characters seem to not get written properly when rerouting the process output:
![image](https://user-images.githubusercontent.com/2693840/115164443-a6e86800-a0ac-11eb-8be6-c4f5489f9db0.png))

**Comment by donmccurdy** [comment]
Hm, yeah I think that first table's layout could be improved (in CSV and perhaps in other formats). It doesn't really fit the CSV pattern of...

```
header,header,header
cell,cell,cell
cell,cell,cell
```

... but should at least stick to ASCII characters here.

**Comment by hybridherbst** [comment]
Just wanted to start making a PR for this - turns out I was probably running an old version when generating that screenshot 🤦
In current versions it's already formatted as key/value:
![image](https://user-images.githubusercontent.com/2693840/115211332-c0ff6600-a0ff-11eb-9b19-950014f7ca11.png)

Sorry! Closing this.

**Comment by donmccurdy** [comment]
Ah ok! I'd forgotten that. :) I still have a hunch the "key/value" thing could be improved, but it was the best option I saw at the time. I'll close this issue unless other ideas come up.
