### ISSUE TITLE
Simplify/decimate geometry

### ISSUE THREAD

**Issue by donmccurdy** [donmccurdy/glTF-Transform#244]
It's pretty common to see models that have far too many vertices for rendering purposes: LiDAR scans are a good example. In these cases quantization or Draco compression are not really the first tool you should reach for — they'll reduce the size of the model, but it still has too many triangles. 

It'd be nice to have a simplification tool available in this library, similar to Blender's "decimate" modifier. Some other libraries that could be used here:

- https://www.npmjs.com/package/mesh-simplify: Appears unmaintained, and doesn't support much in the way of vertex attributes.
- https://github.com/whydoidoit/playcanvas-decimator: Appears unmaintained, supports more vertex attributes, but not arbitrary vertex attributes.
- https://docs.rs/meshopt/0.1.4/meshopt/simplify/fn.simplify.html: Can we compile this to WASM?

Others, not yet evaluated:

- https://github.com/sp4cerat/Fast-Quadric-Mesh-Simplification/issues/8

**Comment by donmccurdy** [comment]
Unclear if this is fully working, but an example with meshopt/rust/wasm here: 

- https://github.com/blaze33/droneWorld/blob/master/src/terrain/dem2mesh/src/lib.rs
- https://github.com/blaze33/droneWorld/commit/ea063f885017c2785e4b9f04da47926ddbf83f5e#diff-24acfe42a8bf538d002dac47d06053cca2f7b81d03fe065f462ec7d3db31890e
- https://twitter.com/maxmre/status/1160002085439586310

**Comment by donmccurdy** [comment]
Related: https://github.com/gwihlidal/meshopt-rs/issues/22

**Comment by zeux** [comment]
> https://docs.rs/meshopt/0.1.4/meshopt/simplify/fn.simplify.html: Can we compile this to WASM?

fwiw I plan to do this as well as part of the other JS components, but I first need to do some long needed work on the simplifier itself.

**Comment by donmccurdy** [comment]
None of the existing implementations I've found seemed complete enough (few vertex attributes supported, mainly), so I'd been expecting to need to write something from scratch... if you're able to expose a WASM implementation with the meshoptimizer JS API that'd be wonderful!

**Comment by angelhodar** [comment]
Hey @donmccurdy how is this feature going on? I have seen that ghe gltfpack from @zeux has a command that does the simplifying so it should be readh to implement?

**Comment by donmccurdy** [comment]
The gltfpack package is a standalone tool for comprehensively rebuilding an optimized glTF asset. To bring simplification into glTF Transform I'd instead need a low-level library similar to the [meshoptimizer](https://www.npmjs.com/package/meshoptimizer) modules used for meshopt encoding/decoding.

None of the JS simplification modules I've found so far appear suitable¹, and building one from scratch would be a pretty big project for me to do on free time, so there's no progress or immediate plans on this issue right now.

<i><small>¹ Criteria: Module should support arbitrary vertex attributes (not just position+normals), and should work in both Web and Node.js environments (WASM is OK but not native binaries).</small></i>

**Comment by donmccurdy** [comment]
- Fixed by #655
