### ISSUE TITLE
Accessor count is zero in draco compressed glb files

### ISSUE THREAD

**Issue by ajay98gane** [donmccurdy/glTF-Transform#253]
I am trying to compress glb files using gltf-transform. This is my code

`
    const io = new core.WebIO()
        .registerExtensions([extension.DracoMeshCompression])
        .registerDependencies({
            'draco3d.encoder': new DracoEncoderModule(),
            'draco3d.decoder': new DracoDecoderModule(),
        });

    const document = io.readBinary(file);

    document.createExtension(extension.DracoMeshCompression)
        .setRequired(true)
        .setEncoderOptions({
            method: extension.DracoMeshCompression.EncoderMethod.EDGEBREAKER,
            encodeSpeed: 5,
            decodeSpeed: 5,
        });

    console.log(io.writeJSON(document,{isGLB:false}));`

<img width="977" alt="Screenshot 2021-05-17 at 7 30 23 PM" src="https://user-images.githubusercontent.com/46472663/118501485-667d1800-b746-11eb-92c6-61edc30e76c3.png">

I am getting accessors count as zero in output file.

i tried this with few glb files and issue is reproducible in all of it.(This occurs only when DracoMeshCompression extension is added).
you can also check this with gltf-valdiator.

reference: [issue reported in filament](https://github.com/google/filament/issues/3948)

Can anyone check this? Thanks in advance

**Comment by donmccurdy** [comment]
Would you be able to share a version of the glTF model before Draco compression has been added? I can't reproduce the issue, decompressing and then recompressing this same model I see non-zero count. It may also be worth trying to update to v0.11 of glTF-Transform in case that fixes the issue.

![Screen Shot 2021-05-17 at 10 24 19 AM](https://user-images.githubusercontent.com/1848368/118531024-327c0580-b6fa-11eb-8260-5105d7308c47.png)

I'm also not sure that the usage of the Draco module above is quite right. In [my own tests on web](https://stackoverflow.com/questions/66975407/convert-glb-to-draco-glb-front-end/66978236#66978236) I'd used `await new DracoEncoderModule()` for the WASM module imports, but perhaps that wasn't necessary.

**Comment by ajay98gane** [comment]
updating to v0.11 fixed the issue.
Thanks for your help.
