### ISSUE TITLE
Feature request: apply transform to model

### ISSUE THREAD

**Issue by looeee** [donmccurdy/glTF-Transform#258]
My use case for this is that poly models come with `presentationParams` data:

``` js
"presentationParams": {
        "orientingRotation": {
            "x": -0.7071067811865475,
            "w": 0.7071067811865476
        },
        "colorSpace": "LINEAR",
        "backgroundColor": "#4caf50"
    }
```

In most cases it's just:

```
"orientingRotation": {
  "w": 1
},
```

and the model is correctly oriented. However for some models (like the one above with `w="0.7..."`) the model will load with incorrect orientation and I'd like to be able to fix that. 

This could also be used to transform models between coordinate system or fix incorrectly scaled models.

**Comment by donmccurdy** [comment]
As a script this should work:


```ts
import { Document, Transform, vec4 } from '@gltf-transform/core';

const orientation = (options: {quat: vec4}): Transform => {
	return async (document: Document): Promise<Document> => {
		const scene = document.getRoot().listScenes().pop();
		const rootNode = document.createNode('SceneRotation')
			.setRotation(options.quat);
		for (const node of scene.listChildren()) {
			rootNode.addChild(node);
		}
		scene.addChild(rootNode);
		return Promise.resolve(document);
	};
};

await document.transform(
	orientation({quat: [-0.707106, 0, 0, 0.707106]})
);
```

Does that seem workable? glTF does specify how a scene is supposed to be oriented, so I'd rather not add a built-in function to convert to other coordinate systems.

**Comment by looeee** [comment]
Ah, that was easy ^_^ 

Yeah, I think that's ok.

**Comment by ffdead** [comment]
I have a similar problem when models exported from for instance Blender have transformations like `scale`, `rotation` and `position`.

We sometimes require these to be applied to the mesh before exporting, but designers have a tendency to forget, so would be nice to have that as part of the pipeline.

![image](https://user-images.githubusercontent.com/420472/166522199-db9b15f4-bf6b-46bd-bd5c-26a58830d4c0.png)

Do you know a way of recursively applying all or one type of transformations on a model, using `glTF-Transform` or some other tool?

**Comment by donmccurdy** [comment]
Filed as — https://github.com/donmccurdy/glTF-Transform/issues/579
