### ISSUE TITLE
Fix non unit normals

### ISSUE THREAD

**Issue by looeee** [donmccurdy/glTF-Transform#261]
A common error that I'm encountering is `Vector3 at accessor indices 102..104 is not of unit length: 0`. 

Is within scope to add a function to normalize normals? Or even to just do it automatically on read/write?

**Comment by lexaknyazev** [comment]
Zero-length normal vector usually indicates some authoring issue - there's probably not enough information in the asset to generate it automatically.

@donmccurdy WDYT?
