### ISSUE TITLE
Creating large mesh results in broken indices

### ISSUE THREAD

**Issue by donalffons** [donmccurdy/glTF-Transform#262]
Hi!
Thank you so much for your great work on this library. The API is really intuitive and well designed.

Here's my problem:
I have an application that can convert `STEP` files to GLB in varying quality levels (i.e. with different polygon counts). I want to merge all mesh objects in that file that share the same material. The relevant part of my code looks like this:

```js
  // => 1: Determine sizes of the new ArrayBuffers
  let numPositions = 0;
  let numNormals = 0;
  let numIndices = 0;
  for(let entity of entitiesToMerge) {
    const posArray = entity.primitive.getAttribute("POSITION")?.getArray();
    const normalArray = entity.primitive.getAttribute("NORMAL")?.getArray();
    const indexArray = entity.primitive.getIndices()?.getArray();
    if(!posArray || !normalArray || !indexArray) throw new Error("invalid data!");
    numPositions += posArray.length;
    numNormals += normalArray.length;
    numIndices += indexArray.length;
  }

  // => 2: Create and initialize ArrayBuffers
  const newPositions = new Float32Array(numPositions);
  const newNormals = new Float32Array(numNormals);
  const newIndices = new Uint32Array(numIndices);
  let positionOffset = 0;
  let normalOffset = 0;
  let indexOffset = 0;

  // => 3: Perform Merge
  for(let entity of entitiesToMerge) {
    const arr = entity.primitive.getAttribute("POSITION")?.getArray();
    if(!arr) throw new Error("invalid data!");
    const newArr = new Float32Array(arr.length);
    const mat = entity.worldMatrix;
    for(let i = 0; i < arr.length; i+=3) {
      newArr[i+0] = mat[0] * arr[i+0] + mat[4] * arr[i+1] + mat[8]  * arr[i+2] + mat[12];
      newArr[i+1] = mat[1] * arr[i+0] + mat[5] * arr[i+1] + mat[9]  * arr[i+2] + mat[13];
      newArr[i+2] = mat[2] * arr[i+0] + mat[6] * arr[i+1] + mat[10] * arr[i+2] + mat[14];
    }
    newPositions.set(newArr, positionOffset);

    const crr = entity.primitive.getAttribute("NORMAL")?.getArray();
    if(!crr) throw new Error("invalid data!");
    newNormals.set(crr, normalOffset);

    const brr = entity.primitive.getIndices()?.getArray();
    if(!brr) throw new Error("invalid data!");
    newIndices.set(brr.map(i => i+positionOffset/3), indexOffset);

    positionOffset += arr.length;
    normalOffset += crr.length;
    indexOffset += brr.length;
  }

  // => 4: Assign ArrayBuffers to myNode
  const positionAccessor = inputDoc.createAccessor("positionAccessor");
  positionAccessor.setType("VEC3");
  positionAccessor.setArray(newPositions);
  (myNode.getMesh() as Mesh).listPrimitives()[0].setAttribute("POSITION", positionAccessor);

  const normalAccessor = inputDoc.createAccessor("normalAccessor");
  normalAccessor.setType("VEC3");
  normalAccessor.setArray(newNormals);
  (myNode.getMesh() as Mesh).listPrimitives()[0].setAttribute("NORMAL", normalAccessor);
  (myNode.getMesh() as Mesh).listPrimitives()[0].setMaterial(material);

  const indexAccessor = inputDoc.createAccessor("indexAccessor");
  indexAccessor.setType("SCALAR");
  indexAccessor.setArray(newIndices);
  (myNode.getMesh() as Mesh).listPrimitives()[0].setIndices(indexAccessor);
```

That code works pretty nicely with "small" mesh. The picture below  shows my test mesh with 113,604 lines.
![image](https://user-images.githubusercontent.com/33040347/119364872-aa749d80-bcaf-11eb-8427-e0ba686904e1.png)

When I have larger meshes, the code suddenly stops working and produces wrong results. This picture shows my test mesh with 227,220 lines.
![image](https://user-images.githubusercontent.com/33040347/119365204-fe7f8200-bcaf-11eb-8e48-c2a8e8ad3426.png)

When I discard the indices in my code (see picture below), I expectedly get a garbage result. However, from that result it is visible that vertices are exported correctly. Therefore, I suspect that the issue has something to do with the indices.
![image](https://user-images.githubusercontent.com/33040347/119365559-53bb9380-bcb0-11eb-828d-e6e401086679.png)

The full source code of my algorithm is attached along with a "large" mesh version of my test file. Running the code against the input file results in the broken output file.

Input GLB file: [problemModel.glb.txt](https://github.com/donmccurdy/glTF-Transform/files/6533193/problemModel.glb.txt)

Output GLB file: [outputModel.glb.txt](https://github.com/donmccurdy/glTF-Transform/files/6533429/outputModel.glb.txt)

[optimizeGLB.ts.txt](https://github.com/donmccurdy/glTF-Transform/files/6533197/optimizeGLB.ts.txt)

Any help would be greatly appreciated.

**Comment by donalffons** [comment]
...nevermind, I think I found the solution

Replacing this line
```js
newIndices.set(brr.map(i => i+positionOffset/3), indexOffset);
```

with a good old loop solves the issue
```js
for(let i = 0; i < brr.length; i++) {
   newIndices[i+indexOffset] = brr[i]+positionOffset/3;
}
```

...there's probably something overflowing in that ArrayBuffer. Tested this on this model with ~400,000 lines and its still working fine.
![image](https://user-images.githubusercontent.com/33040347/119373651-ed873e80-bcb8-11eb-9855-ff24d67c2444.png)

Thank you so much for this library!

**Comment by donmccurdy** [comment]
Glad you were able to get it working! If the finished STEP -> GLB converter ends up being open source I'd be curious to check it out, but no worries if not! At some point I'd like to support merging meshes and flattening a scene graph automatically (https://github.com/donmccurdy/glTF-Transform/issues/11) but haven't gotten around to that yet. :)

**Comment by donalffons** [comment]
I'm using OpenCascade to convert STEP to GLB. I'm working on porting OpenCascade to JS + WASM in [this repo](https://github.com/donalffons/opencascade.js). There's also an [example repo](https://github.com/donalffons/opencascade.js-examples), which contains a simple STEP file loader (as part of the "Bottle" examples).

There are still several things missing in that project, but I'm determined to get it to a stage where it can be used "easily" for production applications.

Here' s a quick demo of the converter.

![ezgif-4-5eb7ccefbd71](https://user-images.githubusercontent.com/33040347/119398297-a9576680-bcd7-11eb-8412-fed15acb78fa.gif)

**Comment by donmccurdy** [comment]
Meant to reply sooner here, but that's an awesome project! Have definitely seen a number of people asking in the threejs forums (https://discourse.threejs.org/) about how to do this sort of conversion. :)
