### ISSUE TITLE
Regression: wrong file size displayed during etc1s encoding with --verbose

### ISSUE THREAD

**Issue by hybridherbst** [donmccurdy/glTF-Transform#274]
It seems the size displayed when encoding etc1s is wrong now (was working in the past):

![image](https://user-images.githubusercontent.com/2693840/121874967-348cb080-cd08-11eb-826d-0eea17cd53a2.png)

As can be seen, every single texture reports "no size change" e.g. 
```debug: • 4.85 MB → 4.85 MB bytes.```

but the resulting file shrinks considerably.

Previously, the → size was showing the reduced file size.

Might be since the switch to toktx 4?

**Comment by donmccurdy** [comment]
Thanks! Should be fixed on next version.
