### ISSUE TITLE
Error: Missing required extension, "KHR_lights_punctual".

### ISSUE THREAD

**Issue by zaaakk** [donmccurdy/glTF-Transform#275]
I get this error when trying to use NodeIO.read on a GLB binary exported from Blender 2.92.
It doesn't happen on the Khronos test GLB models.

**Comment by zaaakk** [comment]
My bad, didn't see I had to import those as an extension

**Comment by aiden-jeffrey** [comment]
How do we import the extension? The only way I can find to add the extension to a document is with the `createExtension` method - however, the `NodeIO.read` call fails to create the document, so I don't have anything to call `createExtension` on.

**Comment by aiden-jeffrey** [comment]
ah, `registerExtensions` - sorry for the noise.
