### ISSUE TITLE
Texture can be separated compression options is better.

### ISSUE THREAD

**Issue by mm-longcheng** [donmccurdy/glTF-Transform#276]
Is it possible to set the compression options of "normal map" special.
Normal map usually needs uastc, others use etc1s.

And batch multiple commands, such as activate draco when use texture compression.

**Comment by donmccurdy** [comment]
Hi! Separate compression options for different texture types are supported, yes. For example:

```
# Step 1.
gltf-transform uastc input.glb output.glb --level 4 --rdo 4 --zstd 18 \
    --slots "{normalTexture,occlusionTexture,metallicRoughnessTexture}" \
    --verbose

# Step 2.
gltf-transform etc1s output.glb output.glb --quality 255 --verbose

# Step 3.
gltf-transform draco output.glb output.glb
```

The second step will ignore any textures already compressed by the first. However, it is necessary to run the commands individually, with Draco last. 

Many commands are also available in a scripting context (https://gltf-transform.donmccurdy.com/functions.html) and can be chained together there, but currently KTX/Basis compression is only available through the CLI.

**Comment by mm-longcheng** [comment]
Thank you very much!  
"The second step will ignore any textures already compressed by the first" .
This feature gives us a lot of operability
