### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by JaniKallankari** [donmccurdy/glTF-Transform#28]
> After cloning the repository, run:  yarn install

This produce error:" [Errno 2] No such file or directory: 'install'" 
Could you help with newbie how to proceed with installation?

**Comment by donmccurdy** [comment]
Sounds a bit like [this issue](https://stackoverflow.com/questions/46013544/yarn-install-command-error-no-such-file-or-directory-install), perhaps Node.js or Yarn are using an old version?
