### ISSUE TITLE
Draco compression doesn't work with Sparse Accessors

### ISSUE THREAD

**Issue by hybridherbst** [donmccurdy/glTF-Transform#289]
**Describe the bug**
I'm not entirely sure if the title is accurate, but it seems that draco compression via gltf-transform
a) doesn't keep sparse accessors and thus results in bigger files than passed in
b) breaks the file, error "Offset is outside the bounds of the DataView".

**To Reproduce**
1. Download + unpack
[FacialAnimation.sparse.zip](https://github.com/donmccurdy/glTF-Transform/files/6816650/FacialAnimation.sparse.zip)
2.. Run `gltf-transform draco FacialAnimation.sparse.glb FacialAnimation.sparse.draco.glb`
3. Open the resulting file in https://sandbox.babylonjs.com/

**Expected behavior**
Resulting file should probably be smaller and still work.

**Additional context**
While Babylon rejects the file, threejs/model-viewer play the file (but show the validation errors), with interesting results:
![210714-160556994](https://user-images.githubusercontent.com/2693840/125636271-61ee87ee-4a5a-44d2-a733-3f2f5add5cda.gif)

**Comment by donmccurdy** [comment]
I'm not sure mixing Draco w/ sparse accessors is possible... it may need to be one or the other. But certainly adding Draco to a file should not break it, I'd expect it to just replace the sparse accessors. Thanks for letting me know!

**Comment by donmccurdy** [comment]
On second thought, it's fine to mix compressed and uncompressed attributes in the same mesh primitive, so I suppose the sparse accessors could just be left uncompressed... that should work, but at the moment this tool doesn't have an API for sparse accessors and so things are always unpacked when reading and left un-sparse when writing.

**Comment by donmccurdy** [comment]
Would be curious if you're able to compress this successfully with another tool? I'm getting errors from glTF-Pipeline as well.

The sparse accessors aren't a problem, compression fails on the same model without them. Edge cases I need to handle related to Draco and morph targets... because (1) the Draco extension doesn't compress morph targets, and (2) Draco's default edgebreaker compression change vertex counts, we need to use "sequential" encoding here to keep the vertex count the same. Haven't got that working just yet, will investigate more though.

**Comment by hybridherbst** [comment]
I wasn't aware that draco can't compress morph targets! –
regarding "not going to help much with this model", I agree, but for for some projects we just regularily pass everything through etc1s/draco compression and then manually check (for now, ideally at some point not anymore) if it works and I report bugs otherwise 😄 

I'll look into the other tools and see if I can make reports there. The combination of "many blendshapes + sparse accessors + weight animation + bone animation" seems to bring a good number of tools to their limits (both for processing as well as for rendering) :)

**Comment by donmccurdy** [comment]
Still investigating why the output is broken here – see https://github.com/google/draco/issues/720#issuecomment-886135249.

**Comment by donmccurdy** [comment]
@hybridherbst FWIW, there is a standalone JS implementation of meshopt encoding coming up (https://github.com/zeux/meshoptimizer/pull/322) and I am hoping to include it in glTF-Transform. I think that's likely to be a good solution for this type of data. It doesn't look like gltfpack currently writes sparse accessors, but in theory it could, and compression should benefit them.

**Comment by donmccurdy** [comment]
Proposed fix in #355, support for writing sparse accessors tracked in https://github.com/donmccurdy/glTF-Transform/issues/351.
