### ISSUE TITLE
Resampling should include morph target animations

### ISSUE THREAD

**Issue by hybridherbst** [donmccurdy/glTF-Transform#290]
**Describe the bug**
Seems that resampling is missing some condition for removing/keeping keyframes.
The attached animation breaks after resampling.

**To Reproduce**
1. Download 
[pfc-head-resampling-issue.zip](https://github.com/donmccurdy/glTF-Transform/files/6816761/pfc-head-resampling-issue.zip)
2. Run `gltf-transform resample pfc-head-resampling-issue.glb out.glb`
3. Watch both the original and the result in https://sandbox.babylonjs.com/

**Expected behavior**
Resampled animation looks the same as the original animation but might be smaller file size.
Actual: resampled animation is smaller but looks very different / wrong; mesh breaks in some places.

**Additional context**
Original vs. Resampled
![210714-162338589](https://user-images.githubusercontent.com/2693840/125638773-f78cc695-2a44-48ac-b523-672f318902de.gif) 
![210714-162407417](https://user-images.githubusercontent.com/2693840/125638815-940dfc84-e5ce-48ec-8ad0-0477c84b830f.gif)

**Comment by donmccurdy** [comment]
Next release will have a fix (https://github.com/donmccurdy/glTF-Transform/commit/ab96756c12ddc52ed3f1f648fc0b1023cabbe543) to at least skip these samplers during the resampling process and not break anything. I'll need to do some more work to get the resampling right for morph targets.
