### ISSUE TITLE
toktx transform does not work with current linux builds of ktx-software

### ISSUE THREAD

**Issue by dbuck** [donmccurdy/glTF-Transform#319]
**Describe the bug**
I am unable to use gltf-transform etc1s on linux currently due to the semver restrictions.

ktx-software 4.0.0 linux builds are not returning valid semver strings from `toktx --version`

Related issue: https://github.com/KhronosGroup/KTX-Software/issues/467

Output attempting to use the [ktx-software-linux 4.0 build](https://github.com/KhronosGroup/KTX-Software/releases/download/v4.0.0/KTX-Software-4.0.0-Linux.tar.bz2) with gltf-transform 0.12.7

```
gltf# gltf-transform --version
0.12.7
gltf# gltf-transform etc1s ./staging/input.glb ./staging/output.glb

error: Unable to find "toktx" version. Confirm KTX-Software is installed.

gltf# toktx --version
toktx v4.0
```

**To Reproduce**
on linux, install ktx-software 4.0
attempt to use gltf-transform etc1s <input> <output>

**Expected behavior**
gltf-transform converts the embedded image data via toktx.

**Versions:**
 - Version: v0.12.7
 - Environment: Node.js
 - ktx-software version: v4.0.0
 - os: Ubuntu 18.04.5 LTS

**Additional context**
The solution may be 'Wait for an actual fix from KTX-Software build pipeline', but hopefully this issue can save someone else some amount of time if they also see this error.

**Comment by donmccurdy** [comment]
Hm, I guess as long as the `toktx` command exists, we could just log a warning if the version can't be parsed and then continue to try encoding? It may be a while before I can get to a non-CLI implementation.

**Comment by donmccurdy** [comment]
Merging into https://github.com/donmccurdy/glTF-Transform/issues/358.
