### ISSUE TITLE
Writing Accessors Min/Max null

### ISSUE THREAD

**Issue by pixlhero** [donmccurdy/glTF-Transform#32]
When reading the attatched lamp.gltf file and then writing it, some accessors' min and max arrays will have null values. (This prevents the next tool in our pipeline to convert it to usdz). We know that the original .gltf file has some issues, but we would expect that upon successful reading of the file that it would also write a correct file.

[lamp.zip](https://github.com/donmccurdy/glTF-Transform/files/4650188/lamp.zip)

<pre>
const io = new NodeIO(fs, path);  
var doc = io.read("lamp/lamp.gltf");  
io.write("lamp/lampOut.gltf", doc);
</pre>

gltf-transform/core version: 0.3.2

**Comment by donmccurdy** [comment]
Hi — Thanks for reporting the issue. 

With the code you've provided above, the tool is going to overwrite the `lamp.bin` file and the texture from the original model. The texture wouldn't be affected by overwriting, but the `.bin` would, and It looks like the original `.bin` file is not included in the ZIP as a result.

Are you able to share the original file without the generated output?

**Comment by pixlhero** [comment]
Yes, of course. Thanks a lot for your fast response.
[lampData.zip](https://github.com/donmccurdy/glTF-Transform/files/4655734/lampData.zip)

**Comment by donmccurdy** [comment]
This is fixed in v0.3.3. It should compute min/max ignoring any corrupt values present in the accessor arrays. However, note that this tool does not correct the underlying accessor data, which will persist from the original file.
