### ISSUE TITLE
Reduce accessor min/max size in JSON

### ISSUE THREAD

**Issue by donmccurdy** [donmccurdy/glTF-Transform#325]
Current output includes min/max for every accessor, and writes them with high precision:

```
      "max": [
        0.9957213401794434,
        0.9957212805747986,
        0.9957213401794434
      ],
      "min": [
        9.9999988758398e-13,
        9.9999988758398e-13,
        9.9999988758398e-13
      ],
```

This takes up more space than necessary in the JSON output. We could omit min/max for many accessor types, and truncate precision somewhat where we do include it.

**Comment by lexaknyazev** [comment]
If these boundaries are taken from the actual `float32` values stored in binary buffers, any truncation would be flagged by the validator.

On the other hand, if some of these boundaries are taken from an intermediate computation result, then they could be safely truncated to `float32` with `Math.fround()`.

**Comment by donmccurdy** [comment]
The boundaries are taken from the actual float32 values, yes. Is there any harm in the scientific notation above?

The added file size appears to be coming from writing min/max on _every_ accessor, and not so much from the length of the min/max values — which will be integers anyway if the user is taking advantage of quantization or meshopt compression to reduce size. So I think i will just leave min/max un-truncated, but include them only conditionally: https://github.com/donmccurdy/glTF-Transform/pull/326

**Comment by lexaknyazev** [comment]
There's no harm in using the scientific notation. However, there's a trick there: it may be possible to find a shorter `float64` value that is equal to the stored `float32` value after truncation. For example:
```js
Math.fround(9.999999e-13) === 9.9999988758398e-13; // true
```
