### ISSUE TITLE
Root extras missing in output

### ISSUE THREAD

**Issue by pavle-goloskokovic** [donmccurdy/glTF-Transform#338]
**Describe the bug**

Extras set on root node are not saved in the output.

**To Reproduce**
```javascript

const document = new Document();

const root = document.getRoot();

root.setExtras({foo: 1, bar: 2});

/* ... */

io.write('./foo/bar.gltf', document);

```
**Expected behavior**
Extras data is saved as json property.

**Versions:**
 - Version: 0.12.9
 - Environment: Node.js

**Comment by donmccurdy** [comment]
Thanks! Will be fixed on next release by https://github.com/donmccurdy/glTF-Transform/pull/339.
