### ISSUE TITLE
Support extensions

### ISSUE THREAD

**Issue by gmarty** [donmccurdy/glTF-Transform#34]
Hey, I know support for extensions is in development in the `v0.4` branch but according to the comment, the only thing missing is documentation.

Can I start using this branch? Is there anything else I can do to help with it? 

I'm using glTF-Transform to extract the 3D models from a proprietary format and I'd like to use the `KHR_materials_unlit` extension.

**Comment by donmccurdy** [comment]
I think the branch probably needs a fair bit more testing than I've given it at this point, but you can try installing from the alpha release if you'd like:

```
npm install --save @gltf-transform/core@0.4.0-alpha.1 gltf-transform/extensions@0.4.0-alpha.1
```

There's some documentation in #33 now. Let me know if you hit any issues! For KHR_materials_unlit, specifically, you'd do something like this:

```ts
import { Document } from '@gltf-transform/core';
import { MaterialsUnlit, Unlit } from '@gltf-transform/extensions';

const doc = new Document();

// Create a MaterialsUnlit Extension instance attached to the Document.
const unlitExtension = doc.createExtension(MaterialsUnlit)
  .setRequired(false);

// Attach an Unlit property to a new Material.
const unlit = unlitExtension.createUnlit();
doc.createMaterial('MyUnlitMaterial')
  .setExtension(Unlit, unlit);
```

**Comment by donmccurdy** [comment]
v0.4 is available now, and includes `KHR_materials_unlit`. 🙂
