### ISSUE TITLE
Failing quantization in some cases

### ISSUE THREAD

**Issue by donmccurdy** [donmccurdy/glTF-Transform#352]
Running `quantize()` (and therefore, using `EXT_meshopt_compression`) currently breaks the model below:

[facecap.glb.zip](https://github.com/donmccurdy/glTF-Transform/files/7145241/facecap.glb.zip)

Looks like quantization scale isn't being applied consistently to the skinned and non-skinned parts? I'd tested that previously with the Shift Happens Canyon scene, which worked, so it would be important to check that the fix here doesn't cause regressions there. The unit tests for rescaling skin IBMs are a bit opaque.

**Comment by donmccurdy** [comment]
Thanks @somepablo! I'm taking a look at this model now. The `ACCESSOR_WEIGHTS_NON_NORMALIZED` error is not causing the scale difference, but is important and should be fixed by https://github.com/donmccurdy/glTF-Transform/pull/370. 

I'm seeing a baseline shift, but not a scale change, after quantization – the model is roughly centered at the origin before quantization, and sits on top of the Y=0 plane after quantization, which is a bug. I'm not seeing a change in the scale when skinning transforms are considered, though — note that the vertex values will change during quantization, but the inverse bind matrices will be updated to account for that. Common ways of calculating the scene's bounding box may or may not consider the skinning IBMs.

**Comment by somepablo** [comment]
Hi @donmccurdy, you are totally right, it was not a scale change, it was a shift (perspective betrayed me).

After testing it in several editors, I'm not sure this is a bug anymore. It's probably some issue with Three.js not considering the skinning IBMs:

- Blender: There is not any difference between quantized and non-quantized model
- Your gltf viewer (three r131): There is vertical shift between quantized and non-quantized (did not check how you are centering the model)
- Threejs online editor (three r133): There is a shift between model and its bbox for the quantized model.

So, if your visor is centering the model according to the bbox, that could explain that behaviour.

PS: Thanks for your quick fix on `ACCESSOR_WEIGHTS_NON_NORMALIZED`

**Comment by donmccurdy** [comment]
Ah that sounds like the difference yes. My viewer relies on three.js `THREE.Box3.setFromObject(...)` to center the model, which will not account for IBMs, so that explains the baseline shift. Have been meaning to fix that at some point but it's another issue.

I think the rest of the issue here will be fixed by https://github.com/donmccurdy/glTF-Transform/pull/371 — wasn't dealing with the animation channels correctly when applying quantization to meshes on an animated node.
