### ISSUE TITLE
Support keeping unused element in GLB

### ISSUE THREAD

**Issue by simonihmig** [donmccurdy/glTF-Transform#353]
**Is your feature request related to a problem? Please describe.**

I am trying to create a material-only GLB (related: https://github.com/KhronosGroup/glTF/issues/1420). I managed to use this library to basically remove everything from an existing glTF except textures and materials (see example below). 

When saving this as a .gltf, everything seems fine. The glTF validator passes (however shows a warning that the material seems unused, which is expected).

However when saving as a .glb, the file is way too small, and shows that only the json is contained, but the textures are not.

**Describe the solution you'd like**
It *seems* to be the issue is that the material is unused. But this is expected in my case. So either the glb export should not drop unused elements, or support an option to not do so.

[gltf-pipeline](https://github.com/CesiumGS/gltf-pipeline) shows the same behaviour, but it has a flag `--keepUnusedElements` to opt into that mode I am proposing here. (it seems to have some other bug, when `buffer` and `bufferViews` are not present. But after tweaking the gltf manually, the converted material-only glb seems fine!)

**Describe alternatives you've considered**

**Additional context**

This is the .gltf I get from `gltf-transform` (after removing everything except materials and textures), which as said above seems valid, and references the external images:

```json
{
  "asset": {
    "generator": "glTF-Transform v0.12.11",
    "version": "2.0"
  },
  "bufferViews": [],
  "buffers": [],
  "samplers": [
    {
      "magFilter": 9729,
      "minFilter": 9985,
      "wrapS": 10497,
      "wrapT": 10497
    }
  ],
  "textures": [
    {
      "source": 0,
      "sampler": 0
    },
    {
      "source": 2,
      "sampler": 0
    },
    {
      "source": 1,
      "sampler": 0
    }
  ],
  "images": [
    {
      "mimeType": "image/png",
      "uri": "Mahagoni-processed_1.png"
    },
    {
      "mimeType": "image/png",
      "uri": "Mahagoni-processed_2.png"
    },
    {
      "mimeType": "image/png",
      "uri": "Mahagoni-processed_3.png"
    }
  ],
  "materials": [
    {
      "name": "DefaultMaterial",
      "pbrMetallicRoughness": {
        "baseColorTexture": {
          "index": 0
        },
        "metallicRoughnessTexture": {
          "index": 2
        }
      },
      "normalTexture": {
        "index": 1
      },
      "occlusionTexture": {
        "index": 2
      }
    }
  ]
}
```

This is the extracted JSON part of the equivalent .glb:

```json
{"asset":{"generator":"glTF-Transform v0.12.11","version":"2.0"},"bufferViews":[{"buffer":0,"byteOffset":-1,"byteLength":1009676},{"buffer":0,"byteOffset":-1,"byteLength":5356},{"buffer":0,"byteOffset":-1,"byteLength":1572809}],"samplers":[{"magFilter":9729,"minFilter":9985,"wrapS":10497,"wrapT":10497}],"textures":[{"source":0,"sampler":0},{"source":2,"sampler":0},{"source":1,"sampler":0}],"images":[{"mimeType":"image/png","bufferView":0},{"mimeType":"image/png","bufferView":1},{"mimeType":"image/png","bufferView":2}],"materials":[{"name":"DefaultMaterial","pbrMetallicRoughness":{"baseColorTexture":{"index":0},"metallicRoughnessTexture":{"index":2}},"normalTexture":{"index":1},"occlusionTexture":{"index":2}}]}
```

After the json, there is nothing more in the file. So AFAICT the referenced buffers don't even exist!

**Comment by donmccurdy** [comment]
Hm, this seems like a bug — gltf-transform shouldn't be removing unused resources at all, unless instructed to (e.g. with the `prune` [function](https://gltf-transform.donmccurdy.com/functions.html#prune) or CLI command). Maybe it is failing to write the buffer if there's no geometry (and only images) to put in that buffer.

I'll look into fixing that and adding a unit test for this case.

**Comment by donmccurdy** [comment]
@simonihmig possibly a quick workaround – in https://github.com/kaliber5/gltf-toolbox/pull/1 linked above, all buffers are being destroyed. If you leave at least one buffer (or dispose of the existing ones and then create another with `doc.createBuffer()`) the export should work – could you confirm that?

But glTF-Transform should at least warn about this, rather than silently writing an invalid file, so let's keep this open in any case.

**Comment by simonihmig** [comment]
> If you leave at least one buffer (or dispose of the existing ones and then create another with doc.createBuffer()) the export should work – could you confirm that?

Confirmed, that workraround (https://github.com/kaliber5/gltf-toolbox/pull/2) works perfectly! 

Thanks for your super quick and helpful support here! 🙏

**Comment by donmccurdy** [comment]
Glad to hear! Will have a better error message (instead of silent invalid output) after next version is released with https://github.com/donmccurdy/glTF-Transform/pull/354.
