### ISSUE TITLE
WebIO.read still attempts to fetch embedded resources

### ISSUE THREAD

**Issue by Someoneamzing** [donmccurdy/glTF-Transform#359]
**Describe the bug**

WebIO.read will attempt to fetch the uuid variants of the data URI resources that are embedded in the glTF/glb file, resulting in redundant network requests and multiple console errors complaining of non-existent files.

**To Reproduce**
1. Obtain a glTF file with embedded resources, (e.g. [NormalTangentMirrorTest.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/blob/7df889bfe844453bf961e3b92dc7d642cd33978d/2.0/NormalTangentMirrorTest/glTF-Embedded/NormalTangentMirrorTest.gltf))
2. Run WebIO.read on the file:
```js
import {WebIO} from '@gltf-transformer/core';
const document = await new WebIO().read('NormalTangentMirrorTest.gltf');
```
3. Console will display errors about missing files.

**Expected behavior**

I expected the embedded files to be skipped during the fetch phase.

**Versions:**
 - Version: v0.12.12
 - Environment: Browser

**Additional context**

I've noticed the embedded data still gets loaded in the internal step inside `platform-io.ts` , but after the uuid renaming of the URI, it continues to try and fetch this uuid URI in `web-io.ts` as there are no checks to verify if the image was already loaded.

**Comment by donmccurdy** [comment]
Thanks @Someoneamzing! This should be fixed by https://github.com/donmccurdy/glTF-Transform/pull/360.
