### ISSUE TITLE
Texture compression of normal map causes bad aliasing

### ISSUE THREAD

**Issue by mikejurka** [donmccurdy/glTF-Transform#388]
**Describe the bug**
On one model (BoomBox.glb), texture compression of the model causes lots of aliasing at the edges of surfaces.
Compressed:
<img width="638" alt="Screen Shot 2021-10-18 at 8 12 42 PM" src="https://user-images.githubusercontent.com/440407/137837674-6fa44aae-f601-40c1-befd-df2dcdeda01f.png">
Uncompressed:
<img width="754" alt="Screen Shot 2021-10-18 at 8 13 02 PM" src="https://user-images.githubusercontent.com/440407/137837705-11548e8c-66b7-41e5-a876-f36c198928cc.png">

**To Reproduce**
1. Download BoomBox.glb from https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/BoomBox/glTF-Binary/BoomBox.glb
2. Run `gltf-transform`:
```
gltf-transform etc1s ~/Downloads/BoomBox.glb  ~/Downloads/BoomBox.compressed.glb
```
3. Observe the resulting model in https://gltf.report/

**Expected behavior**

I expect there to not be such bad aliasing in the compressed model. Notably, when I modified the code of gltf-transform so that compression of the normal map was skipped, it looked much more like the original!

**Versions:**
 - Version: v0.12.16
 - Environment: node v14.18.1 on mac

**Additional context**
Notably, when I modified the code of gltf-transform so that compression of the normal map was skipped, it looked much more like the original!

**Comment by donmccurdy** [comment]
Agreed, a warning might be a good idea. Probably for `normalTexture` but not for the O/R/M textures (which are sometimes fine with ETC1S). If you want to add the warning in https://github.com/donmccurdy/glTF-Transform/pull/389 feel free, otherwise I can try to put it in later. :)
