### ISSUE TITLE
Support exporting embedded .gltf

### ISSUE THREAD

**Issue by marcofugaro** [donmccurdy/glTF-Transform#397]
**Is your feature request related to a problem? Please describe.**

Currently (using WebIO in my case), you can use the `writeBinary` function to export as .glb, and the `writeJSON` function to export as .gltf with external resources.

It would be useful to have also the ".gltf embedded" option like blender does:

<img src="https://user-images.githubusercontent.com/7217420/138709611-3a6c5e7f-b652-4438-a37d-f3abcb667dce.png" width="300" />

In my usecase, I need the json to be stored in another json file.

**Describe the solution you'd like**
A function like `writeJSONEmbedded` or something that returns just the json object with the resources embedded in base64 in the object.

**Describe alternatives you've considered**
Doing it myself (geometry only in this case):
```js
const encodedBuffer = base64js.fromByteArray(new Uint8Array(resources['.bin']));
gltfCompressed.buffers[0].uri = `data:application/octet-stream;base64,${encodedBuffer}`;
```

**Comment by tmarti** [comment]
Cannot avoid to share this here @donmccurdy 😇

I lost 30 minutes doing and trying this, so adding here as a hint that can be helpul to others 🙂 

```js
function _arrayBufferToBase64(buffer)
{
    var binary = '';
    var bytes = new Uint8Array(buffer);
    var len = bytes.byteLength;
    for (var i = 0; i < len; i++)
    {
        binary += String.fromCharCode(bytes[i]);
    }
    return btoa.default(binary);
}

const document = new Document();

// .... fill the document

const nodeIO = new NodeIO();
const jsonDocument = nodeIO.writeJSON(document);

var jsonString = JSON.stringify(jsonDocument.json, null, 4);

Object.keys(jsonDocument.resources).forEach(resourceKey =>
{
    jsonString = jsonString.replace(
        '"uri": "' + resourceKey + '"',
        '"uri": "data:application/octet-stream;base64,' + _arrayBufferToBase64(jsonDocument.resources[resourceKey]) + '"'
    )
});

// enjoy the embedded resouces in your JSON
```
