### ISSUE TITLE
Set up 'Prettier' code formatting

### ISSUE THREAD

**Issue by donmccurdy** [donmccurdy/glTF-Transform#408]
I think this repository would benefit from having automatic code formatting, probably with Prettier (https://prettier.io/). Ideally configured for similar code style to what's currently here but doesn't have to be a perfect match.

**Comment by MrMagicPenguin** [comment]
If no one else is interested, i'd be happy to take this up!

**Comment by donmccurdy** [comment]
Looks like Prettier [doesn't have that many options](https://prettier.io/docs/en/options.html#bracket-spacing) so this is going to cause a lot of layout changes when it lands... that's OK but it might be best if I go ahead and do it so we don't need to do code reviews on 100+ file changes. 😁

**Comment by MrMagicPenguin** [comment]
No worries!! After playinf with Prettier and ESLint in my own project I am frankly a bit intimidated by the configuration and issues that arose.. best of luck!
