### ISSUE TITLE
[CLI] meshopt compression breaks UV coordinates

### ISSUE THREAD

**Issue by hybridherbst** [donmccurdy/glTF-Transform#414]
**Describe the bug**
UV coordinates seem to break in some cases when applying meshopt compression.

**To Reproduce**

1. Download the attached file [MultipleUVRanges.zip](https://github.com/donmccurdy/glTF-Transform/files/7477635/MultipleUVRanges.zip)
2. Run ```gltf-transform meshopt MultipleUVRanges.glb MultipleUVRanges.meshopt.glb```
3. Open the file e.g. in https://sandbox.babylonjs.com/ (doesn't load in gltf.report)
4. Note distorted UV coordinates on output file
![WRYJMRK14U](https://user-images.githubusercontent.com/2693840/140405817-85f21e01-1e73-4f5f-ae6c-49696e265d60.png)

**Expected behavior**
Output file looks the same as input file
![chrome_ZiTdOLGFe9](https://user-images.githubusercontent.com/2693840/140405802-0551bf56-68be-4dde-b420-982cd56b4a28.png)

**Versions:**
 - Version: 1.0.1
 - Environment: nodejs

**Notes**
- doesn't seem to happen when running ```gltfpack -c``` or ```-cc``` on the same file

**Comment by donmccurdy** [comment]
Likely the same as https://github.com/donmccurdy/glTF-Transform/issues/403, but I'm glad for the extra test case thanks! It seems like the issue shows up when using `--level high` (similar to `-cc` in meshopt) but not `--level medium` (similar to `-c`).

**Comment by donmccurdy** [comment]
Just curious, what are the "Multiple UV ranges" referred to by the title?

**Comment by donmccurdy** [comment]
> I thought it may be because of those UV ranges (and gltf-transform logging that UVs out of [0..1] range are skipped) but seems I'll have to hunt some more...

The error doesn't show up when using just the `quantize` command (which is always a pre-process step when doing meshopt) so those warnings shouldn't be the issue. I think given that the error only shows up with the higher meshopt compression setting, I may be using one of the meshopt compression filters incorrectly here. I'll take a look!

**Comment by donmccurdy** [comment]
Merging details from #403 —

***


Testing [War Plane (Sketchfab)](https://sketchfab.com/3d-models/war-plane-b487f1128b984da8ae8cd9ce0a02d9ba) on https://gltf.report, the model looks OK when exported normally, or when quantized, but enabling Meshopt compression results in broken UVs. Test on CLI as well, which has the same error.

![Screen Shot 2021-10-28 at 2 25 16 PM](https://user-images.githubusercontent.com/1848368/139337895-841c09a9-7bfd-4fc5-bc09-4c60401cdf1b.png)

Original:

[WarPlane-v2.glb.zip](https://github.com/donmccurdy/glTF-Transform/files/7437404/WarPlane-v2.glb.zip)

**Comment by scurest** [comment]
(Talking about `MultipleUVRanges.glb` here.)

The problem is obviously that the TEXCOORD_0 acccessor is using buffer view 5, which has the wrong filter (`OCTAHEDRAL`, so it should be for normals).

Looking here

https://github.com/donmccurdy/glTF-Transform/blob/2b24c54e8c1631eda9f07c508ba15f413e81f45a/packages/extensions/src/ext-meshopt-compression/meshopt-compression.ts#L293

`filter` always stringifies as `"[object Object]"`, so effectively the filter is missing from the key. My guess is that's why the buffer views are colliding. The TEXCOORDs on the other quads don't collide because they differ in the byteStride as well as the filter (since they don't get quantized I guess).

Using `filter.filter` in the key fixes this case for me.

**Comment by donmccurdy** [comment]
Thanks @scurest! That change fixed both of the cases above. I was looking wayyyy down the wrong trail on this issue. 😅

**Comment by hybridherbst** [comment]
Found another failure case on 1.2.1 @donmccurdy in case you want to verify that the solution fixes that as well:
[ThorSerpent.zip](https://github.com/donmccurdy/glTF-Transform/files/7643774/ThorSerpent.zip)

(it actually produces quite an interesting pattern design for this model!)
![image](https://user-images.githubusercontent.com/2693840/144468440-98792961-08e2-4ed9-964d-248890d68e54.png)

**Comment by donmccurdy** [comment]
Thanks @hybridherbst! Confirmed that model is fixed as well – and just published the fix as v1.2.2.
