### ISSUE TITLE
Asynchronous NodeIO read and write methods

### ISSUE THREAD

**Issue by ukito-pl** [donmccurdy/glTF-Transform#440]
**Is your feature request related to a problem? Please describe.**
Problems may occur when working with big gltf models, more than 100MB. In those cases writing and saving models blocks all IO related functionality that may be working in the program for a significant amount of time.

**Describe the solution you'd like**
Either change existing NodeIO.read and NodeIO.write functions to be asynchronous (but it would be a breaking change) or create new methods NodeIO.readAsync and NodeIO.writeAsync.

**Describe alternatives you've considered**
\-

**Additional context**
\-

**Comment by donmccurdy** [comment]
Hi, thanks for opening this issue! It might be best to move toward async methods in NodeIO, similar to WebIO. In addition to supporting large models better, this seems like something users would want when using NodeIO in a server or serverless environment.

In the next month or two I'm hoping to make a v2.0 release, which would be a good opportunity to do breaking changes to the API where necessary. Would you be able to have a look at https://github.com/donmccurdy/glTF-Transform/pull/441 and see if it works for your needs?
