### ISSUE TITLE
Client-side DracoMeshCompression not working?

### ISSUE THREAD

**Issue by pio-esg** [donmccurdy/glTF-Transform#473]
**Describe the bug**
Client-side Draco Compression not working. GLB output is not compressed (same size with not compressing)

**To Reproduce**
I basically followed the steps [here](https://github.com/mrdoob/three.js/pull/22227#issuecomment-897310955) 

```
  compressScene = async (scene) => {
    let _this = this;
    const io = new WebIO()
      .registerExtensions(KHRONOS_EXTENSIONS)
      .registerDependencies({
        "draco3d.encoder": await new window.DracoEncoderModule(),
        "draco3d.decoder": await new window.DracoDecoderModule(),
      });

    new GLTFExporter().parse(
      scene,
      function (glb) {
        const document = io.readBinary(glb);

        document
          .createExtension(DracoMeshCompression)
          .setRequired(true)
          .setEncoderOptions({
            method: DracoMeshCompression.EncoderMethod.EDGEBREAKER,
            encodeSpeed: 5,
            decodeSpeed: 5,
          });

        const compressedGLB = io.writeBinary(document);
        _this.downloadBLOB(
          new Blob([compressedGLB], { type: "application/octet-stream" }),
          "result.glb"
        );
      },
      { binary: true }
    );
  };
```

**Expected behavior**
The file size should somehow decrease like result of gltf-pipeline.

**Versions:**
 - Version: Draco 1.4.3
 - Environment: React

**Additional context**
Sorry if I'm doing something wrong

**Comment by donmccurdy** [comment]
Hi! Could you share the input file, along with the complete and runnable code involved?  Have you confirmed that gltf-pipeline also compresses the specific file you're testing here? 

I've implemented client-side draco compression in https://gltf.report/ using this tool and that does work, but if there's something particular to your setup causing the bug I will need more details (beyond the sample code) to reproduce that.

**Comment by pio-esg** [comment]
Hi Don. Thanks to your hint, I tried preparing a minimum code sample. In there, I tried to compress my GLB and found that the logger is enabled, showing multiple "Skipping Draco compression on non-indexed primitive" messages. [This](https://github.com/donmccurdy/glTF-Transform/discussions/394) discussion was helpful to get the compression working. It now works in the large codebase I'm dealing with.

Btw, Is there a way to enable the logger by force?

Thanks so much for this awesome lib.

**Comment by donmccurdy** [comment]
Glad to hear! 

The logger should be enabled by default for warnings and errors like this, so I'm not sure why its output wouldn't have appeared before sorry. You can increase its verbosity by making a new [logger](https://gltf-transform.donmccurdy.com/classes/core.logger.html) instance and calling `document.setLogger( logger )`, but that just adds debug output, and the warning above would be printed with or without debug verbosity enabled.
