### ISSUE TITLE
Writing gltf with remote assets while using setAllowHttp() throws no such file or directory error

### ISSUE THREAD

**Issue by oddnugget** [donmccurdy/glTF-Transform#474]
**Describe the bug**
Writing a gltf to disc that has remote assets causes `ENOENT: no such file or directory` error. 

**To Reproduce**
1. Get url to a gltf that has remote assets. 
2. Create instance of NodeIO, provide it a fetch implementation and call `setAllowHttp(true)`
3. Read the gltf using the url and then write it to the disc as bellow: 
 ```js
 const doc = await io.read(url);
 await io.write('output.gltf', doc);
 ```

**Expected behavior**
The library writes the gltf to disc while preserving the remote asset urls.  

**Versions:**
 - Version: 2.0.0-alpha-5
 - Environment: NodeJS (NodeIO)

**Additional context**
This relates to #466 and #462.

**Comment by daniel-gato** [comment]
Same issue here?

**Comment by donmccurdy** [comment]
A fix has been published to the `@next` tag.
