### ISSUE TITLE
Possibly memory leak on TextureResize

### ISSUE THREAD

**Issue by VrTech** [donmccurdy/glTF-Transform#478]
**Describe the bug**
After running a command 

```
  await doc.transform(
    textureResize({ size: [128, 128], filter: TextureResizeFilter.LANCZOS2 }),
  );
```

I notice that the memory goes up and never comes back down.

**To Reproduce**
```
async function compress(glbFile) {
  await MeshoptDecoder.ready;
  await MeshoptEncoder.ready;

  //Low Definition
  let compress = io.readBinary(glbFile);

  await compress.transform(
    textureResize({ size: [128, 128], filter: TextureResizeFilter.LANCZOS2 }),
    prune(),
    dedup(),
    reorder({ encoder: MeshoptEncoder }),
    quantize({ pattern: /^(POSITION|TEXCOORD|JOINTS|WEIGHTS)(_\d+)?$/ })
  );

  compress.createExtension(MeshoptCompression)
    .setRequired(true)
    .setEncoderOptions({ method: MeshoptCompression.EncoderMethod.FILTER });

  return await io.writeBinary(compress);
}
```

**Expected behavior**
RAM and memories returns back to normal

**Versions:**
- Version 1.2.4
-  Nodejs

**Comment by donmccurdy** [comment]
Hi @VrTech! Thanks for reporting the issue. Unfortunately, if there is a memory leak in the texture processing it is likely to be somewhere deeper in this dependency stack:

- `@gltf-transform/functions`
    - `ndarray-pixels`
        - `get-pixels`
            - `jpeg-js`
            - `pngjs`
            - `node-bitmap`
        - `save-pixels`
            - `jpeg-js`
            - `pngjs-nozlib`

Note that some of those dependencies would depend on the image format you're using, and perhaps other factors. Is it possible to share more information about:

- Are you measuring memory usage with `process.memoryUsage().heapUsed`, or some other way?
- What format (PNG, JPEG, etc.) are the images? What resolution?
- Could you share one or more model(s) to reproduce the issue?

**Comment by VrTech** [comment]
Hi @donmccurdy,

Here is what I've done so far.
- I'm using process.memoryUsage() to assess the leakage.
- Most of the formats are PNG with 4K resolution
- The test model is from [Here](https://sketchfab.com/3d-models/space-age-radio-a3c888aed8424954b8e93980cd107fc6) but I converted it to GLB via Blender in order to test the texture resize.

The issue is more obvious when using with a large texture size of a model

**Comment by donmccurdy** [comment]
Thanks! I'm testing the same model and a few others with this script:

```js
// node --expose-gc test.js

const { NodeIO } = require('@gltf-transform/core');
const { textureResize, TextureResizeFilter } = require('@gltf-transform/functions');

const MODEL_PATH = 'path/to/scene.gltf';

let tickCount = 1;
const tick = () => console.log(`mem#${tickCount++}: ${(process.memoryUsage().heapUsed / 1000000).toFixed(2)} MB`);

async function main() {

	tick();

	const io = new NodeIO();
	const document = await io.read(MODEL_PATH);

	tick();

	for (let i = 0; i < 5; i++) {

		const size = 2048 / Math.pow(2, i);
		console.log(`textureResize(size=${size})`);

		await document.transform(
			textureResize({
				size: [size, size],
				filter: TextureResizeFilter.LANCZOS2
			})
		);

		tick();

	}

	// Requires `--expose-gc` flag
	if (global.gc) {
		console.log('gc()');
		global.gc();
	}

	tick();

}

main();
```

... the Sketchfab asset reported roughly flat memory in these tests, but a few showed more change over time like this:

```
mem#1: 13.71 MB
mem#2: 9.73 MB
textureResize(size=2048)
mem#3: 9.78 MB
textureResize(size=1024)
mem#4: 31.70 MB
textureResize(size=512)
mem#5: 48.74 MB
textureResize(size=256)
mem#6: 39.86 MB
textureResize(size=128)
mem#7: 30.82 MB
gc()
mem#8: 10.12 MB
```

I don't know how Node.js / V8 garbage collection works in detail, but it appears to be working incrementally and (eventually) does clean things up.

That said, Sharp is definitely a faster and more efficient library for resizing images in Node.js! If you want to run this online in a performance-sensitive environment, that's probably a better choice. I haven't included it out of the box because (1) I need the library to support the Web as well, and (2) I rely on `ndarray-pixels` for some other image processing operations, like spec/gloss metal/rough conversion.
