### ISSUE TITLE
Animation compression gets worse over time when using meshopt

### ISSUE THREAD

**Issue by hybridherbst** [donmccurdy/glTF-Transform#489]
**Describe the bug**
It seems that gltf-transform meshopt currently has "medium" and "high" presets, but it looks like in both these presets animations degrade more the longer the animation time is (keyframes that are later in time compress worse).

**To Reproduce**
1. Download [AnimatedArm.zip](https://github.com/donmccurdy/glTF-Transform/files/8023253/AnimatedArm.zip)
2. This contains Arm.glb, Arm.meshopt-medium.glb and Arm.meshopt-high.glb
2. The effect is barely visible on medium but very visible on high; it seems that the further to the back of an animation the values are, the worse the compression ends up being.

**Expected behavior**
My understanding is that the error/lossy compression should be uniformly distributed and not worse to the "back" of the animation, but I might be mistaken in my meshopt animation compression understanding...

**Additional context**
Babylon Sandbox works good for viewing the files as it has a timeline slider (https://sandbox.babylonjs.com/).

The files are also good stress test files for https://gltf.report by the way, opening the "Validate" view crashes Chrome (out of memory) 👀

**EDIT:** I'm not sure if this is the same or a separate issue, but `Arm.meshopt-high.glb` also isn't valid anymore since it contains duplicate time values (ACCESSOR_ANIMATION_INPUT_NON_INCREASING), and, a lot of them, which is what I think is crashing gltf.report.

**Comment by hybridherbst** [comment]
When looking at the imported animation it seems that indeed the time itself is nonlinearly packed (time resolution becomes lower over time) which I think might be a bug:
![image](https://user-images.githubusercontent.com/2693840/152983588-00a23f1e-07b6-4ec6-936f-296de975a482.png)

**Comment by donmccurdy** [comment]
Animation times and values can use different filter methods, but the other two filter types aren't appropriate for time. So if exponential doesn't work here I'd just need to disable the filters on animation times probably.
