### ISSUE TITLE
Meshopt compression alters bounds of skinned meshes in some cases

### ISSUE THREAD

**Issue by hybridherbst** [donmccurdy/glTF-Transform#490]
**Describe the bug**
It seems that in some cases `gltf-transform meshopt` alters bounds of skinned meshes and results in files with either incorrect scale or incorrect bounds (haven't been able to verify which it actually is so far).

**To Reproduce**
1. Download and unpack [BentCylinder-Meshopt.zip](https://github.com/donmccurdy/glTF-Transform/files/8026583/BentCylinder-Meshopt.zip)
2. Drop "BentCylinder.glb" into https://gltf-viewer.donmccurdy.com/
3. Now drop "BentCylinder.meshopt.glb" into it
4. Note that the second file displays very differently, the only difference is that it was processed with gltf-transform meshopt.

_Without meshopt_
![image](https://user-images.githubusercontent.com/2693840/153055054-82ac12c8-23c9-432b-a787-4ca7c2fa6304.png)

_With meshopt_
![image](https://user-images.githubusercontent.com/2693840/153055115-532ce7b7-274f-40d5-ba11-b18c4a649a28.png)

**Expected behavior**
Files display the same.
This might also be an issue with bounds calculations inside modelviewer/gltf-viewer instead of gltf-transform (there's known issues with skinned meshes in model-viewer bounds calculations at least, see here: https://github.com/google/model-viewer/issues/3189), but since in this case the only difference is meshopt compression might be a separate problem (and/or the model scale is incorrectly calculated in model-viewer).

**Comment by donmccurdy** [comment]
I think it's the issue you mention in model-viewer, as well as https://github.com/donmccurdy/three-gltf-viewer/issues/147 - quantization (which can be applied independently of meshopt) applies a scale to skin IBMs to cancel out changes to the vertex values. This keeps the same scene bounding box, but causes both viewers to compute the bounding box incorrectly.

**Comment by hybridherbst** [comment]
Understood - added some more info (and an implementation by Mugen where I'm not sure if it ever made its way into the threejs core) to the model-viewer issue.
