### ISSUE TITLE
Broken texture after etc1s conversion

### ISSUE THREAD

**Issue by hybridherbst** [donmccurdy/glTF-Transform#502]
**Describe the bug**
The attached model runs through gltf-transform etc1s without error, but the resulting texture is 8x0 pixels and can't be loaded anymore (throws exception in gltf.report and elsewhere).

**To Reproduce**
1. Download [TexturedCube.zip](https://github.com/donmccurdy/glTF-Transform/files/8090577/TexturedCube.zip)
2. Run `gltf-transform etc1s TexturedCube.glb TexturedCube.etc1s.glb`
3. Open the result in gltf.report

**Expected behavior**
Has same appearance as original file, does not throw exception.
Alternative: gltf-transform should log an error if this file can't be processed for some reason (but generally I think "everything should pass" in the sense of a pipeline tool/step).

**Additional context**
The error logged is 
```
Error: THREE.KTX2Loader:	Invalid texture
    at a816abbe-5888-4dab-9200-d3bd76c69d3a:29:1367
    at a816abbe-5888-4dab-9200-d3bd76c69d3a:29:1887
(anonymous) @ a816abbe-5888-4dab-9200-d3bd76c69d3a:29
bundle.js:2 THREE.GLTFLoader: Couldn't load texture blob:https://gltf.report/7406afd6-8a1b-48ad-88ed-fba2ea534bf9
```

**Comment by donmccurdy** [comment]
To be fixed in https://github.com/donmccurdy/glTF-Transform/pull/504.
