### ISSUE TITLE
Compressing texture with uastc logs KTX error that might be misleading

### ISSUE THREAD

**Issue by hybridherbst** [donmccurdy/glTF-Transform#503]
**Describe the bug**
The same file as for #502 logs an error "Zstd deflation failed; KTX error: Out of memory" when attempting to compress with uastc.
This seems to be incorrect or misleading, as the file is tiny (or it's a bug in toktx maybe?).

**To Reproduce**
1. Download https://github.com/donmccurdy/glTF-Transform/files/8090577/TexturedCube.zip
2. Run `gltf-transform uastc TexturedCube.glb TexturedCube.uastc.glb`
3. Observe exception with (I think) misleading error message

**Expected behavior**
Either better error message or the file should pass and compress properly.

**Additional context**
![image](https://user-images.githubusercontent.com/2693840/154531291-cff9e5e4-3170-4efb-a0ed-bf0c8130f650.png)

**Comment by donmccurdy** [comment]
Verbose output:

```
gltf-transform uastc ~/Desktop/TexturedCube.glb ~/Desktop/TexturedCube.uastc.glb --verbose
debug: Found KTX-Software v4.0.0.
debug: Texture 1/1 (baseColorTexture)
debug: • toktx --genmipmap --uastc 2 --zcmp 18 /var/folders/n5/m5lw96654zn9mpq7lk351jbh0000gn/T/tmp-38216-8yePbD4FogiF-.ktx2 /var/folders/n5/m5lw96654zn9mpq7lk351jbh0000gn/T/tmp-38216-uuOJFUdUVzRj-.jpg

error: • Texture compression failed:

       toktx: Zstd deflation failed; KTX error: Out of memory.



error: Texture compression failed
```

I have a hunch the image needs to be resized 8x1 → 8x4 for UASTC compression, but not sure whether toktx should handle that automatically or if it requires glTF Transform to provide the `--resize` flag. Will investigate, thanks!

**Comment by donmccurdy** [comment]
The OOM error for UASTC will be fixed in KTX Software by https://github.com/KhronosGroup/KTX-Software/pull/527. The error reported with ETC1S appears to have a different cause.

In the meantime, resizing the texture to 12x12 or larger appears to work around the problem, but that value may be texture-specific. :/
