### ISSUE TITLE
One to many indices created when welding GL_Line primitives with zero tolerance

### ISSUE THREAD

**Issue by Rennzie** [donmccurdy/glTF-Transform#505]
**Describe the bug**
Welding a line primitive with a tolerance of zero creates one too many indices. The output below shows the resulting indices array and the input positions. 

```javascript
{
  mode: 1,
  indices: Uint16Array(3) [ 0, 1, 2 ],
  positions: Float32Array(6) [
    97247.71875,
    36549.90625,
    103.6875991821289,
    97247.875,
    36549.90625,
    103.6875991821289
  ],
}
```
**To Reproduce**
1. With any glb which has GL_Line draw mode
2. attempt to weld it using tolerance of zero
```javascript
await gltf.transform(weld({tolerance: 0}))
```
3. Print the resulting indices array and the position array

**Expected behavior**
Welding GL_Lines with a tolerance of zero creates one index per vertex.

**Versions:**
 - Version: `1.2.4`
 - Environment: Node 16

**Additional context**
I'm sorry I'm not able to raise a PR fix for this right now (time crunch on delivery) but this is the code I wrote (mostly borrowed from `weld`) to get around the issue. It deals specifically with indexing lines.

```typescript
export function indexLinePrimitives(doc: Document): void {
  for (const prim of getAllPrimitives(doc)) {
    if (prim.getIndices()) continue;

    if (!isLineMode(prim.getMode())) continue;

    const positions = getPositions(prim)!;
    const numVertices = positions.getCount();

    const indicesArray =
      numVertices <= 65534
        ? new Uint16Array(numVertices)
        : new Uint32Array(numVertices);

    const indices = doc
      .createAccessor()
      .setBuffer(positions.getBuffer())
      .setType(Accessor.Type.SCALAR)
      .setArray(indicesArray);

    // fill the indices
    for (let i = 0; i < numVertices; i += 1) indices.setScalar(i, i);

    prim.setIndices(indices);
  }
}
```

My suspicion is the issues come from how the size of the index array is calculated here https://github.com/donmccurdy/glTF-Transform/blob/a28537fb11081684e8e8260081b620c1069b5555/packages/functions/src/weld.ts#L44

**Comment by donmccurdy** [comment]
Thanks for the detailed report @Rennzie! You're right, it looks like the `--tolerance=0` code path only really considered triangle meshes. The default tolerance (or any non-zero custom tolerance) should work, based on a quick test.

There are a bunch of test models for different primitive draw modes in https://github.com/KhronosGroup/glTF-Asset-Generator/tree/master/Output/Positive/Mesh_PrimitiveMode, I should probably go through and test all of those against the weld/unweld operations at some point.

**Comment by Rennzie** [comment]
Yes I can confirm that any non-zero tolerance does the job as expected. If I get a chance at some point I'll try raise a PR, if you don't get to it first.

**Comment by donmccurdy** [comment]
Great to hear! I've got a PR on the way now, in #507.
