### ISSUE TITLE
Fail to read GLB using paths containing hash char '#'

### ISSUE THREAD

**Issue by timknip** [donmccurdy/glTF-Transform#510]
**Describe the bug**
Both cli and core fail to read from a path containing the hash char `#`

**To Reproduce**
1. create a directory named for example `BATCH#1` and add `foo.glb` to that directory
2. run `gltf-transform inspect BATCH#1\foo.glb` or `const io = new NodeIO(); await io.read('BATCH#1\\foo.glb')`
3. the command fails with `error: Unexpected token g in JSON at position 0`

**Expected behavior**
`gltf-transform inspect BATCH#1\foo.glb` should run without error

**Versions:**
 - Version: 2.0.0, 2.0.4, 2.0.5
 - Environment: Windows 10, node 14.15.1, 16.13.1, 17.0.0

**Additional context**
-  Oddly `gltf-transform validate BATCH#1\foo.glb`  runs without errors
-  Hunch: path is cut off at `#` perhaps due to the new 'url' stuff?
-  Using `1.2.4` all is good

**Comment by donmccurdy** [comment]
Thanks! You're right about the issue being related to the new support for HTTP requests in NodeIO. There are some tricky cases here, e.g. `path/to/texture.png#25.jpg` is a valid path for a PNG on the web, but also would be a valid path for a JPEG on disk. glTF Transform aims to work in both environments, but there are some weird edge cases like that. I believe #513 will fix the I/O issues you're seeing, but I would just be cautious about using paths that aren't "safe for URLs" *inside* a glTF file, particularly as a texture or .bin path.
