### ISSUE TITLE
MeshoptCompression  extension documentation example is missing parameter in the reorder transformer?

### ISSUE THREAD

**Issue by Rennzie** [donmccurdy/glTF-Transform#521]
**Describe the bug**

`MeshoptCompression`  extension documentation example is missing parameter in the `reorder` transformer. The function is called directly as `reorder()` but in the `reorder` documentation is says it needs to be called with an instance of `MeshoptEncoder` 

```typescript
reorder({encoder: MeshoptEncoder})
```

If I use the medium `MeshoptCompression` example code with out the `encoder` param, compression fails with: 

```bash
TypeError: Cannot read properties of undefined (reading 'ready')
    at transform (/workspaces/async-jobs/mesh-processing/glb2tiles/tiler/node_modules/@gltf-transform/functions/src/reorder.ts:52:17)
    at /workspaces/async-jobs/mesh-processing/glb2tiles/tiler/node_modules/@gltf-transform/core/src/document.ts:199:10
```

When I use the encoder as above, compressions works as expected. I'm not sure if this is missing documentation or something is actually wrong with my gltf?

**To Reproduce**
1. Add MeshoptCompression extension using the documentation example (medium)
2. Compress a gltf
3. Fails with above error message

**Expected behavior**
[Meshoptimiser](https://gltf-transform.donmccurdy.com/classes/extensions.meshoptcompression.html) documentation example should include the `encoder` param

```typescript
import {  MeshoptCompression } from '@gltf-transform/extensions';
import {quantize, reorder} from '@gltf-transform/functions';
import {MeshoptEncoder} from 'meshoptimizer';

// Write and encode. (Medium, -c)
await document.transform(reorder({encoder: MeshoptEncoder}), quantize());
document.createExtension(MeshoptCompression)
    .setRequired(true)
    .setEncoderOptions({ method: MeshoptCompression.EncoderMethod.QUANTIZE });
await io.write('compressed-medium.glb', document);
```

**Comment by donmccurdy** [comment]
Oh you're correct — it's a missing parameter in the documentation (and should probably fail with an explicit error when omitted).
