### ISSUE TITLE
`prune` doesn't remove unused attributes

### ISSUE THREAD

**Issue by hybridherbst** [donmccurdy/glTF-Transform#614]
**Describe the bug**
Maybe I'm not understanding the docs right, but it looks like unused accessor attributes should be removed by pruning. Basically my assumption was that whatever GLTF Validator warns as "unused" will be gone after running `gltf-transform prune` - is this wrong to assume? Is there another command that does that?

**To Reproduce**
1. Download & unzip [SphereUnusedAttributes.zip](https://github.com/donmccurdy/glTF-Transform/files/9077501/SphereUnusedAttributes.zip)
2. Drag file into https://github.khronos.org/glTF-Validator/, note unused tangents + uv0 + uv1
3. Run `gltf-transform prune SphereUnusedAttributes.glb SphereUnusedAttributes.pruned.glb`
4. Note it logs `info: prune: No unused properties found.`
2. Drag file into https://github.khronos.org/glTF-Validator/, note unused tangents + uv0 + uv1

**Expected behavior**
Unused tangents and texcoords are removed

**Versions:**
 - Version: 2.1.7
 - Environment: CLI

When using gltfpack, those are removed by default (don't think that's good):
```
gltfpack -i .\SphereUnusedAttributes.glb -o .\SphereUnusedAttributes.prune.glb
```
results in 0 warnings in the Validator.

**Comment by donmccurdy** [comment]
Hi! The `prune()` function is not specifically designed to deal with validation warnings — these are all reasonable feature ideas for improving the function, but I'm not aiming for parity with the validator. Most of the focus is on removing resources that are literally not referenced at all, like loose accessors and textures in the file. More specifically, the stuff implemented here:

https://github.com/donmccurdy/glTF-Transform/blob/c4c640b/packages/functions/src/prune.ts#L43

Unused TEXCOORD_0 and TANGENT attributes are still referenced by a mesh primitive, and might be used by the target application even if the attached materials don't require those attributes, so we'd be making more assumptions by removing them and this might require ways to opt out. As it is the prune() function is often used internally to clean up after other processing that might have left unused resources behind.

**Comment by hybridherbst** [comment]
Understood - so "unused" as in "unreferenced/abandoned", not necessarily as in "unused in the context of this glTF file".

I'd love if gltf-transform had a way to get rid of the latter as well though - in some cases it can reduce file size quite a bit to remove unused texcoords and tangents (and even normals, for unlit things), and not all generators support doing at for the same reason you mentioned: as part of a production pipeline (and not web delivery) they should be in the file.

Thanks!

**Comment by donmccurdy** [comment]
Yep! Agreed it'd be a good addition, just need to think through the way to expose that  — either under `prune` with an option, or perhaps a separate command.

**Comment by donmccurdy** [comment]
Probably needs a bit more work but here's a start, you can test this script on https://gltf.report/ ... I'm not actually 100% sure which texture slots benefit from having a TANGENT attribute, though. Certainly normal maps and clearcoat normal maps... maybe also upcoming `KHR_materials_anisotropy`?

```typescript
import { Document, Material, ExtensionProperty, Texture, TextureInfo, PropertyType } from '@gltf-transform/core';
import { prune } from '@gltf-transform/functions';

// for each mesh primitive, detect unused vertex attributes based on
// the associated materials.
for (const mesh of document.getRoot().listMeshes()) {
	for (const prim of mesh.listPrimitives()) {
		const reqs = getRequirements(document, prim.getMaterial());

		console.debug(`Requirements: ${Array.from(reqs)}`);

		for (const semantic of prim.listSemantics()) {
			if (semantic.startsWith('TEXCOORD') && !reqs.has(semantic)
					|| semantic === 'TANGENT' && !reqs.has('TANGENT')) {
				console.debug(`Removing: ${semantic}`);
				prim.setAttribute(semantic, null);
			}
		}
	}
}

// clean up unused accessors
await document.transform(prune({propertyTypes: [PropertyType.ACCESSOR]}));

/** gather a set of vertex attributes required by the material */
function getRequirements(document: Document, material: Material | ExtensionProperty | null, reqs = new Set<string>()): Set<string> {
	if (!material) return reqs;

	const graph = document.getGraph();
	for (const edge of graph.listChildEdges(material)) {
		const child = edge.getChild();
		if (child instanceof TextureInfo) {
			reqs.add(`TEXCOORD_${child.getTexCoord()}`);
		} else if (child instanceof ExtensionProperty) {
			getRequirements(document, child, reqs);
		} else if (child instanceof Texture && edge.getName().toLowerCase().includes('normal')) {
			reqs.add('TANGENT');
		}
	}

	return reqs;
}
```
