### ISSUE TITLE
[screenshot] Support screenshot generation on Web and Node.js

### ISSUE THREAD

**Issue by donmccurdy** [donmccurdy/glTF-Transform#62]
Related links:

- https://github.com/google/filament/issues/2647
- https://github.com/google/filament/tree/main/web/docs
- https://cx20.github.io/gltf-test/examples/filament/index.js

Usage:

```
gltf-transform screenshot model.glb --options ...
```

```js
import { screenshot } from '@gltf-transform/screenshot';
import { NodeIO } from '@gltf-transform/core';


const doc = new NodeIO().read('model.glb');
const screenshotBuffer = screenshot(doc);
fs.writeFileSync('screenshot.png', screenshotBuffer);
```

**Comment by donmccurdy** [comment]
Maybe not headless-gl+FIlament after all, because the former doesn't support WebGL 2.  https://github.com/google/node-gles? three.js+headless-gl?

**Comment by donmccurdy** [comment]
https://github.com/sindresorhus/terminal-image

**Comment by donmccurdy** [comment]
Alternatively: https://github.com/maierfelix/webgpu

**Comment by binarytracer** [comment]
@donmccurdy, after 2 years, is this possible now?

**Comment by donmccurdy** [comment]
Hi @binarytracer -- Sorry no, I've decided not to implement rendering here. You'll need to choose other software like a 3D engine or model viewer for screenshots.
