### ISSUE TITLE
Add documentation about toktx dependency

### ISSUE THREAD

**Issue by vorg** [donmccurdy/glTF-Transform#63]
Encoding basis seems to be done via `toktx` tool that could be downloaded from here https://github.com/KhronosGroup/KTX-Software/releases/tag/v4.0.0-beta3

**Comment by donmccurdy** [comment]
Thanks for mentioning this — is there somewhere in the docs that you would intuitively look for this information? Maybe it should just show a warning if you try to convert textures without the dependency installed?

And just to confirm — was it just conversion to KTX that failed when you didn't have the dependency, or a larger error?

**Comment by donmccurdy** [comment]
Should be fixed on next release, thanks!

**Comment by vorg** [comment]
The command exist check is good. Adding small note in https://gltf-transform.donmccurdy.com/cli.html installation section would be another place.
