### ISSUE TITLE
error found incompatible module

### ISSUE THREAD

**Issue by marleykanui** [donmccurdy/glTF-Transform#640]
error @squoosh/lib@0.4.0: The engine "node" is incompatible with this module. Expected version " ^12.5.0 || ^14.0.0 || ^16.0.0 ". Got "18.6.0"
error Found incompatible module.

I've tried to install gltf-transform/cli several times and continue to recieve this error above. Then when I run the unlit command there is an output glb, but the error below pops up and I'm unable to see that the materials reflect as basic materials 

error: Failed to parse URL from /opt/homebrew/lib/node_modules/@gltf-transform/cli/node_modules/@squoosh/lib/build/imagequant_node-a4aafbae.wasm

This is version: 2.2.3
Any and all help is much appreciated

**Comment by donmccurdy** [comment]
Hi @marleykanui! This error is referring to the version of node.js you have installed on your computer. The `@squoosh/lib` library is a dependency of the glTF-Transform CLI, and it doesn't yet support Node.js v18+ (https://github.com/GoogleChromeLabs/squoosh/issues/1242). You'll need to use a version >=14 and <18, I typically use Node.js v14. If you need to keep multiple versions of Node.js around, I like to use [nvm-sh](https://github.com/nvm-sh/nvm) for that.
