### ISSUE TITLE
Extras in texture samplers are not read/written.

### ISSUE THREAD

**Issue by repalash** [donmccurdy/glTF-Transform#645]
Hello, 

**Describe the bug**
extras are removed from the gltf file when processed with glTF-Transform

**To Reproduce**
When reading a GLTF with `readBinary` the extras property is not parsed and written.

**Expected behaviour**
I don't think there should be any problem in adding these to samplers according to the glTF schema: https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#schema-reference-sampler

**Additional context**
From what I could understand by going through the source code, looks like TextureInfo (where data for sampler is saved) has an extras property but it's never set in `ReaderContext.setTextureInfo`. And in `WriterContext.createTextureInfoDef` its not written.

I think it would be the same for custom extensions in samplers.

**Comment by donmccurdy** [comment]
At this time, glTF-Transform doesn't track texture samplers as unique objects in its runtime representation. The properties of the sampler are put on the TextureInfo object instead, and (at export time) an appropriate number of texture samplers are generated and exported. So you're correct that there's currently no way to represent extras or extensions on a texture sampler in this library. Similarly, glTF's "texture" and "image" types are consolidated by this library's runtime representation into a single [Texture](https://gltf-transform.donmccurdy.com/classes/core.texture.html) class.

This has (so far) been a helpful simplification, having fewer definition types to deal with when processing files. There are also no official extensions that require extensions on samplers.

Could you say more about how you'd use extras on samplers? Would extras on the Texture or TextureInfo be reasonable substitutes, or not?

**Comment by repalash** [comment]
I am adding uid for Texture and Source (from three.js) to extras in gltf. 
Source uid goes to images.extras and they work with gltf transform.
For texture uids, first I was adding them to texture extras, but since it's replaced with image extras in gltf transform, I am putting them in sampler extras. 

uid is just one property, in my implementation i want to support custom extension data with textures and support for saving the complete user data from threejs.

From what I understand Texture and TextureInfo are already separate, so could we put the extras and extensions for samplers in TextureInfo?
Or is there already a way to set extras on Texture Info from gltf input?

**Comment by donmccurdy** [comment]
I'm curious why the Texture and the Image (`texture.source`) need to be separate objects with separate unique IDs? It's very rare that those would not have a 1:1 relationship, or that more than one Texture would refer to the same Image.

It was an oversight that extras on TextureInfo do not currently get read or written. I think we can fix that — see #646. For example:

```javascript
material.getBaseColorTextureInfo().setExtras({id: 12345});
```

However, I don't think that three.js does anything with TextureInfo extras data. There is no obvious analog for a "TextureInfo" in three.js, because many TextureInfos may refer to the same glTF Texture. So I'm not sure whether that will solve the problem your facing sorry.

**Comment by repalash** [comment]
> I'm curious why the Texture and the Image (`texture.source`) need to be separate objects with separate unique IDs?

I am trying to serialize the complete three.js state in glTF; since Source is now added as a separate class with a unique UUID, we will have to store those to restore the complete state, as in my SDK anyone could write a custom plugin that uses source by uuid. 

> I don't think that three.js does anything with TextureInfo extras data

Yeah, three.js also doesn't load/write extras in imageDef. But we have custom forks of GLTFLoader and GLTFWriter(from threejs)  that handle this. 

> many TextureInfos may refer to the same glTF Texture

How is that possible, could you share an example? 
Because texture in glTF can have one integer field for the sampler. (assuming TextureInfo are analogous to samplers in glTF json, is that not the case? )
   
PS: Right now I am storing the sampler extras in images with a custom prefix for the properties and it's working because of 1:1 mapping everywhere(for now), but i guess it would be a lot cleaner to keep them in samplers.

Thanks for such a quick response.

**Comment by donmccurdy** [comment]
In glTF, the reference tree looks like this:

<img width="1019" alt="Screen Shot 2022-08-11 at 12 13 23 PM" src="https://user-images.githubusercontent.com/1848368/184220758-dca7cfc2-30dd-48c9-94a8-f35a4d4b3fb6.png">

TextureInfos are embedded in materials, they are never shared among Materials. And so whenever two Materials share the same Texture, those Materials will each have TextureInfos referring to the same Texture.

Note that the bottom layer of this graph — "Sampler" and "Image" — is flattened in glTF-Transform. The data of a Sampler is stored on [TextureInfo](https://gltf-transform.donmccurdy.com/classes/core.textureinfo.html), and the data of an Image is stored on [Texture](https://gltf-transform.donmccurdy.com/classes/core.texture.html). So the number and order of those objects may change when passed through glTF-Transform, but the meaning and appearance of each texture and material will not change.

I'm afraid that converting `three.js ↔ glTF-Transform ↔ glTF` does not have easy 1:1 mappings that are stable on a round trip. If you can narrow the amount of the three.js API you're mapping, that probably simplifies things. Another idea could be to expose an API that is slightly higher level, and use the three.js scene graph as a 'view' into that data. You can see some (experimental) versions of that approach in https://github.com/donmccurdy/glTF-Transform-View, using glTF-Transform as the source data and using three.js as a rendering layer.

**Comment by donmccurdy** [comment]
As extras in texture samplers are now supported (https://github.com/donmccurdy/glTF-Transform/pull/646), I'll close this issue. Glad to discuss further as needed though!
