### ISSUE TITLE
TextureBasisu extension can not be added to glb or gltf file correctly

### ISSUE THREAD

**Issue by Gongyouhai** [donmccurdy/glTF-Transform#648]
**Describe the bug**
**TextureBasisu** extension seems not be attached to the **Document**, the final glb or gltf file still lacks this extension and can not be loaded correctly

**To Reproduce**
1. creating **TextureBasisu** extension and texture object, then setting  the texture object as the base color of material,  the code as follows(ref [example code](https://gltf-transform.donmccurdy.com/classes/extensions.texturebasisu.html)):
```
const path = require("path");
const fs = require("fs");
const { NodeIO } = require("@gltf-transform/core");
const { TextureBasisu } = require('@gltf-transform/extensions');

run();

async function run() {
    const nodeIO = new NodeIO();
    
    const document = await nodeIO.read(
		path.resolve(__dirname, "../assets/box-uv-no-texture.glb")
	);
    
    const basisuExtension = document.createExtension(TextureBasisu).setRequired(true);

    const texture = document.createTexture('MyCompressedTexture')
        .setImage(fs.readFileSync(path.resolve(__dirname, "../assets/texture/aaa.ktx2")))
        .setMimeType('image/ktx2')

    const materials = document.getRoot().listMaterials();
    materials.forEach(material => {
        material.setBaseColorTexture(texture);
    })

    await nodeIO.write(
		path.resolve("D:\\test\\box-ktx.glb"),
		document
	);
}

```
2. using threejs to load the glb file but failed
3. changing the output file type to gltf, and the remains keeps same as  step 1:
```
....
await nodeIO.write(
    path.resolve("D:\\test\\box-ktx.gltf"),
   document
);
```
4. according the [KHR_texture_basisu specification](https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Khronos/KHR_texture_basisu/README.md) to check whether the gltf doc is lack of some values, i find that  the element of textures array is lack of KHR_texture_basisu extension
```
// KHR_texture_basisu specification
"textures": [
        {
            "source": 0,
            "extensions": {
                "KHR_texture_basisu": {
                    "source": 1
                }
            }
        }
    ]

// my gltf file
"textures": [
    {
      "source": 0,
      "sampler": 0
    }
  ]
```
5. i add the KHR_texture_basisu extension to my gltf file manually and it can be loaded successfully by threejs
```
"textures": [
    {
	 "extensions": {
		"KHR_texture_basisu": {
			"source": 0
		}
	},
      "sampler": 0
    }
  ]
```

**Expected behavior**
**TextureBasisu** extension can be attached to the **Document** correctly and modified glb or gltf file can be loaded successfully

**Versions:**
 - Version: [v 2.2.3]
 - Environment: [Node.js]

**Additional context**

**Comment by Gongyouhai** [comment]
it works, thanks a lot !

**Comment by donmccurdy** [comment]
Glad to hear! I've improved the visibility of the warning in https://github.com/donmccurdy/glTF-Transform/commit/a558a620197ef91869d66e6daf28340df1cc779a.
