### ISSUE TITLE
Support interface when specifying logger in setLogger

### ISSUE THREAD

**Issue by TyLindberg** [donmccurdy/glTF-Transform#651]
**Is your feature request related to a problem? Please describe.**
For codebases using logging other than `console`, it would be great to be able to use that logging framework when calling `NodeIO.setLogger`. Currently this is difficult to achieve with TypeScript since it expects an instance of the `Logger` class.

**Describe the solution you'd like**
It would be great to have `setLogger` accept an interface for `logger` argument that only requires the logger to implement `debug`, `error`, `info`, and `warn`. This would allow more flexibility when using custom logging frameworks.

**Describe alternatives you've considered**
There may be an opportunity to create another class similar to `Logger` that will satisfy TypeScript's type checking, but this seems like a wonky solution compared to using an interface.

**Comment by donmccurdy** [comment]
Good point thanks! It was my intention to allow custom logging with `setLogging()`, but didn't make it into the type definitions. Should be fixed after #653.

**Comment by TyLindberg** [comment]
Awesome, thanks!
