### ISSUE TITLE
Private file names being output from writeJSON

### ISSUE THREAD

**Issue by TyLindberg** [donmccurdy/glTF-Transform#652]
**Describe the bug**
When calling `io.writeJSON` on a Document that contains resources with no names, the resulting key names in the `resources` object and `uri` properties in the glTF JSON will be of the form `.png`, `.bin`, etc. Since there are no characters prior to the `.` in these keys the name corresponds to a private file rather than a file with the proper extension.

**To Reproduce**
To view this behavior you can run the following snippet.

```js
import { NodeIO } from "@gltf-transform/core";

(async () => {
  const io = new NodeIO();
  const doc = await io.read("Duck.glb");
  const { json, resources } = await io.writeJSON(doc);

  console.log(Object.keys(resources));
  console.log(json.images);
  console.log(json.buffers);
})();
```

The printed output from this snippet should be the following.

```
[ '.png', '.bin' ]
[ { mimeType: 'image/png', uri: '.png' } ]
[ { uri: '.bin', byteLength: 102040 } ]
```

**Expected behavior**
I would expect the `writeJSON` method to assign names to the output images and buffers. For images it may be something along the lines of `baseColor_0.png`, `occlussion_metallicRoughness_2.jpg`, etc. For buffers it could be something like `buffer_0.bin`, `buffer.bin`, etc.

The exact output names don't necessarily matter, but In my mind the goal would be for `writeJSON` to output unique filenames for separate resources, and for those names to not start with `.`.

This is actually currently being handled for glTF files with multiple resources with the same extension. An example of this can be seen by plugging "DamagedHelmet" into the previous snippet.

```
[ '_1.jpg', '_2.jpg', '_3.jpg', '_4.jpg', '_5.jpg', '.bin' ]
[
  { mimeType: 'image/jpeg', uri: '_1.jpg' },
  { mimeType: 'image/jpeg', uri: '_2.jpg' },
  { mimeType: 'image/jpeg', uri: '_3.jpg' },
  { mimeType: 'image/jpeg', uri: '_4.jpg' },
  { mimeType: 'image/jpeg', uri: '_5.jpg' }
]
[ { uri: '.bin', byteLength: 558504 } ]
```

**Versions:**
 - Version: v2.2.3
 - Environment: Node.js

**Additional context**
I've found that output of the form `.jpg` can break glTF import in certain environments.

**Comment by donmccurdy** [comment]
Hm, you can see what's happening here:

https://github.com/donmccurdy/glTF-Transform/blob/1a74774df4fa731619e52c4168d3fd0e39aea2f4/packages/core/src/io/writer-context.ts#L85-L86

https://github.com/donmccurdy/glTF-Transform/blob/1a74774df4fa731619e52c4168d3fd0e39aea2f4/packages/core/src/io/writer-context.ts#L238-L252

When we're writing to disk (`write`) there is a basename prepended to textures that don't already specify a URI, e.g. `garden.gltf` would have textures `garden.png` (if only one texture is present) or `garden_1.png`, `garden_2.png`, etc. When writing to memory the basename comes out empty.

There's a quick workaround here, if you specify a basename: 


```javascript
const { json, resources } = await io.writeJSON(doc, {basename: 'MyScene'});
```

But probably the logic for generating unique URIs for images and buffers should be reworked a bit.

**Comment by TyLindberg** [comment]
That totally makes sense. Do you think there would be a case for having a default `basename` for this method?

**Comment by donmccurdy** [comment]
Perhaps, though I'm wondering if the naming convention should just be different... using material texture slot names like "baseColor", or material names perhaps. Then it wouldn't fall back to something quite as generic as "scene_1.png" for example.

**Comment by TyLindberg** [comment]
Yeah, that is an interesting consideration. It would certainly make it easier to determine the texture types at a glance after an export.
