### ISSUE TITLE
EXR → KTX2 conversion

### ISSUE THREAD

**Issue by hybridherbst** [donmccurdy/glTF-Transform#671]
**Is your feature request related to a problem? Please describe.**
We've started putting high-dynamic range images in glTF files (for lightmaps, emissive textures, and environment maps) in EXR format using `EXT_texture_exr` (exactly the same as how `EXT_texture_webp` works). Would be great if these would be converted to high-dynamic range KTX2 files when run through gltf-transform.

**Describe the solution you'd like**
Seems the right mime type for EXR is currently `image/x-exr` but I've also seen `image/exr` - would be great if these would be converted into floating-point KTX2 files!

**Describe alternatives you've considered**
Considered pre-packing them into KTX2, but that kind of defeats the purpose of using glTF as an interchange format and then preparing for transmission with glTF-transform.
Currently we're simply skipping transformation but that means the files stay relatively large.

**Additional context**
I can imagine working on a PR with maybe some first pointers on where to start 👀

**Comment by hybridherbst** [comment]
Yes, happy to discuss this in the glTF repo!
I'd also be fine with another floating-point format instead of EXR, so HDR could also work.
Thanks for all the hints!

Regarding cubemaps vs. equirectangular, we're currently shipping equirectangular ones, but at some point a transition to cubemap probably makes sense so these can be used as-is without the shader overhead and additional seams.

Another option for a custom plugin would probably be to convert equirect EXR back to cubemap KTX2 - only one file to handle  and still a cubemap.

Would toktx be capable of packing into BCH6 if there's no way in JavaScript right now?

**Comment by donmccurdy** [comment]
I do prefer OpenEXR to HDR. KTX2 should be more efficient than either from a runtime perspective, though I understand there are fewer authoring tools that support it today.

> Would toktx be capable of packing into BCH6 if there's no way in JavaScript right now?

That's a great question. I don't think KTX-Software can do f16/f32 → BC6H compression today, but  doing OpenEXR f16/f32 → KTX2 f16/f32 might not be much of a stretch. We should ask @lexaknyazev about this perhaps.

**Comment by donmccurdy** [comment]
I'm not sure this issue is actionable for the glTF Transform repository right now, so I'll close the issue. 

Happy to discuss as needed, though!
