### ISSUE TITLE
Vertex merging issue with `draco` (probably an external issue) and `weld`

### ISSUE THREAD

**Issue by hybridherbst** [donmccurdy/glTF-Transform#693]
**Describe the bug**
Might be related to
- #259 

Getting the following error when compressing a file:
```
error: Compression reduced vertex count unexpectedly, corrupting morph targets. Applying the "weld" function before compression may resolve the issue.
```
The file uses animation and blendshapes.

Running the suggested `weld` on the file breaks it as the resulting animation now moves wrong / welded vertices around.

**To Reproduce**
- Download [SimpleBlendshapeAnimation.zip](https://github.com/donmccurdy/glTF-Transform/files/9665829/SimpleBlendshapeAnimation.zip)
- run `gltf-transform draco SimpleBlendshapeAnimation.glb SimpleBlendshapeAnimation.draco.glb`
- note error logged
- run `gltf-transform weld SimpleBlendshapeAnimation.glb SimpleBlendshapeAnimation.weld.glb`
- note the resulting file is obviously broken because welding vertices that are moved in Blendshapes 

**Expected behavior**
I suspect there are two bugs here:
- draco shouldn't be merging vertices that can't be merged (external issue, raised as https://github.com/google/draco/issues/929)
- gltf-transform weld shouldn't be merging vertices that can't be merged (this issue)

**Comment by donmccurdy** [comment]
As you guessed I think the Draco compression problem is an external issue – sequential encoding shouldn't change the vertex count, but it does, and unfortunately if the vertex count changes this library can't write valid morph htargets.

The weld() is unexpected though, I'll need to look into that. If you _just_ needed to add indices, setting `weld({tolerance: 0})` would do it without problems. But that doesn't actually merge any vertices, it just writes indices for the existing vertices, and that isn't what's needed to work around the issue in the Draco encoder.

**Comment by donmccurdy** [comment]
The base logic for vertex welding is here:

https://github.com/donmccurdy/glTF-Transform/blob/4177b0a4e0fb5ee0c3d02fc0dd5db4990a2b55a0/packages/functions/src/weld.ts#L160-L177

As you can see it does take blend shapes (targets) into account, so I'm at a bit of a loss so far as to why the unwanted merges are happening here. 🤔
