### ISSUE TITLE
Reconsider extension naming convention

### ISSUE THREAD

**Issue by donmccurdy** [donmccurdy/glTF-Transform#715]
Currently Extension subclasses are named after their extension, minus the prefix. Any ExtensionProperty subclasses they create are named succinctly for what they represent:

- MaterialsClearcoat / Clearcoat
- MaterialsVolume / Volume
- DracoMeshCompresion / —
- TextureBasisu / —
- LightsPunctual / Light

I regret that there's not much to semantically differentiate the extension from the property. If KHR_audio is ratified, will it just be named "Audio" here? It's weird. Originally I'd thought of an "Extension" suffix on the names but felt it was too verbose. Now I'm wondering if a prefix would be more practical.

- KHRMaterialsVolume / Volume
- KHRDracoMeshCompression / —
- KHRLightsPunctual / Light
- ...

This makes a clearer distinction, I think, and doesn't lengthen the names much.

**Comment by hybridherbst** [comment]
+1 for explicit names matching the extensions!

**Comment by donmccurdy** [comment]
@robertlong any preference on this change?
