### ISSUE TITLE
Instance disposed when one fails

### ISSUE THREAD

**Issue by Samsy** [donmccurdy/glTF-Transform#723]
1 ) Perform an instance function successfully on a document.

2 ) Re-perform an instance on the same document, but with different nodes after manipulation which in my particular conditions fails because there's no common meshes in the newly manipulated document

3 ) The step 1 previously successful instancing is erased and not working anymore !

I suspect the dispose here to dispose all previously successfully created instance

https://github.com/donmccurdy/glTF-Transform/blob/ce526e7/packages/functions/src/instance.ts#L93

More precisions as well,

I'm operating this way cause I need in a specific case : 

1 ) instance object in children A independently from the other childrens

2 ) instance object in children B independently from the other childrens

Both Children A and Children B may have mesh in commons, but cannot be instanced together for the purpose of the application

**Comment by donmccurdy** [comment]
Thanks @Samsy! This should be fixed in https://github.com/donmccurdy/glTF-Transform/pull/724.

**Comment by Samsy** [comment]
Thanks a lot @donmccurdy
I'm currently OOO but will check it asap

**Comment by Samsy** [comment]
I confirm this is working ! 

Thanks a lot !
