### ISSUE TITLE
Writing new glb using Node IO is not working in three js loader.

### ISSUE THREAD

**Issue by atul161** [donmccurdy/glTF-Transform#728]
I have downloaded a glb. 
I was also able to render my glb on https://gltf-viewer.donmccurdy.com/

Now when i am using nodeio for reading and writing the same glb after that i am not able to render my glb.

```
    document = await io.read('./assets/bear.glb');
     await io.write('model.glb', document);

```

**Comment by donmccurdy** [comment]
If you share the file (ZIP archives can be attached to GitHub comments) I'll be able too look into this -- thanks!
