### ISSUE TITLE
cli webp conversion results with an error

### ISSUE THREAD

**Issue by bpedazur** [donmccurdy/glTF-Transform#744]
**Describe the bug**
When I run the cli function for webp I get the fllowing error:
_Aborted()_
_error: Aborted(). Build with -sASSERTIONS for more info._

**To Reproduce**
1. run `gltf-transform webp <input> <output>`

**Versions:**
 - Version: running version 2.4.7 of glTF-Transform
 - Environment: Ubuntu 22, Node version v16.18.1

**Comment by donmccurdy** [comment]
@bpedazur could you give this a try on your OS? 

```bash
npm install --global @gltf-transform/cli@next
```

It's a prerelease for v3 (with #752), including sharp instead of squoosh.

**Comment by bpedazur** [comment]
Hi. I tried it and unfortunately, it didn't work. I'm still getting the same issue. I tested it on my Ubuntu 22 machine and my Windows machine running the same node version - both resulted in the same error.

**Comment by donmccurdy** [comment]
Hm, I'm not sure what to make of that. Do other operations work, like `gltf-transform --help`? Does the model have any extensions, like Draco, that might be relying on WASM decoders? I'm assuming the vague `Build with -sASSERTIONS` message means something is failing in a WASM or native dependency...

**Comment by bpedazur** [comment]
Other operations work fine. I noticed that it happens only with larger files (>200M), regardless of the extensions -some were Draco compressed and some were not.

**Comment by donmccurdy** [comment]
I see, thanks - can you share an example file? I suspect this might have something to do with node.js memory limits. Draco-compressed geometry is decompressed in memory, and textures must also be decompressed during the webp conversion, so it'll be easy to use a lot of memory quickly with files that are already large.

I suspect that limiting concurrency during compression might help here, but without a way to reproduce the error myself I probably cannot work on that fix.

**Comment by donmccurdy** [comment]
Closing for now, as I'll need a way to reproduce the issue in order to work on this. Thanks!
