### ISSUE TITLE
Error: spawn toktx EACCESS

### ISSUE THREAD

**Issue by hybridherbst** [donmccurdy/glTF-Transform#750]
**Describe the bug**
Haven't seen this one before and not sure why it suddenly started happening:

![image](https://user-images.githubusercontent.com/2693840/208404083-7d25cddc-7cb0-4bd3-a32b-4824abb90624.png)

Seems it's trying to spawn "toktx --version" - if I do that right below, it works:

![image](https://user-images.githubusercontent.com/2693840/208404204-b303a83a-94f9-40d9-9f7e-d9c308389e5a.png)

**To Reproduce**
No idea, but wanted to have this tracked. Currently I can't use gltf-transform for compressing textures due to this issue.

**Versions:**
 - Version: [2.4.7]
 - Environment: [CLI]

**Additional context**
Tried on both Node 16 and 18. 18 always logs an `error: fetch failed` for any gltf-transform command it seems, even `--version`, but seems to succeed nonetheless.

**Comment by donmccurdy** [comment]
On latest Node.js v18.12.1 I'm seeing:

```
> gltf-transform --help
(node:62303) ExperimentalWarning: The Fetch API is an experimental feature. This
feature could change at any time (Use `node --trace-warnings ...` to show where 
the warning was created)

error: Failed to parse URL from /Users/donmccurdy/Documents/Projects/glTF-Transform/node_modules/@squoosh/lib/build/imagequant_node-a4aafbae.wasm
```

I believe that part comes back to https://github.com/GoogleChromeLabs/squoosh/issues/1242, squoosh (used for WebP, JPEG, and PNG optimization) needs some updates for Node.js 18.

However, I can't seem to reproduce the "EACCESS" error. If anyone else is seeing that and can suggest ways to debug that would be helpful. I'm wondering if this might be related to a recent Node.js 18 update, and/or Windows OS?

**Comment by CodyJasonBennett** [comment]
Related: https://github.com/withastro/astro/issues/5051#issuecomment-1305894211.

**Comment by donmccurdy** [comment]
@hybridherbst would you be up for building the library locally and seeing if the EACCESS error re-occurs? I'm wondering if Squoosh is also the cause of that, and whether removing it from the build would fix things. If so it might be time to switch from Squoosh to Sharp (https://sharp.pixelplumbing.com/) or something else.

**Comment by donmccurdy** [comment]
- cc https://github.com/donmccurdy/glTF-Transform/issues/751

**Comment by donmccurdy** [comment]
@hybridherbst could you give this a try on your OS? 

```bash
npm install --global @gltf-transform/cli@next
```

It's a prerelease for v3, including sharp instead of squoosh.

**Comment by hybridherbst** [comment]
Don't think it's squoosh-related unfortunately:
![image](https://user-images.githubusercontent.com/2693840/208876639-e0082952-ed8e-4a90-a27b-51e076467494.png)

To me it looks like for some reason spawning "toktx --version" is failing...

**Comment by CodyJasonBennett** [comment]
Are there any assets I can use to reproduce this? I want to see if I can get a more helpful stack-trace out of Node.

**Comment by hybridherbst** [comment]
The problem is that it seems to be machine-related, I'm able to run this on the same asset just fine on other machines, even with the same Node and OS versions. I suspect some kind of permissions issue but haven't seen this happen with another node tool (even ones that also spawn toktx processes) so thought I'd track it here.

The asset I used above is this one: [Textures-4k.zip](https://github.com/donmccurdy/glTF-Transform/files/10276779/Textures-4k.zip)

**Comment by donmccurdy** [comment]
Ah well.

Does `--jobs 1` make any difference here? Possibly concurrency limits ...

**Comment by donmccurdy** [comment]
Glad to help with this if someone can look into the cause, as I don't have Windows access. PRs also welcome!

**Comment by hybridherbst** [comment]
Does unfortunately not change it, would be great if you could reopen this issue.
![image](https://user-images.githubusercontent.com/2693840/211786443-fb07f754-2bf8-40a8-adb5-43049b9da0d4.png)

I'm not sure which node.js environment settings I'd need to change or look into – any hints?

**Comment by donmccurdy** [comment]
I was thinking of limits on the number of open files with Node.js, but now I don't think that matches up with the context or the error message.

**Comment by donmccurdy** [comment]
The only thing I'm aware I can do here is to look for a solution to #675. If someone will continue investigating the EACCES errors, I am happy to reopen this issue.

**Comment by hybridherbst** [comment]
I have some additional info that I wanted to share, maybe it's helpful in the future:
- the EACCESS errors are _only_ happening when running global gltf-transform from C:/
- they're _not_ happening when running global gltf-transform from any other drive.
... independent of the actual folder, just the drive seems to matter.
