### ISSUE TITLE
Replace Squoosh with Sharp for image optimization

### ISSUE THREAD

**Issue by donmccurdy** [donmccurdy/glTF-Transform#751]
I've been using squoosh for webp, jpeg, and png optimization since those features were added. It supports only Node.js today, and only versions <18, but the hope originally was that Squoosh would add in-browser support and maybe eventually Basis compression. I no longer think either of those things will happen, and since Squoosh seems to be unmaintained (causing errors in latest Node.js LTS), it's time to switch.

The library will begin using Sharp (https://sharp.pixelplumbing.com/) for these operations instead, unless I find something better. Being able to support these features on the web would be great, but I don't see a maintained alternative for it, short of forking Squoosh.

This might also be a good time to update the image resizing code, or provide an alternative.

Related issues:

- https://github.com/donmccurdy/glTF-Transform/issues/773
- https://github.com/donmccurdy/glTF-Transform/issues/750
- https://github.com/donmccurdy/glTF-Transform/issues/744
- https://github.com/donmccurdy/glTF-Transform/issues/704
- https://github.com/donmccurdy/glTF-Transform/issues/647
- https://github.com/donmccurdy/glTF-Transform/issues/612
- https://github.com/donmccurdy/glTF-Transform/issues/583
- https://github.com/donmccurdy/glTF-Transform/issues/562

**Comment by donmccurdy** [comment]
FYI: 

- https://github.com/lovell/sharp/issues/2981

**Comment by hybridherbst** [comment]
Maintenance for the Squoosh CLI and libsquoosh has officially ended now: 
https://github.com/GoogleChromeLabs/squoosh/issues/1181#issuecomment-1369837109

**Comment by donmccurdy** [comment]
One bit of good news is that Sharp uses [libvips](https://www.libvips.org/) as its image processing engine, and there is an unofficial [WASM build](https://github.com/kleisauke/wasm-vips) that works on web, excluding Safari. Probably too early to pull that WASM build in here, but maybe possible to support running things on the web down the road this way too.
