### ISSUE TITLE
[atlas] Create texture atlases

### ISSUE THREAD

**Issue by donmccurdy** [donmccurdy/glTF-Transform#8]
See: https://github.com/oguzeroglu/TextureMerger/blob/master/TextureMerger.js

**Comment by Inviz** [comment]
Great idea!

**Comment by donmccurdy** [comment]
Unless a JS or WASM library shows up that makes texture atlas creation considerably easier, I don't think I'll be able to include it here. There seem to be plenty of utilities for mechanically merging the textures, but not so much for making sure that the texture packing is efficient in image and UV space. I think it's more than I can tackle, but could certainly built on/in/with glTF-Transform if someone wanted to do it.
