### ISSUE TITLE
Can textureResize become textureCompress on the web?

### ISSUE THREAD

**Issue by elalish** [donmccurdy/glTF-Transform#801]
**Is your feature request related to a problem? Please describe.**
I'd like to compress jpg/png textures into webP on the web. `textureCompress` is the function I want, but it doesn't (yet) work on the web. `textureResize` does work on the web, but only supports jpg/png and apparently not converting between them.

**Describe the solution you'd like**
Looking at your `ndarray-pixels` package, it seems like `textureResize` would be able to do everything `textureCompress` does if this [check](https://github.com/donmccurdy/glTF-Transform/blob/b53c7a26/packages/functions/src/texture-resize.ts#L63) were removed (at least on web) and the options were added. Is there any reason not to?

**Describe alternatives you've considered**
Wait for `sharp` to add web support.

**Additional context**
I'd like to take a stab at making a very simple, very automatic glTF optimizer based on `gltf-transform`, probably living next to the model-viewer editor.

**Comment by donmccurdy** [comment]
I'm not using very much of the Sharp API, I wonder if we could 'polyfill' Sharp with a small wrapper around `ndarray-pixels`, and use it as a fallback to the Sharp API? Would just need to match the API here:

https://github.com/donmccurdy/glTF-Transform/blob/482a718cde2fce4b58c72b51c99bd1f31539ccd9/packages/functions/src/texture-compress.ts#L132-L147

Another alternative here would be https://github.com/kleisauke/wasm-vips ... same underlying native library as Sharp, compiled to WASM, but note the "early development" disclaimers. I tend to assume the compression with libvips is better than what browsers provide, but I don't really know on that.

**Comment by elalish** [comment]
Yes, I guess I thought most of the code for that polyfill was already in `textureResize`. Perhaps those two functions could be combined, thus providing the fallback with a single API? I have no problem with browser-level compression, so long as we can go from lossless to lossy.

**Comment by donmccurdy** [comment]
Maybe just removing `textureResize` would be the thing to do, yeah. Can't resize without recompressing anyway. And probably a smaller/simpler API surfaces to maintain. Then let [textureCompress](https://gltf-transform.donmccurdy.com/functions.html#texturecompress) default to ndarray-pixels if no encoder is given.
