### ISSUE TITLE
Add vertexPaint()

### ISSUE THREAD

**Issue by donmccurdy** [donmccurdy/glTF-Transform#802]
In scenes with many objects like those found in CAD or low-poly scenes, we may have 100s of materials with solid materials. It can be advantageous join them, with the new join() function, but to do that we need to unify the materials. A new function that converts solid colors to vertex colors, and then de-duplicates materials, could be a big help here.

Example:

```javascript
import { vertexPaint, ... } from '@gltf-transform/functions';

await document.transform(
  vertexPaint(),
  dedup(),
  flatten(),
  join(),
  weld(),
  simplify({ ... }),
  draco()
);
```

**Comment by hybridherbst** [comment]
Are you planning to also do this for textures? (e.g.: bake texture data to vertex colors)
I've seen (and used) that for a) artistic purposes b) saving on data c) for LOD levels (lowest LOD level is vertex color only, higher ones have textures).

Worth noting that there are fun challenges with animated objects and this kind of join + vertexBake functionality - not unsolvable though 😅

**Comment by donmccurdy** [comment]
Probably not the initial focus — I mostly want to make sure the flatten() and join() features are useful out of the gate, for some of these CAD and BIM models that otherwise have too many materials to benefit from joining. But since [ndarray-pixels](https://github.com/donmccurdy/ndarray-pixels) is already a dependency, reading from textures and writing to vertex colors doesn't seem like it should be a huge lift either. I hadn't considered the idea with LODs, that is a nice trick!

> Worth noting that there are fun challenges with animated objects and this kind of join + vertexBake functionality...

We can skip joining animated notes...

https://github.com/donmccurdy/glTF-Transform/blob/fb97455ae01f03c59919ae4f71768d798f4aa811/packages/functions/src/join.ts#L124-L126

... but I can't think of additional cases where vertexBake and animation get entangled, did you have some in mind there? I imagine detecting unknown extensions on nodes and meshes may need to block joining in some cases too, though maybe it's more practical to just jump down a level and  control what gets joined manually at that point, with `joinPrimitives( prims )`.

**Comment by donmccurdy** [comment]
A quick and dirty implementation:

```js
import { ColorUtils } from '@gltf-transform/core';
import { KHRMaterialsUnlit } from '@gltf-transform/extensions';
import { getPixels } from 'ndarray-pixels';

for (const mesh of document.getRoot().listMeshes()) {
	for (const prim of mesh.listPrimitives()) {
		const material = prim.getMaterial();
		const texture = material.getBaseColorTexture();
		const texCoord = material.getBaseColorTextureInfo().getTexCoord();
		const uv = prim.getAttribute(`TEXCOORD_${texCoord}`)
		const color = document.createAccessor()
			.setArray(new Float32Array(uv.getCount() * 3))
			.setBuffer(uv.getBuffer())
			.setType('VEC3');

		const pixels = await getPixels(texture.getImage(), texture.getMimeType());
		const _uv = [], _color = [];

		// Read color from texture, write to COLOR_0 vertex attribute.
		for (let i = 0, il = uv.getCount(); i < il; i++) {
			uv.getElement(i, _uv);
			const x = Math.floor(_uv[0] * pixels.shape[0]);
			const y = Math.floor((_uv[1]) * pixels.shape[1]);
			
			_color[0] = pixels.get(x, y, 0) / 255;
			_color[1] = pixels.get(x, y, 1) / 255;
			_color[2] = pixels.get(x, y, 2) / 255;

			ColorUtils.convertSRGBToLinear(_color, _color);

			color.setElement(i, _color);
		}

		prim.setAttribute('COLOR_0', color);
		uv.dispose();
	}
}

// Clean up unused textures.
for (const texture of document.getRoot().listTextures()) {
	texture.dispose();
}

// Switch the material to unlit.
const unlitExtension = document.createExtension(KHRMaterialsUnlit);
for (const material of document.getRoot().listMaterials()) {
	material.setExtension('KHR_materials_unlit', unlitExtension.createUnlit());
}
```

- related: https://github.com/mrdoob/three.js/issues/25697

**Comment by donmccurdy** [comment]
Closing for now – I think this needs (in addition to time...) a clearer motivating use case to make decisions about the implementation and to test it properly.
