### ISSUE TITLE
Tutorials — reading and writing files

### ISSUE THREAD

**Issue by donmccurdy** [donmccurdy/glTF-Transform#808]
While the I/O classes are documented, e.g. to read/write .glTF files on disk...  the two most reasonable next steps probably deserve guides, and we don't have them today:

1. generate a glTF file 'from scratch' given basic vertex data and a texture
2. read a glTF file, then unpack basic vertex data and a texture (e.g. for rendering)

I imagine those guides could be helpful to people who are writing converters, generating models procedurally, writing loaders for their own engines or applications, etc. This could go into the Introduction section, following the "Concepts" guide.

(Suggested by @bhouston)

**Comment by OldManMeta** [comment]
Hi Don - this is precisely the position I am in at the moment ;-) so your thoughts would be most welcome.

My workflow in this instance is - read file from disk=> edit/compress=> write file to disk.

Any hints on that would be awesome!

Cheers

**Comment by donmccurdy** [comment]
Hi @OldManMeta! Is compression the only edit you're trying to make, or were there others? Do you prefer to do this in a Node.js script, a web browser, a CLI tool, or something else? Maybe the best thing would be to start a [discussion thread](https://github.com/donmccurdy/glTF-Transform/discussions) and we can figure out the rest.

**Comment by OldManMeta** [comment]
@donmccurdy - hey thanks for that. Wow - I didn't even see the discussions stuff before. I'll head over there! Cheers

**Comment by donmccurdy** [comment]
Merging this issue into https://github.com/donmccurdy/glTF-Transform/issues/984.
