### ISSUE TITLE
"error: Cannot use import statement outside a module" using the example configuration:

### ISSUE THREAD

**Issue by Utopiah** [donmccurdy/glTF-Transform#828]
**Describe the bug**
The example from the documentation does not work.

**To Reproduce**
1. Go to https://gltf-transform.donmccurdy.com/cli.html#configuration
2. copy/paste to `gltf-transform.config.js`
3. start `gltf-transform --help --config path/to/gltf-transform.config.js`

**Expected behavior**

**Versions:**
 - Version: gltf-transform 3.0.2
 - Environment: Node.js v19.6.1

**Additional context**
```
fabien@fabien-CORSAIR-ONE-i160:~/Prototypes/blender-converter/animations_male_rpm_walkingset$ gltf-transform --help --config gltf-transform.config.js 
(node:841341) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)

error: Cannot use import statement outside a module

/home/fabien/Prototypes/blender-converter/animations_male_rpm_walkingset/gltf-transform.config.js:2
import { Extension } from '@gltf-transform/core';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1195:20)
    at Module._compile (node:internal/modules/cjs/loader:1239:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:168:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)

Node.js v19.6.1

```

**Comment by donmccurdy** [comment]
I think the cause will be that the config file needs to be an ES Module, as defined by whatever project you're using it in. Node.js assumes `.js` files are CommonJS, unless found under a directory with a package.json containing `{"type": "module"}`. I'm not sure how other tools like Vite get around that in their configs.

The easiest way to fix this would be to rename the config file `.mjs` instead of `.js`, and it should work as expected.

**Comment by Utopiah** [comment]
Indeed so should the documentation recommend `gltf-transform --help --config path/to/gltf-transform.config.mjs` or might it break other things?
