### ISSUE TITLE
Sharp: webP --quality flag has no effect

### ISSUE THREAD

**Issue by emkajeej** [donmccurdy/glTF-Transform#829]
**Describe the bug**
When running `gltf-transform webp` the `--quality` flag does not seem to have any effect.

**To Reproduce**
1. Run `gltf-transform webp input.glb output100.glb --quality 100`
2. Note the output's reported filesize and image quality in e.g gtlf.report
3. Run `gltf-transform webp input.glb output0.glb --quality 0`
4. Note the output's reported filesize and image quality in e.g gtlf.report

**Expected behavior**
Filesize should be considerable lower in the output0.glb, at obvious cost of image quality.

**Actual behavior**
The files output100.glb and output0.glb are identical.

**Versions:**
 - Version: 3.0.2
 - Node 16.10

**Additional context**
Using gltf.report, I extracted the normal maps and compared them in Photoshop. They are identical.
Manually running the normal map through an app like Squoosh with quality 0 and 100, the differences are considerable:

Original:
<img width="974" alt="image" src="https://user-images.githubusercontent.com/34506354/220940664-be3c064e-22aa-4cca-bf1d-3b0845512548.png">

Quality 100 gltf-transform:
<img width="966" alt="image" src="https://user-images.githubusercontent.com/34506354/220940743-583a683d-03fb-411b-9610-365f3d704d2f.png">

Quality 0 gltf-transform:
<img width="966" alt="image" src="https://user-images.githubusercontent.com/34506354/220940771-944f9088-9081-42c4-8c56-0e480c312e05.png">

Quality 0 Squoosh:
<img width="973" alt="image" src="https://user-images.githubusercontent.com/34506354/220940133-34d4aa87-f711-4ed8-be66-5d8b4feffdbe.png">

**Comment by donmccurdy** [comment]
Thank you! Should be fixed in v3.0.3.
