### ISSUE TITLE
Allow root nodes in multiple scenes

### ISSUE THREAD

**Issue by jonflanders** [donmccurdy/glTF-Transform#831]
Not sure if this is a feature request or a bug report.

The glTF spec says that "The same root node can appear in multiple scenes"  and this seems to work in most tools I've loaded my glTFs in.   But your tool always validates scenes and removes any nodes that appear in multiple scenes. 

<img width="973" alt="Screen Shot 2023-02-23 at 3 25 45 PM" src="https://user-images.githubusercontent.com/1928643/221054408-7d498522-fb23-44cc-8974-f8540f0035e8.png">

**Comment by donmccurdy** [comment]
Thanks @jonflanders! I didn't realize that was allowed — I agree we should try to support it here, in that case. Will have to think about how to make the fix, which is somewhat a breaking change that would affect the `Node#getParent` method:

https://github.com/donmccurdy/glTF-Transform/blob/b19c8971a0c384770e57d61f846506eb1bc3954c/packages/core/src/properties/node.ts#L208-L214

**Comment by jonflanders** [comment]
I was going to look and see if I could help and make a PR - but I hadn't gotten the chance yet (and I don't know the source well only having been using your AWESOME! tool for a month or so).  


Thanks!

**Comment by donmccurdy** [comment]
No worries! The fix here will probably touch a fair number of files, I'll try to get that done fairly soon:

- https://github.com/donmccurdy/glTF-Transform/pull/833

Would you be able to share an example file that uses root nodes in multiple scenes?

**Comment by jonflanders** [comment]
[multiscene.glb.zip](https://github.com/donmccurdy/glTF-Transform/files/10843388/multiscene.glb.zip)

Sure  - thanks!  Here you go.
