### ISSUE TITLE
 WriteBinary doesn't keep the order of textures

### ISSUE THREAD

**Issue by gz65555** [donmccurdy/glTF-Transform#842]
**Describe the bug**
I use glTF-Transform to transform a glTF file to glb format, but the order of the textures of glb is not consistent with the original glTF. 

**To Reproduce**
This is an original glTF
[helmet.gltf.zip](https://github.com/donmccurdy/glTF-Transform/files/10899880/helmet.gltf.zip)
The field of `textures` is:
```json
{
  "textures": [
    { "sampler": 0, "source": 0 },
    { "sampler": 0, "source": 1 },
    { "sampler": 0, "source": 2 },
    { "sampler": 0, "source": 3 },
    { "sampler": 0, "source": 4 }
  ]
} 
```
The code of transform is:
```javascript
const resources = {};
await Promise.all(
  [...json.buffers, ...json.images].map((item) =>
    fetch(item.uri)
      .then((res) => res.arrayBuffer())
      .then((ab) => (resources[item.uri] = new Uint8Array(ab)))
  )
);

const doc = await io.readJSON({
  json,
  resources
});

const result = await io.writeBinary(doc);
```

The result I parsed is:
![image](https://user-images.githubusercontent.com/6926263/223161144-4debc85b-fa7f-4b6b-80ab-429798671318.png)

And the result file is:
[helmet.glb.zip](https://github.com/donmccurdy/glTF-Transform/files/10900102/helmet.glb.zip)

**Expected behavior**
The order of the glb texture field should be the same as the source glTF.

**Versions:**
 - Version: [3.0.4]
 - Environment: [Browser]

**Comment by gz65555** [comment]
Thank you for your answer, the material I created myself needs to reference the texture in glTF. 

In the texture information, name/extras are not reliable, and the material of glTF itself also uses indices as identity. Also, glTF is designed to separate images and textures.

I think this is a design issue, can I submit a pull request to fix it?

**Comment by donmccurdy** [comment]
> I think this is a design issue, can I submit a pull request to fix it?

Sorry, but I don't know of any solution preserving texture indices that I could accept as a PR.

glTF Transform needs to know about references to objects like textures. It converts indices to references when loading, so it can track them. Without knowing where a texture is used, for example, it can't determine the right compression settings when using the KTX2 compression. I understand you're only trying to pack a glTF file into a GLB file here, which is much simpler than the broader goals of this library, but I think the changes you describe are going to create larger problems for the project. For full use of the glTF Transform library it is necessary to provide an implementation if your custom material extension, as shown here: https://gltf-transform.donmccurdy.com/extensions.html#custom-extensions.


I would be open to creating a `JSONToBinary( { json, resources } )` method that would do what you need, without unpacking the model into glTF Transforms internal representation. You can find most of the necessary code in:

https://github.com/donmccurdy/glTF-Transform/blob/a09aa718d8bbeaed32dcc1556b6d246c5caa5fe1/packages/core/src/io/platform-io.ts#L153-L171

**Comment by gz65555** [comment]
Yes, adding an `images` field is too complex.  

I use gltf-transform not only to convert glTF to glb, I also use quantize, mesh-opt and other functions. glTF-transform is a very nice tool for dealing with glTF.

I have used a custom extension to customize the material replacement, but it didn't solve the problem. Let me figure out how to get around this problem.

Thanks anyway.

**Comment by donmccurdy** [comment]
A custom extension will keep the material attached to the correct textures, even when the texture indices change. The material will be updated at export with the correct texture index. If you want to check the [draft implementation of KHR_materials_anisotropy](https://github.com/donmccurdy/glTF-Transform/pull/748/files) you can see how that generally works, and how to add your own extension.

**Comment by donmccurdy** [comment]
Merging into #746.
