### ISSUE TITLE
Migrate CLI from Caporal.js

### ISSUE THREAD

**Issue by donmccurdy** [donmccurdy/glTF-Transform#843]
Caporal is [unmaintained](https://github.com/mattallty/Caporal.js/issues/243) at this point, and the outdated dependencies underneath it are piling up. Especially now that `@gltf-transform/cli` offers an experimental plugin API, it'd be nice for the interface to custom CLI commands to be stable. Some alternatives:

- https://github.com/oclif/oclif
- https://www.npmjs.com/package/yargs
- https://github.com/tj/commander.js/

~~I'm leaning toward oclif.~~

**Comment by donmccurdy** [comment]
Tangentially related idea, export an API interface from /functions and import that into /cli to reduce duplication.

```javascript
export const JOIN_API = {
  fn: join,
  options: {
    keepMeshes: {
      type: 'boolean',
      default: JOIN_DEFAULTS.keepMeshes,
    },
    keepNamed: {
      type: 'boolean',
      default: JOIN_DEFAULTS.keepMeshes,
    }
  }
};
```

But arguably the only value there is a declarative representation of the options list...

Potentially the full description could be pulled from JSDoc using [`@greendoc/parse`](https://github.com/donmccurdy/greendoc), when that is stable.

**Comment by arpu** [comment]
Hi, 
for the meantime would it make sense to use a Caporal.js fork to get the npm audit fixed?

at the moment i fight with lodash

```
lodash  <=4.17.20
Severity: high
Prototype Pollution in lodash - https://github.com/advisories/GHSA-p6mc-m468-83gw
Command Injection in lodash - https://github.com/advisories/GHSA-35jh-r3h4-6jhm
Regular Expression Denial of Service (ReDoS) in lodash - https://github.com/advisories/GHSA-29mw-wpgm-hmr9
fix available via `npm audit fix --force`
Will install @gltf-transform/cli@0.4.1, which is a breaking change
node_modules/lodash
  @caporal/core  *
  Depends on vulnerable versions of lodash
  node_modules/@caporal/core
    @gltf-transform/cli  >=0.4.2
    Depends on vulnerable versions of @caporal/core
    node_modules/@gltf-transform/cli

3 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force
```

**Comment by donmccurdy** [comment]
I haven't seen any indicators that the npm audit warnings are 'real' (and [in general they're noise](https://overreacted.io/npm-audit-broken-by-design/)), so I'm not eager to create or vet a fork just to silence those issues. If I have time to spend on it, I'd rather direct the time at setting up a replacement. 

If this is causing significant issues for people though, we can discuss.

**Comment by donmccurdy** [comment]
Ended up doing a fork of Caporal after all – migrating to other options didn't feel like as good of a fit once I started working on it.

**Comment by donmccurdy** [comment]
Reconsidering more recent, lighter-weight alternatives:

- https://npmx.dev/package/@effect/cli
- https://npmx.dev/package/citty

Both are relatively small, in terms of size and dependencies. `citty` is the smaller of the two, but appears to be in early development. `@effect/cli` is a bit bigger but supports Node.js or Deno runtimes, and I'm guessing more stable at this stage, but not sure.
