### ISSUE TITLE
Add Pattern Function

### ISSUE THREAD

**Issue by robertlong** [donmccurdy/glTF-Transform#845]
**Is your feature request related to a problem? Please describe.**
In my asset optimization pipeline I resize textures to a maximum size. I'd like to be able to ignore certain textures by looking for an `extras` property. Currently the only way to filter textures is a regex on name/uri.

**Describe the solution you'd like**
Add the ability to provide a `pattern` function to `textureResize` etc. where the first argument is the object in question and the return value is a boolean where `true` means include the object and false means ignore the object.

**Describe alternatives you've considered**
I could hack around this by searching through the document and looking for the extras property and then dynamically constructing the regex, but that's a lot more work and is pretty hacky.

**Additional context**
None

**Comment by donmccurdy** [comment]
At this point most of the code in this transform is already dedicated to just selecting which textures to change. I'm not keen to add more options, hiding what is an otherwise simple bit of code. Are you using Node.js or Web? For Node.js this should work just as well, and run much faster:

```javascript
import sharp from 'sharp';

function customResize({ size }) {
  return (document) => {
    for (const texture of document.getRoot().listTextures()) {
      if (/* ??? */) continue;

      const buffer = await sharp(texture.getImage())
        .resize(size[0], size[1], {
          fit: 'inside',
          kernel: resizeFilter,
          withoutEnlargement: true,
        })
        .toBuffer();

      texture.setImage(BufferUtils.toView(buffer));

    }
  };
}

await document.transform(customResize({size: [1024, 1024]}));
```
