### ISSUE TITLE
gltf-transform broke my model because of too much decimation

### ISSUE THREAD

**Issue by y-71** [donmccurdy/glTF-Transform#846]
**Describe the bug**
I ran compression on lots of models and the result blew me away most of the times. Then I ran it on this case and I lost some important poly during during the process. I don't know if there is a way to get less decimation. 

**To Reproduce**
I ran ``` gltf-transform optimize model.glb output.glb   ``` [on this model] (https://we.tl/t-Z3zcR5JeHA) and it ended with broking the model. 

**Expected behavior**
not loosing that much poly and having the right poly.

**Versions:**
 - Version: latest
 - Environment: Node.js

**Additional context**
I really love your lib and would love to contribute more. 
Yours sincerely.

**Comment by donmccurdy** [comment]
Hi @y-71! Most operations in the CLI are configurable with flags. To see those options you can run something like:

```
gltf-transform optimize --help
```

In this case, setting a lower error threshold for the simplification is probably what you want:

```
gltf-transform optimize model.glb output.glb --simplify 0.000001
```

There is no perfect amount of simplification for all models, so you may have to try different options, or disable simplification (`--simplify 0`) if the model is already simple enough and/or simplification causes other issues.
