### ISSUE TITLE
Thin planes are removed during optimize

### ISSUE THREAD

**Issue by bigrig2212** [donmccurdy/glTF-Transform#849]
Hello! What a great package. Wondering if there is a certain configuration for optimize that will prevent thin planes from being removed? 

Command i ran was:
`gltf-transform optimize source/Bus_1.glb source/output2.glb`

Window removal (original on left): 
<img width="1697" alt="Screenshot 2023-03-10 at 11 13 58 AM" src="https://user-images.githubusercontent.com/19869387/224405712-f5ce72f1-46ca-448a-a51a-9b0023356861.png">

In addition to removal, there is this little jaggedy transformation: 
<img width="300" alt="Screenshot 2023-03-10 at 11 14 50 AM" src="https://user-images.githubusercontent.com/19869387/224405936-72d51d2d-9fc9-4bf5-a0b1-19c1d776f46c.png">

**Comment by donmccurdy** [comment]
Hi! You can reduce or disable simplification error tolerance with:

```javascript
gltf-transform optimize input.glb output.glb --simplify 0.0000001
```

Or use `0` to disable simplification.

If you would like to share the model, I can see if there are other options here.

**Comment by donmccurdy** [comment]
The "optimize" command is also just a general-purpose combination of other CLI commands. Depending on what's in the model, you can control the result more by running those commands individually:

https://github.com/donmccurdy/glTF-Transform/blob/5515ebdba1508eaf3eb8677be2f13d929ebdf61c/packages/cli/src/cli.ts#L214-L269

**Comment by donmccurdy** [comment]
@harrycollin could you file a new issue or discussion thread, with an example .glb showing the issue?
