### ISSUE TITLE
Install the CLI is fail

### ISSUE THREAD

**Issue by liuliu-imemachine** [donmccurdy/glTF-Transform#869]
node.js version = v16.13.0

npm install --global @gltf-transform/cli
error message:

npm ERR! sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.13.3/libvips-8.13.3-win32-x64.tar.br
npm ERR! sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies

**Comment by donmccurdy** [comment]
If you happen to be installing this from China, a mirror site provided by Alibaba may be necessary. I believe the commands below would enable it:

```
npm config set sharp_binary_host "https://npmmirror.com/mirrors/sharp"
npm config set sharp_libvips_binary_host "https://npmmirror.com/mirrors/sharp-libvips"
npm install --global @gltf-transform/cli
```

**Comment by donmccurdy** [comment]
Closing because I cannot reproduce the issue and haven't heard back, but I'm happy to continue discussing if you are still having trouble. Thanks!

**Comment by fy0** [comment]
> If you happen to be installing this from China, a mirror site provided by Alibaba may be necessary. I believe the commands below would enable it:
> 
> ```
> npm config set sharp_binary_host "https://npmmirror.com/mirrors/sharp"
> npm config set sharp_libvips_binary_host "https://npmmirror.com/mirrors/sharp-libvips"
> npm install --global @gltf-transform/cli
> ```

Same problem, and it works.
It's a bit strange because i was able to install it directly using npm at last year.

**Comment by donmccurdy** [comment]
Thanks @fy0! I've moved this into the installation docs in https://github.com/donmccurdy/glTF-Transform/commit/fa7efcfe9e06912415bac728f498a29b0d5874e2.
