### ISSUE TITLE
dedup: group accessors and images to accelerate comparsions

### ISSUE THREAD

**Issue by kzhsw** [donmccurdy/glTF-Transform#881]
**Is your feature request related to a problem? Please describe.**
In function `dedupAccessors` and `dedupImages`, nested loops was used for checking duplication of accessors and textures, this should be fast when count of accessors or images are small, but slower when there are a large number of it.

**Describe the solution you'd like**
Group accessors and images by a quick hash of some properties, then do the nested loop for each group. 
Maybe like the pesudo code here:
```typescript
function detectDuplicates(accessors: Accessor[]): Map<Accessor, Accessor> {
	const multiMap = new MultiValueMap<number, Accessor[]>;
	for (let i = 0; i < accessors.length; i++) {
		const a = accessors[i];
		const hashCode = makeHashCode(a.getType(), a.getComponentType(), a.getCount(), a.getNormalized(), a.getArray()!.byteLength);
		multiMap.add(hashCode, a);
	}
	const duplicateAccessors: Map<Accessor, Accessor> = new Map();
	multimap.values().forEach(accessors => {
		for (let i = 0; i < accessors.length; i++) {
			const a = accessors[i];
			const aData = BufferUtils.toView(a.getArray()!);

			if (duplicateAccessors.has(a)) continue;

			for (let j = 0; j < accessors.length; j++) {
				const b = accessors[j];

				if (a === b) continue;
				if (duplicateAccessors.has(b)) continue;

				if (a.getType() !== b.getType()) continue;
				if (a.getComponentType() !== b.getComponentType()) continue;
				if (a.getCount() !== b.getCount()) continue;
				if (a.getNormalized() !== b.getNormalized()) continue;
				if (BufferUtils.equals(aData, BufferUtils.toView(b.getArray()!))) {
					duplicateAccessors.set(b, a);
				}
			}
		}
	});

	return duplicateAccessors;
}
```

**Describe alternatives you've considered**
Keep existing mechanism and warn users with too many images or accessors in docs or in cli.

**Additional context**
screenshots about running `dedup` with a glb file with ~18k meshes:
![The call tree view of chrome profiler](https://user-images.githubusercontent.com/120431159/228725822-3fa0ee4d-8a4d-41ea-a64e-df5ae08aa380.png)
![The source view of detectDuplicates after profiling](https://user-images.githubusercontent.com/120431159/228725851-01efa2e8-8b8c-4f61-b6b9-d79ba6d3c9ec.png)

**Comment by donmccurdy** [comment]
Hi @kzhsw! Would you be able to share an example glTF file that's running slower than you'd hoped with the `dedup()` function? Or would you want to do a PR for this improvement? Thanks!

**Comment by donmccurdy** [comment]
Another quick savings would be to change the loops slightly, so the inner loop begins just after the current index of the outer loop, avoiding some repeated comparisons:

```js
for (let i = 0; i < accessors.length; i++) {

  // ...

  for (let j = i + 1; j < accessors.length; j++) {
```

**Comment by kzhsw** [comment]
> Hi @kzhsw! Would you be able to share an example glTF file that's running slower than you'd hoped with the `dedup()` function? Or would you want to do a PR for this improvement? Thanks!

The model used for profiling is a autodesk revit model converted from rvt to glb, which contains some business stuff which can not be shared here, here is some info about the json of the model and the stats from <gltf.report>:
![gltf-info](https://user-images.githubusercontent.com/120431159/229020258-8917be83-fd02-4624-9eea-47ac38e377c3.png)
![stats](https://user-images.githubusercontent.com/120431159/229020471-1aa69123-c482-4f5b-aff4-ac0bb72ec9db.png)

**Comment by donmccurdy** [comment]
Let's start with #885 – on some quick tests that alone will reduce the dedup time by about half.
