### ISSUE TITLE
can't use gltf-Transform in threejs loader

### ISSUE THREAD

**Issue by mostafamdy** [donmccurdy/glTF-Transform#882]
Hi thanks for this tool 
I get this error when trying to use gltf-transform to compress glb file
![Screenshot 2023-03-30 173106](https://user-images.githubusercontent.com/76405917/228899445-d1dd4107-baa7-4a81-bb4a-d2cbdd05dd62.png)

I am using this command `gltf-transform sparse input.glb output.glb`

**Comment by donmccurdy** [comment]
@mostafamdy could you attach the glTF file you're asking about? .ZIP files can be included in GitHub comments.

**Comment by mostafamdy** [comment]
thanks 
here you can find gltf file this file works on [GLTF Viewer](https://gltf-viewer.donmccurdy.com/)
https://drive.google.com/file/d/1gsXwd-zOk6xmmzxhbq7xUPQy0gDX99d4/view?usp=share_link

**Comment by donmccurdy** [comment]
Thanks @mostafamdy! I'm having trouble reproducing the issue, so a few more questions:

What version of gltf-transform are you using? (try `gltf-transform --version`)

After using gltf-transform on the model, does the resulting GLB work correctly in https://gltf-viewer.donmccurdy.com/ for you?

**Comment by mostafamdy** [comment]
yes it works on https://gltf-viewer.donmccurdy.com/ 
gltf-transform version 3.0.1-alpha.0

**Comment by mostafamdy** [comment]
It works 😄 I was using an old version of threejs
