### ISSUE TITLE
quantize: incorrect bounding box after quantize

### ISSUE THREAD

**Issue by kzhsw** [donmccurdy/glTF-Transform#890]
**Describe the bug**
When using a model quantized by gltf-transform in babylon.js, some parts of the model disappears if the camera is moved and scene border passes by the center of the model.

![27](https://user-images.githubusercontent.com/120431159/229266795-cbf74599-be61-4482-ba69-5a19c1fe241b.gif)

If the frustum clipping is disabled, like in <https://playground.babylonjs.com/#N036XF#1>, this issue does not reproduce.

The bounding box of quantized model:
![bbox quantized](https://user-images.githubusercontent.com/120431159/229267010-1300d0e8-5c70-4d2d-a829-e9f476d7cb42.png)

The bounding box of original model:
![bbox orig](https://user-images.githubusercontent.com/120431159/229267044-6cc8473f-3200-4430-9a3c-59e5c12205d3.png)

**To Reproduce**
1. Go to <https://gltf.report/> and drag in `model_orig.glb`
2. Click on Script button
3. Use code below to do a quantize
```js
import { quantize } from '@gltf-transform/functions';

await document.transform(
	quantize()
);
```
4. Run and export
5. Open <https://playground.babylonjs.com/#N036XF> and load the exported model in the right panel.

**Expected behavior**
1. All parts of the model keeps visible even if he camera is moved and scene border passes by the center of the model.

**Versions:**
 - Version: gltf-transform v3.0.4
 - Environment: Browser

**Additional context**

[models.zip](https://github.com/donmccurdy/glTF-Transform/files/11128410/models.zip)
* `model_orig.glb` is the model before quantize, which is ok
* `model_gltf-transform.glb` is the model quantized with steps above, which can reproduce this issue.
* `model_gltfpack.glb` is the model quantized with `gltfpack -ke -kn -km` using `gltfpack 0.18`, which is ok

Another thing to notice is that gltfpack uses u16 for position and gltf-transform uses i16_norm for position, this could make a difference.
![gltfpack](https://user-images.githubusercontent.com/120431159/229267104-450e62be-d855-4ebb-b8ba-e84020793c5e.png)
![gltf-transform](https://user-images.githubusercontent.com/120431159/229267135-41f9ffdc-c4e7-48f1-8134-6ebb655bf6ee.png)

**Comment by donmccurdy** [comment]
I think this would need to be reported to the Babylon.js developers -- frustum culling is up to the rendering engine, and it may be that there's a bug related to quantized data in Babylon.js. Use of signed integers here is intentional.

**Comment by kzhsw** [comment]
> I think this would need to be reported to the Babylon.js developers -- frustum culling is up to the rendering engine, and it may be that there's a bug related to quantized data in Babylon.js. Use of signed, normalized integers here is intentional.

Reported here: <https://forum.babylonjs.com/t/incorrect-bounding-box-after-loading-a-model-quantized-by-gltf-transform/39561>

**Comment by bghgary** [comment]
FYI: I have confirmed this is a Babylon.js bug. Will be fixed shortly.

**Comment by sebavan** [comment]
For reference: https://github.com/BabylonJS/Babylon.js/pull/13696

**Comment by donmccurdy** [comment]
Thanks @kzhsw for the report, and @bghgary and @sebavan for the fast fix! 🎊
