### ISSUE TITLE
`simplify` breaks model / causes validation errors and buffer range issues

### ISSUE THREAD

**Issue by hybridherbst** [donmccurdy/glTF-Transform#902]
**Describe the bug**
A specific model breaks (fails validation / doesn't load in most viewers) after running `gltf-transform simplify` on it.

**To Reproduce**
1. Go to https://sketchfab.com/3d-models/plant-3-5ecd9744ff6f4aa09766d796eec161ee
2. Download the GLB model
3. Check in the Validator
4. Run `gltf-transform simplify plant_03.glb plant_03.simplified.glb`
5. Check again in the Validator
6. Note it now has numerous errors about accessor ranges. It seems to still load in three.js-based viewers but doesn't load in others

**Expected behavior**
Returns a file without introducing new validation errors

**Versions:**
 - Version: [3.1.7]
 - Environment: [CLI]

**Comment by donmccurdy** [comment]
Steps to reproduce the error on the current release:

1. Download "Plant 3" above
2. `gltf-transform prune plant.glb plant.prune.glb --no-keep-attributes --no-keep-leaves`
3. ✅ No validation issues
4. `gltf-transform weld plant.prune.glb plant.weld.glb --tolerance 0.0001 --tolerance-normal 0.5`
5. ✅ No validation issues
6. `gltf-transform simplify plant.weld.glb plant.simple.glb --error 0.01 --ratio 0.01`
7. ❌ Many validation issues
