### ISSUE TITLE
core: optimize the performance of isRefMap

### ISSUE THREAD

**Issue by kzhsw** [donmccurdy/glTF-Transform#908]
**Is your feature request related to a problem? Please describe.**
In a recent benchmark on resample function of gltf-transfrom git ([618c506](https://github.com/donmccurdy/glTF-Transform/commit/618c506920dd49c49ec36287febac934b3b87d95)), I found that the function `isRefMap` consumes most (26.8%) of CPU time:
![chrome performance profiler](https://user-images.githubusercontent.com/120431159/231983312-c0f80e7c-3dca-460a-abe5-0ceb3afec0ef.png)

**Describe the solution you'd like**
Replace isRefMap to code below, which runs much faster according to benchmark:
```typescript
const hasOwnProperty = Object.prototype.hasOwnProperty;

export function isRefMap(value: unknown): boolean {
	if (!isPlainObject(value)) {
		return false;
	}
	const objectValue = value as object;
	for (const k in objectValue) {
		if (!hasOwnProperty.call(value, k)) {
			continue;
		}
		return objectValue[k as keyof typeof objectValue] as object instanceof GraphEdge;
	}
	return false;
}
```
This could be done by changing `packages/core/src/utils/ref-utils.ts` file, and replace import of `isRefMap` in file `packages/core/src/properties/property.ts`.
![chrome performance profiler after patch](https://user-images.githubusercontent.com/120431159/231986286-4ce26392-ed7a-45bc-bb85-a7c7b3c56242.png)

**Describe alternatives you've considered**
* Impl this in [property-graph](https://github.com/donmccurdy/property-graph) repo instead of changing glTF-Transform.
* Monkey patch `property-graph` at runtime.
* Submit this to v8 or spidermonkey issue tracker and hope they would optimize this `Object.values(value)[0]`.

**Additional context**
The model used for benchmark: Arm.glb from [Archive.zip](https://github.com/donmccurdy/glTF-Transform/files/8081046/Archive.zip) from https://github.com/donmccurdy/glTF-Transform/issues/501

Also, according to the benchmark result above, performance of `GraphNode#get()` might need futher optimizations.

The benchmark code, which runs in the root dir of a built glTF-Transform repo :
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<input type="file" id="file0">
<button type="button" id="btn0">Click</button>
<script type="importmap">
{
  "imports": {
    "@gltf-transform/core": "./packages/core/dist/core.modern.js",
    "@gltf-transform/extensions": "./packages/extensions/dist/extensions.modern.js",
    "@gltf-transform/functions": "./packages/functions/dist/functions.modern.js",
    "property-graph": "./node_modules/property-graph/dist/property-graph.modern.js",
    "ndarray-pixels": "https://esm.run/ndarray-pixels",
    "ndarray-ops": "./node_modules/ndarray-ops/ndarray-ops.js",
    "ndarray": "https://esm.run/ndarray",
    "get-pixels": "./node_modules/get-pixels/dom-pixels.js",
    "save-pixels": "./node_modules/save-pixels/save-pixels.js",
    "ktx-parse": "./node_modules/ktx-parse/dist/ktx-parse.modern.js",
    "ndarray-lanczos": "./node_modules/ndarray-lanczos/dist/ndarray-lanczos.modern.js"
  }
}
</script>
<script type="module">
  import {WebIO} from '@gltf-transform/core';
  import {ALL_EXTENSIONS} from '@gltf-transform/extensions';
  import {resample} from '@gltf-transform/functions';

  let webIo = new WebIO();
  webIo.registerExtensions(ALL_EXTENSIONS);
  document.getElementById('btn0').onclick = () => {
    let files = document.getElementById('file0').files;
    if (!files || !files.length) {
      return;
    }
    let fr = new FileReader();
    fr.onload = async () => {
      for (let i = 0; i < 10; i++) {
        let doc = await webIo.readBinary(new Uint8Array(fr.result));
        performance.mark('resample start');
        await doc.transform(resample());
        performance.mark('resample end');
      }
      console.log('done');
    };
    fr.readAsArrayBuffer(files[0]);
  };

</script>
</body>
</html>

```

The full patch for glTF-Transform:
[the_patch.patch](https://github.com/donmccurdy/glTF-Transform/files/11230695/the_patch.patch)

**Comment by donmccurdy** [comment]
Related:

- https://github.com/donmccurdy/property-graph/pull/80
- https://github.com/donmccurdy/glTF-Transform/pull/910

I went ahead and pulled in @kayhhh's performance improvements to `isRefMap`, they are on the `main` branch of glTF Transform now, unreleased. I've been trying to do benchmarks on the `Arm.glb` sample provided, but unfortunately I'm not seeing very much difference there, with either the isRefMap optimizations or #909. 

@kzhsw could you check that #909 is having the effect you intend, sharing steps to reproduce and the benchmark numbers before / after? 

I've been running bunchmarks as shown below:

```bash
# run profile
node --prof packages/cli/bin/cli.js resample in.glb out.glb

# preprocess profile
node --prof-process --preprocess -j isolate*.log > profile.json

# display profile
npx speedscope profile.json
```

If there are other examples with more obvious performance issues, those might be helpful as well.

**Comment by kzhsw** [comment]
https://github.com/donmccurdy/property-graph/pull/80 had done almost the same optimization of this issue.
