### ISSUE TITLE
Texture Compress fails ( "o is not a function" )

### ISSUE THREAD

**Issue by canberka** [donmccurdy/glTF-Transform#965]
**Describe the bug**
Texture compress at script Api has a failure in project
![37ffe3ed-6885-406a-8abc-1e91cd8a0f20](https://github.com/donmccurdy/glTF-Transform/assets/36857390/cdceaea6-104a-4703-8892-e8c06474eecb)

The way we follow

Install:
npm install --save @gltf-transform/core @gltf-transform/extensions @gltf-transform/functions
npm install sharp

```
Code:
import { Document, NodeIO } from '@gltf-transform/core';
import { KHRONOS_EXTENSIONS } from '@gltf-transform/extensions';
import draco3d from 'draco3dgltf';

// Configure I/O.
const io = new NodeIO()
    .registerExtensions(KHRONOS_EXTENSIONS)
    .registerDependencies({
        'draco3d.decoder': await draco3d.createDecoderModule(), // Optional.
        'draco3d.encoder': await draco3d.createEncoderModule(), // Optional.
    });

// Read from URL.
const document = await io.read('path/to/model.glb');

// Write to byte array (Uint8Array).
const glb = await io.writeBinary(document);

import { resample, prune, dedup, draco, textureCompress } from '@gltf-transform/functions';
import * as sharp from 'sharp'; // Node.js only.

await document.transform(
    // Compress mesh geometry with Draco.
    draco(),
    // Convert textures to WebP (Requires glTF Transform v3 and Node.js).
    textureCompress({
        encoder: sharp,
        targetFormat: 'webp',
        resize: [1024, 2024],
    }),
);

```

**Expected behavior**
Draco and texture compress together.

**Versions:**
![98f73f15-d2ec-4ba3-8041-2da4ce9adebf](https://github.com/donmccurdy/glTF-Transform/assets/36857390/c192db85-dfa7-47c9-8d10-1b26d862cac5)

**Additional context**
Tried at Mac and Windows

**Comment by MultiTrickFox** [comment]
I have the same error going on. My project is built with node.js, up-to date packages (@gltf-transform and sharp) but getting this exact error.

I tried downgrading the @gltf-transform and sharp packages too.. but even the past versions give the same error..

**Comment by donmccurdy** [comment]
It looks like the import statement for Sharp is incorrect:

```javascript
import * as sharp from 'sharp'; // incorrect ❌

import sharp from 'sharp'; // correct ✅
```

I see that was wrong or outdated in the docs, and it's fixed in https://github.com/donmccurdy/glTF-Transform/commit/1a2ea75f0d6b976c965aacbd3cbd349e866785b1. If you are using a bundler, different requirements are possible.

Also, EXT_texture_webp is not a Khronos extension, so you'll need to import and register `ALL_EXTENSIONS` rather than `KHRONOS_EXTENSIONS` in this case.
