### ISSUE TITLE
Error in write.groupByParent `Cannot read properties of undefined`

### ISSUE THREAD

**Issue by marwie** [donmccurdy/glTF-Transform#978]
**Describe the bug**
We have a model with a lot of blendshapes and draco mesh compression warnings ("reduced vertex count unexpectedly")
When running `draco` with the glb the process fails to write the result

**To Reproduce**
1. Download provided glb
2. Run `gltf-transform draco "path\scene.glb" "path\scene.o.glb"`
3. See error

**Expected behavior**
Glb being written, perhaps without draco compression where it failed

**Versions:**
 - Version: 3.2.1 but also reproduced with 3.4
 - Environment: node

**Additional context**

Model: https://drive.google.com/file/d/1xPKC2gixHsGYBTdX9iGEeOFpsmAccVei/view?usp=sharing

The error is caused in writer grouping:
![image](https://github.com/donmccurdy/glTF-Transform/assets/5083203/939a1188-a7e3-451d-866c-1f1a4101ab12)

![image](https://github.com/donmccurdy/glTF-Transform/assets/5083203/109a1607-47c1-4325-9394-f08d69768014)

When ignoring groups with 0 accessors the file is written:

![image](https://github.com/donmccurdy/glTF-Transform/assets/5083203/720c33cb-5d03-4f36-9322-7fdbba0d8f67)

![image](https://github.com/donmccurdy/glTF-Transform/assets/5083203/af7bcc54-f5ae-4a87-9eaa-445d63015385)

**Comment by donmccurdy** [comment]
To be resolved by https://github.com/donmccurdy/glTF-Transform/pull/981.
