### ISSUE TITLE
Material count changed after meshopt 

### ISSUE THREAD

**Issue by marwie** [donmccurdy/glTF-Transform#980]
**Describe the bug**
Using meshopt compression seems to change the material count

**To Reproduce**
1. Download glb and apply meshopt compression

**Expected behavior**
Material count is unchanged.

**Versions:**
 - Version: gltf-transform 3.2.1, reproduces with 3.3
 - Environment: node

**Additional context**
Files for testing: https://drive.google.com/file/d/1HrlsYD_PtpZPJ7LPvyGU8FOWQcIWK_y6/view?usp=sharing

Same glb as here: https://gltf-report.canny.io/bugs/p/glb-compressed-with-meshopt-shows-error-in-console-cannot-read-properties-of-und

glb before compression, see material list has 15 material (including a material 34)

![image](https://github.com/donmccurdy/glTF-Transform/assets/5083203/2d0441f2-8e0c-4053-854e-83b97d1fa3a8)

After applying meshopt, Material 34 was removed
![image](https://github.com/donmccurdy/glTF-Transform/assets/5083203/0d419edb-9dd2-4953-9bf8-0a21603942ff)

Material 34 with emission doesnt remove it:
![image](https://github.com/donmccurdy/glTF-Transform/assets/5083203/2edb4417-51b6-4c15-9372-3bec5c912ea2)

Logs are identical (if emission is on or off in material 34)
```
gltf-transform meshopt "C:\Users\....." "...."
info: prune: Removed types... Accessor (21)
warn: quantize: Skipping TEXCOORD_0; out of [0,1] range.
warn: quantize: Skipping TEXCOORD_0; out of [0,1] range.
warn: quantize: Skipping TEXCOORD_0; out of [0,1] range.
warn: quantize: Skipping TEXCOORD_0; out of [0,1] range.
warn: quantize: Skipping TEXCOORD_0; out of [0,1] range.
info: prune: Removed types... Accessor (43)
info: Book5.glb (1.85 MB) → Book5.o.glb (1.68 MB)
```

**Comment by donmccurdy** [comment]
Running `dedup` alone will give:

```
dedup: Found 1 duplicates among 16 materials.
```

So probably the offending code the quantization implementation is this:

https://github.com/donmccurdy/glTF-Transform/blob/407454d4ca184334ce362c9097555fabe5f28916/packages/functions/src/quantize.ts#L123-L126

This cleanup occurs because quantization _may_ need to clone and modify materials using KHR_materials_volume, to preserve original volume thickness. We could probably track which materials were touched during quantization and only attempt to deduplicate those — in which case this asset should be unchanged.

However, that doesn't scale so well when looking at all the cleanup we need to do in different operations in the `@gltf-transform/functions` module, it's much easier to use 'prune' and 'dedup' when possible, as I'm doing here. So perhaps the question is ... does removing a duplicated material create a problem for you?

**Comment by marwie** [comment]
Thanks for the explanation

It creates a problem when using e.g. animation pointers / json pointers with the material index where the index doesnt exist anymore. 

Is it possible to register that reference to gltf-transform in which case the dedup would not occur or to receive events / information about the change in a event(?) before writing back the extensions in which cleanups on our side (in our extension) could be done?

**Comment by donmccurdy** [comment]
Is your KHR_animation_pointer implementation creating references (i.e. setRef) from the JSON pointers? That isn't enough to prevent de-duplication by itself, but if so, I think we could store metadata on the reference and use that in the `dedup` implementation. Something like:

```js
const pointer = pointerExtension.createPointer();

class Pointer extends ExtensionProperty {
  ...
  setPointer(object) {
    return this.setRef('pointer', object, {modifier: true});
  }
}
```

Idea here being that if a reference indicates it _modifies_ the child resource, dedup() and other operations can realize that merging that resource with another will change the scene. Similar to how we store channel occupancy on textures:

https://github.com/donmccurdy/glTF-Transform/blob/407454d4ca184334ce362c9097555fabe5f28916/packages/extensions/src/khr-materials-clearcoat/clearcoat.ts#L90-L93

The dedup() function would have to be updated as well.

**Comment by marwie** [comment]
We dont use `setRef` etc right now but could perhaps change that

How would we use it in dedup? You mean if we re-implement dedup on our side?

**Comment by donmccurdy** [comment]
@marwie I think it will be necessary to use [references, reference lists, or references maps](https://github.com/donmccurdy/property-graph#api) in some form, to keep the right connections throughout processing. But wouldn't necessarily need to write complete user-facing getters/setters in the way that glTF Transform's own extensions do, just make the reference.

I'm fine with modifying `dedup` (here) to check for these references. It would look something like:

```js
const keep = document.getGraph().listParentEdges(material)
  .some((ref) => ref.getAttributes().modifier === true);
```

The library already has to do something similar for AnimationChannel references, and so it seems easy enough to generalize this:

https://github.com/donmccurdy/glTF-Transform/blob/407454d4ca184334ce362c9097555fabe5f28916/packages/functions/src/join.ts#L124-L126

**Comment by marwie** [comment]
I've added a setRef call for material pointers which seems to prevent the issue from happening (using the latest gltf-transform release).

**Comment by marwie** [comment]
Yep adding something like you proposed above prevents materials from being removed. I'll make a PR in a little bit (I think it would be useful to also log that x materials were kept because of references) 😊

**Comment by marwie** [comment]
I'm also wondering if there could/should be a callback mechanism for reacting for deduplication - e.g. in which case our json pointer extension could update the pointers

**Comment by marwie** [comment]
I understand and it makes sense - I'll have to revisit this then at another point (I think I have said that multiple times before as well 😅 one day....)

**Comment by donmccurdy** [comment]
@marwie Are we OK to close this issue with #990 and #995 merged?

**Comment by marwie** [comment]
Yes, thank you! 🙏
