### ISSUE TITLE
Type error if compiled into a project with "skipLibCheck": false

### ISSUE THREAD

**Issue by bhouston** [donmccurdy/glTF-Transform#996]
**Describe the bug**

When compiling into a Typescript project you will get this error if you have "skipLibCheck" set to false.  This is usually an indicator that there is a problem with typing:

```
../../node_modules/@gltf-transform/functions/dist/resample.d.ts(2,31): error TS2307: Cannot find module 'keyframe-resample' or its corresponding type declarations.
```

**To Reproduce**

Compile the Node.js example code on the home page and be sure to reference @gltf-transform/functions

https://gltf-transform.dev

**Expected behavior**

No type errors emitted.

**Versions:**
 - Version: 3.4.2
 - Environment: Node.js 19.7.0
 - Typescript: 5.1.3

**Comment by donmccurdy** [comment]
Thanks! Hmm, so what's happening here is:

1. `keyframe-resample` is in `devDependencies`, not `dependencies`, so Microbundle will inline the required code
2. Apparently Microbundle *does not* inline the required type definitions
3. Exported references to `keyframe-resample` (below) cause the errors reported

https://github.com/donmccurdy/glTF-Transform/blob/df4adfb9e1f92977447838b3d63a51effc42a4bd/packages/functions/src/resample.ts#L16-L26
